### ISSUE TITLE
Forms: Discuss field name attributes

### ISSUE THREAD

**Issue by mparke** [linode/manager#1008]
Discuss the application of name attributes where appropriate and/or missing on form fields. Apply changes decided on.

**Comment by mparke** [comment]
docs example using name attributes: https://facebook.github.io/react/docs/forms.html#handling-multiple-inputs

**Comment by mparke** [comment]
re: radio inputs, using the name attribute is actually less js/react work, 

```
            name={`config-${field}`}
            id={`config-${field}-${value}`}
            disabled={this.state.loading}
            // checked={this.state[field] === value}
```
^ state in UI correct without having to update checked property, why do the extra work when it's native behavior?

**Comment by eatonphil** [comment]
Sounds good to me, I must have forgotten about this.

**Comment by mparke** [comment]
anyone else have opinions? @abemassry @na3d

**Comment by abemassry** [comment]
And my bow 🏹

**Comment by mparke** [comment]
General usage has consensus, closing
