### ISSUE TITLE
Group labels wrap on space

### ISSUE THREAD

**Issue by briansteffens** [linode/manager#1009]
![screen shot 2017-01-17 at 10 17 58 am](https://cloud.githubusercontent.com/assets/4149249/22026246/3e83b08e-dc9e-11e6-8507-d012536cdd70.png)

**Comment by eatonphil** [comment]
Header tds should span all columns

**Comment by mparke** [comment]
> Header tds should span all columns
I assume you mean `th`, and what do you mean by span all columns?

**Comment by mparke** [comment]
thanks for clarification
