### ISSUE TITLE
Design: Alternative navigation and utilities

### ISSUE THREAD

**Issue by mparke** [linode/manager#1026]
In relation to aligning parts of the header ( see #839 ), I prototyped an alternative navigation solution that removes the sidebar. 

Makes brand and other utility alignment with the content cleaner, and promotes content focus. 

Open to questions and feedback!

1. Primary navigation in the header aligned to content (annotated):

![centered_annotated](https://cloud.githubusercontent.com/assets/709951/22086033/d60f5b2c-dda4-11e6-9e54-821e7202beb6.png)

2. Same, non-annotated:

![centered_marketing_site_similar](https://cloud.githubusercontent.com/assets/709951/22086063/ec2c8baa-dda4-11e6-9d79-e887e2827fd5.png)

3. Alternative active navigation style:

![centered_tabs](https://cloud.githubusercontent.com/assets/709951/22086069/f549872e-dda4-11e6-84d6-0449592d9b7b.png)

4. Alternative, full-width, desktop:

![non_centered_desktop](https://cloud.githubusercontent.com/assets/709951/22086079/0c26e4f0-dda5-11e6-93d6-79c6711abff2.png)

**Comment by abemassry** [comment]
I feel like the sidebar leaves a little more room for future expansion.  One of the problems I've run into with horizontal nav is running low on space if you want more than a few things in there.  I do like the dropdown idea however, not sure how this would fit into a sidebar one though

**Comment by na3d** [comment]
Reorganizing the nav when we face that problem wouldn't be that difficult.  If this is the best solution right now, is it not better to go with this solution until it is no longer the best solution?

**Comment by mparke** [comment]
@abemassry Ideally, there would only be a few primary items to navigate, if there are a lot, we'd want to redefine primary vs. secondary.

Anything come to mind in regards to running out of space that would call for a sidebar?

**Comment by eatonphil** [comment]
First, noting that I have no strong feelings either way regarding the sidebar -- other than that we currently have it. While the aesthetics of the dropdown are pleasant, I do not follow the overall argument for getting rid of the sidebar nor -- in general -- what benefit there is from hiding the links in the new dropdown.

**Comment by mparke** [comment]
Screenshots updated from earlier

**Comment by mparke** [comment]
@eatonphil re: placing links in the dropdown, primary aim was to simplify/de-clutter if possible. 

If any of these are frequently accessed by the user, I'm all for keeping those out in the open.

**Comment by mparke** [comment]
Dropping an existing screenshot in here for comparison:

![screen shot 2017-01-18 at 5 57 33 pm](https://cloud.githubusercontent.com/assets/709951/22086631/abb36212-dda7-11e6-9f02-0a07b3498288.png)
