### ISSUE TITLE
Event notifications breaking

### ISSUE THREAD

**Issue by mparke** [linode/manager#1027]
After clicking around on the notifications we still have errors getting thrown

![screen shot 2017-01-18 at 3 12 50 pm](https://cloud.githubusercontent.com/assets/709951/22081224/beb49870-dd90-11e6-91f9-f6568847c6e9.png)

**Comment by eatonphil** [comment]
This has been taken care of, correct?

**Comment by mparke** [comment]
yes, this specific issue does not exist after https://github.com/linode/manager/pull/1099
