### ISSUE TITLE
Research: Responsive Layout

### ISSUE THREAD

**Issue by mparke** [linode/manager#1037]
A general item to invest some time looking at our current page layouts and how they function/respond to smaller screen sizes and mobile.

In addition, this research issue should be used to document approaches for updating existing flows to account for smaller screens, which may include but is not limited to: technical requirements, best practices, design ideas etc.

**Comment by mparke** [comment]
Closing for now, de-prioritized

**Comment by mparke** [comment]
Keeping this open so I don't forget

**Comment by na3d** [comment]
Closing as #1916 should address this.
