### ISSUE TITLE
Design: Event notification naming scheme / layout

### ISSUE THREAD

**Issue by mparke** [linode/manager#1040]
Suggestions were made re: event notifications in the realm of:

- {Noun}:{Verb}

- {Linode Label}:{Event Action}

Regarding time stamp, up for discussion. Please post comments if other ideas.

**Comment by na3d** [comment]
Handle how API is changing for events

**Comment by mparke** [comment]
General direction of wording updates to event notifications:

Goal is to be clear and concise., using present tense when in progress, and past tense when completed.
![screen shot 2017-01-25 at 11 11 24 am](https://cloud.githubusercontent.com/assets/709951/22298663/5295ba5c-e2ef-11e6-97b8-4017bdb983bc.png)

Hovered state
![screen shot 2017-01-25 at 11 11 35 am](https://cloud.githubusercontent.com/assets/709951/22298685/6843b21e-e2ef-11e6-9cc0-e80a9ff3e43f.png)

Some event types require a slightly different structure but should still be as simple as possible.
![screen shot 2017-01-25 at 11 12 11 am](https://cloud.githubusercontent.com/assets/709951/22298707/7b8a3aa0-e2ef-11e6-9e4b-37e51f4fc35a.png)

**Comment by eatonphil** [comment]
What is the difference between a read and unread event?

And could you give an example of an event associated with an interior object like a disk?

**Comment by rmcintosh** [comment]
I sort of like the "red vs. green (fail vs. success)" aspect of the current notifications - is that something we might implement to some extent here?

**Comment by eatonphil** [comment]
@rmcintosh not sure what you mean? Screenshot?

**Comment by mparke** [comment]
> What is the difference between a read and unread event?

Still looking at read/vs unread, focusing on click > page redirect and wording first.

> And could you give an example of an event associated with an interior object like a disk?

![screen shot 2017-01-25 at 11 23 27 am](https://cloud.githubusercontent.com/assets/709951/22299086/d6e5bcde-e2f0-11e6-91a1-525989620b32.png)

Right now it's specific to only the disk. It may make sense to also include which linode this belongs to.

**Comment by eatonphil** [comment]
I'm not a fan of the 0 padded hour. Also, how does this deal with failed or in progress events?

**Comment by rmcintosh** [comment]
<img width="785" alt="screen shot 2017-01-25 at 11 26 28 am" src="https://cloud.githubusercontent.com/assets/2124557/22299167/22e125ce-e2f1-11e6-89bd-5db16f4e1ef0.png">

**Comment by mparke** [comment]
> Also, how does this deal with failed or in progress events?

Still looking at failed/succeeded, will post an update. thanks for screenshot @rmcintosh

**Comment by mparke** [comment]
> I'm not a fan of the 0 padded hour.

Describe what you mean, what don't you like about it?

**Comment by eatonphil** [comment]
Personally, I'd prefer 2:45 to 02:45

**Comment by mparke** [comment]
@eatonphil ah yes, good catch, will adjust.

**Comment by mparke** [comment]
Alright, some updated versions which include state indication success/pending/failed

1. No Icon:
![screen shot 2017-01-25 at 2 34 09 pm](https://cloud.githubusercontent.com/assets/709951/22305960/6fafc0e4-e30b-11e6-99e4-1cc9d42d1576.png)

2. Success State
![screen shot 2017-01-25 at 2 25 13 pm](https://cloud.githubusercontent.com/assets/709951/22305717/8dd74e80-e30a-11e6-85b3-9ec7885f06de.png)

3. Pending State
![screen shot 2017-01-25 at 1 58 10 pm](https://cloud.githubusercontent.com/assets/709951/22305721/944dba24-e30a-11e6-976d-c911554d0716.png)

4. Failed State (Have not done anything additional in relation to messaging here yet. Why failure happened, what to do or who to ask, open to ideas)
![screen shot 2017-01-25 at 2 29 43 pm](https://cloud.githubusercontent.com/assets/709951/22305776/cbba9dd8-e30a-11e6-8a47-e8cbf1f879e9.png)

5. Read state ( grayed background )
![screen shot 2017-01-25 at 2 25 17 pm](https://cloud.githubusercontent.com/assets/709951/22305789/d8af919c-e30a-11e6-9966-085ee349b3c8.png)

Alternative state indication:

6. Less pronounced icon:
![screen shot 2017-01-25 at 2 40 03 pm](https://cloud.githubusercontent.com/assets/709951/22306478/6d295ee6-e30d-11e6-9179-eefa39acd89d.png)

7. Similar to classic:
![screen shot 2017-01-25 at 2 47 26 pm](https://cloud.githubusercontent.com/assets/709951/22306454/587fd132-e30d-11e6-8b8f-02cfb1ed3e27.png)

@rmcintosh @eatonphil

**Comment by abemassry** [comment]
@mparke i like the read state, and I like 6.
I feel like have all these green checkmarks and then a red X will make the problems stand out more which is good.

Does the pending one change to a completed state or is a new event issued.

**Comment by rmcintosh** [comment]
I like 6 as well

**Comment by mparke** [comment]
@abemassry that is a good question. I'm treating them here as 2 different events.

As part of status indication on a Linode though, I would expect it to behave that way, have a single item change from pending > complete.

**Comment by na3d** [comment]
It seems odd to have the redundancy of  "[x time] ago at [time]".

**Comment by mparke** [comment]
@na3d Agreed. Adjusting.

Thanks for feedback everyone. May be sticking with 1. for the time being to keep it simple/minimal while I work on a better case for more icon usage.
