### ISSUE TITLE
Research: Alerts UI States

### ISSUE THREAD

**Issue by mparke** [linode/manager#1044]
This is an item to simply research and document existing Linode alert states to serve as a basis for design updates when implementing.

**Comment by eatonphil** [comment]
Please post a screenshot (and describe behavior if necessary) for every alert UI.

**Comment by mparke** [comment]
pending migration:

![pending_migration](https://cloud.githubusercontent.com/assets/709951/22697554/c561bd80-ed1f-11e6-9ce0-b97d904865af.png)

scheduled migration pending:

![scheduled_migration](https://cloud.githubusercontent.com/assets/709951/22697562/cca640de-ed1f-11e6-9e70-2c9c83da6df1.png)

**Comment by mparke** [comment]
pending migration:

![pending_migration](https://cloud.githubusercontent.com/assets/709951/22697644/21cd11f0-ed20-11e6-918a-cbcd9ea0d9a3.png)

scheduled migration pending:

![scheduled_migration](https://cloud.githubusercontent.com/assets/709951/22697660/2aa273ba-ed20-11e6-83a4-7016804fc3d0.png)

**Comment by mparke** [comment]
open important support ticket:

![open_important_ticket](https://cloud.githubusercontent.com/assets/709951/22697670/37051da6-ed20-11e6-8f60-67d5cd1b97a4.png)

open abuse ticket:

![open_abuse_ticket](https://cloud.githubusercontent.com/assets/709951/22697678/3e1a695c-ed20-11e6-9fc3-519f9e8b7e24.png)

**Comment by mparke** [comment]
kvm upgrade sidebar highlight:

![kvm_upgrade](https://cloud.githubusercontent.com/assets/709951/22697703/521426d2-ed20-11e6-8a11-c1dbe82b69af.png)

kvm upgrade details:

![kvm_upgrade_details](https://cloud.githubusercontent.com/assets/709951/22697719/593ad1cc-ed20-11e6-8e62-5fbd72d92191.png)

**Comment by mparke** [comment]
the following caps we're mocked in html based on source, so they may not be entirely complete, but they were the additional ones I found.

**Comment by mparke** [comment]
outstanding balance:

![screen shot 2017-02-07 at 4 33 41 pm](https://cloud.githubusercontent.com/assets/709951/22712934/8a29aa86-ed54-11e6-849a-ef4ce22ae5a4.png)

**Comment by mparke** [comment]
outages:

![screen shot 2017-02-07 at 4 37 09 pm](https://cloud.githubusercontent.com/assets/709951/22712950/9615db58-ed54-11e6-8bbd-8435c1ec4278.png)

![screen shot 2017-02-07 at 4 38 14 pm](https://cloud.githubusercontent.com/assets/709951/22712958/9aedc15e-ed54-11e6-9d90-a52a576b869e.png)

**Comment by mparke** [comment]
host maintenance example:

![screen shot 2017-02-07 at 4 32 10 pm](https://cloud.githubusercontent.com/assets/709951/22713306/e515dcfc-ed55-11e6-88d4-cea9670e99b6.png)

**Comment by mparke** [comment]
General sense of existing structure, wording, and color schemes documented here. Any outstanding and/or new banner types can be taken on a case by case when being designed and implemented.

feel free to re-open with comments as needed, closing for now.
