### ISSUE TITLE
Mockup networking page with table view

### ISSUE THREAD

**Issue by eatonphil** [linode/manager#1047]

**Comment by mparke** [comment]
@eatonphil I know the gist of this, but let me know if there was anything specific we needed in addition to table

**Comment by eatonphil** [comment]
There may be another row for your "global pool". I can explain more and all other requirements in person tomorrow.

**Comment by mparke** [comment]
cool, thanks

**Comment by mparke** [comment]
First iteration of table style views.

Does not include enable/disable for private address ( as currently in alpha ), or a row for "global pool".

Single IPv4/IPv6:

![linode - networking - summary table](https://cloud.githubusercontent.com/assets/709951/22983847/6d43601a-f371-11e6-8c80-f1945e238873.png)


Multiple IPv4, Single IPv6:

![linode - networking - summary table multiple ips](https://cloud.githubusercontent.com/assets/709951/22983846/6d3a3bfc-f371-11e6-8b17-b501695be781.png)

**Comment by eatonphil** [comment]
First off, I'd show both the subnet mask and the CIDR (slash notation) for every group. Different configurations use either / both for both ipv4 and ipv6. (Also, current manager uses "Name Servers" not "Nameservers" and I was sticking with that in the DNS pages.)

Second, after seeing this I don't really see any benefit in this particular table UI approach if we're going to break things out into 5 different tables.

Other notes: private ivp4 definitely has subnet mask, gateway and CIDR (which, granted, you did include); double check with somebody that link-local does not have any of these.

**Comment by mparke** [comment]
Updates:
- included slash notation for each group
- updated `Nameservers` to `Name Servers`
- left Link-Local IP as is for now, as it appears to be a single field, can update / adjust at time of implementation if needed
- added help links

Re: benefit of table approach, I realize after you mentioned this that some pieces really didn't make sense separately hah. so, I tried to fix this in the revised:

A version where layout is similar but public/private grouped. I'm not a fan of this, but it was a transition piece I figured I might as well include.

![linode - networking - summary table](https://cloud.githubusercontent.com/assets/709951/22993817/64c7130c-f392-11e6-8b63-6ea6096308a4.png)

Layout similar to existing:

![linode - networking - summary table pivoted](https://cloud.githubusercontent.com/assets/709951/22993818/64cb7c12-f392-11e6-8f8c-5b3be033ec9b.png)

Example with multiple entries:

![linode - networking - summary table pivoted multiple](https://cloud.githubusercontent.com/assets/709951/22993815/64c2e264-f392-11e6-9661-63a359b6c976.png)

Example with multiple entries considering collapsed/expanded state:

![linode - networking - summary table pivoted multiple collapsed](https://cloud.githubusercontent.com/assets/709951/22993816/64c3efba-f392-11e6-9de0-483a65a8fe2a.png)

**Comment by mparke** [comment]
numbered screen caps of updated versions

**Comment by na3d** [comment]
It seems weird to have so much unused screen on the right, and having to scroll or collapse to see more, but I can also understand not having too much information flooded onto the screen.

**Comment by mparke** [comment]
@na3d I will make a note to try them side by side again later, thanks for feedback. @eatonphil also taking a look

**Comment by mparke** [comment]
closing for now, can be re-opened with additional comments.
