### ISSUE TITLE
Mockup alternative layout

### ISSUE THREAD

**Issue by eatonphil** [linode/manager#1053]
Goals:

* More integrated search bar
* Notifications in separate dropdown
* Preserve clarity between account vs profile
* Space for sub-categories like StackScripts
* (potential) More flexible nav by replacing sidebar with context-sensitive secondary (or tertiary?) header

**Comment by eatonphil** [comment]
Folding in #1026

**Comment by eatonphil** [comment]
Two angles here.

First:

![screen shot 2017-01-23 at 5 28 56 pm](https://cloud.githubusercontent.com/assets/3925912/22225851/1204a11e-e192-11e6-8709-441c2a422add.png)
![screen shot 2017-01-23 at 5 29 03 pm](https://cloud.githubusercontent.com/assets/3925912/22225848/12007a80-e192-11e6-9ced-01ac94a699dd.png)
![screen shot 2017-01-23 at 5 29 14 pm](https://cloud.githubusercontent.com/assets/3925912/22225852/1204eea8-e192-11e6-85c0-69be75168bb2.png)
![screen shot 2017-01-23 at 5 29 23 pm](https://cloud.githubusercontent.com/assets/3925912/22225849/120129b2-e192-11e6-9fe0-a935deb27a0f.png)
![screen shot 2017-01-23 at 5 29 30 pm](https://cloud.githubusercontent.com/assets/3925912/22225850/1202263c-e192-11e6-9d6b-270a1c2ab9d2.png)

Second:

![screen shot 2017-01-23 at 5 31 18 pm](https://cloud.githubusercontent.com/assets/3925912/22225869/1da9fdfc-e192-11e6-9f7e-16bf05335ec2.png)
![screen shot 2017-01-23 at 5 31 36 pm](https://cloud.githubusercontent.com/assets/3925912/22225872/1daad394-e192-11e6-9908-29c1c7ddda12.png)
![screen shot 2017-01-23 at 5 31 44 pm](https://cloud.githubusercontent.com/assets/3925912/22225870/1daa162a-e192-11e6-8469-7aef7536c3b6.png)
![screen shot 2017-01-23 at 5 31 55 pm](https://cloud.githubusercontent.com/assets/3925912/22225873/1dab12f0-e192-11e6-87d3-e2c766726068.png)
![screen shot 2017-01-23 at 5 32 10 pm](https://cloud.githubusercontent.com/assets/3925912/22225871/1daa7ca0-e192-11e6-885b-61d2e910240f.png)

**Comment by abemassry** [comment]
I like the second it feels more like a dashboard or manager and allows room for more future expansion.

**Comment by eatonphil** [comment]
Forgot to fix, but the search bar could be aligned with the left-side of the content for extra relevance.

**Comment by eatonphil** [comment]
One more option, not a huge fan but just throwing it out there:

![screen shot 2017-01-24 at 10 01 38 am](https://cloud.githubusercontent.com/assets/3925912/22252430/26138afa-e21c-11e6-85fe-1ef6da15ca9c.png)
