### ISSUE TITLE
Take screenshot of actual manager using fonts and colors present in Mockups

### ISSUE THREAD

**Issue by mparke** [linode/manager#1055]
Review and mockup new font usage and applications

**Comment by eatonphil** [comment]
Current font is Avenir Font.

**Comment by na3d** [comment]
Also match border and background color from mockups for screens. #1054

**Comment by na3d** [comment]
Don't use create page unless 1046 is closed.

**Comment by mparke** [comment]
this change not currently relevant, can be reopened if needed
