### ISSUE TITLE
Design simplified backup view without history

### ISSUE THREAD

**Issue by eatonphil** [linode/manager#106]

**Comment by eatonphil** [comment]
![screen shot 2016-06-10 at 9 19 39 am](https://cloud.githubusercontent.com/assets/3925912/15965532/80e5a636-2eec-11e6-8e72-edf5cc3ba878.png)

**Comment by SirCmpwn** [comment]
Why do we need a detail page? Why not just a restore button? Also, why the change to give the cancel button its own header?

**Comment by eatonphil** [comment]
Because there are two kinds of restoring and there's not enough space to fit everything into this screen.

Chris wanted the cancel to be its own section.

**Comment by SirCmpwn** [comment]
Moving the manual backup restoration under the manual backup header would provide plenty of space for two buttons in each box.

**Comment by eatonphil** [comment]
I don't think there's any reason to do that though. I don't think there's a big gain and I don't think it makes things easier. You have four buckets and we show them to you. You decide what to do from there.

**Comment by SirCmpwn** [comment]
Relevant http://v4-alpha.getbootstrap.com/components/button-group/

**Comment by SirCmpwn** [comment]
It saves having another page, which incurs mental overhead and will 404 when the backup expires. I also don't like having the manual card be there all the time, we'd have to deal with how to make it look when there aren't any manual backups.

**Comment by eatonphil** [comment]
For each slot, when backups are not at that point (the first few weeks) or there are no manual backups, the backup slot card will not appear.

**Comment by eatonphil** [comment]
I am normally with you on cutting down on pages. I don't think doing it here is a big deal though.

**Comment by SirCmpwn** [comment]
Eh, that sounds pretty bad. This page won't look very nice when there's just one card.

**Comment by SirCmpwn** [comment]
Can you mock that up?

**Comment by eatonphil** [comment]
Maybe you're right, in which case we can have a placeholder saying it doesn't exist yet. That would also help to explain how things work. I will mock both up.

**Comment by SirCmpwn** [comment]
While you're at it, could you humor me by trying to use bootstrapish button groups to avoid the extra page?

Also, moving the cancel button is a stragely out of character move for Chris, who's been pushing that we should be making more money from backups (and the change calls out the cancel button).

**Comment by SirCmpwn** [comment]
Idea: no padding between the buttons and the bottom of the card.

**Comment by eatonphil** [comment]
-1 to no padding

**Comment by eatonphil** [comment]
![screen shot 2016-06-10 at 9 37 50 am](https://cloud.githubusercontent.com/assets/3925912/15966031/2dd0e322-2eef-11e6-993b-efcaa068b9d5.png)
![screen shot 2016-06-10 at 9 38 03 am](https://cloud.githubusercontent.com/assets/3925912/15966032/2dd43c52-2eef-11e6-9566-aabe76fc8afe.png)

**Comment by eatonphil** [comment]
I'll mock up using a dropdown as well and some extra details.

**Comment by SirCmpwn** [comment]
Strange empty space. Centered?  Also maybe should have a disabled button rather than no button if no backup is available.

**Comment by SirCmpwn** [comment]
![untitled](https://cloud.githubusercontent.com/assets/1310872/15966049/4ccc55c2-2eef-11e6-9fb5-ac71f6a5788d.png)

**Comment by eatonphil** [comment]
> Also, moving the cancel button is a stragely out of character move for Chris, who's been pushing that we should be making more money from backups (and the change calls out the cancel button).

I may have misunderstand what he wanted. In any case, we have the two options available and mocked up.

**Comment by SirCmpwn** [comment]
np

**Comment by eatonphil** [comment]
I don't think something like this is a good idea. The font still must be too small to even try to accommodate the information. 

![screen shot 2016-06-10 at 9 56 08 am](https://cloud.githubusercontent.com/assets/3925912/15966534/935a4c7c-2ef1-11e6-819a-e00a47924993.png)

**Comment by eatonphil** [comment]
And yes I'm skipping the point of the dropdown with other restore options. I am not focusing on that right now.

**Comment by SirCmpwn** [comment]
Information overload. Things users don't actually care about:

* type: auto (manual is elsewhere anyway)
* location (obviously it's your linode's datacenter)
* config profiles (wtf)
* disks (it's always all of them)
* total size required (just issue a warning on the UI when they try to restore it, or disable the button and leave a message)

**Comment by SirCmpwn** [comment]
Also, would ditch the card around the manual backup UI. Just a sentence like this:

"Last manual backup was taken at [date]"

"[Restore]"

**Comment by eatonphil** [comment]
Ok, I wasn't thinking too closely about everything. I was just thinking take everything from the details page and put it here.

* you're right that the type doesn't need to be there
* if the location is obvious, why is it in the current details page? But if it shouldn't be then that's cool with me too.
* same question for disks
* that makes sense

**Comment by SirCmpwn** [comment]
>if the location is obvious, why is it in the current details page? But if it shouldn't be then that's cool with me too.

I dunno, but let's not take design inspiration from the old manager :wink:

**Comment by eatonphil** [comment]
I missed the config profile section. I am not sure why it's there currently, so I just didn't drop that because I'm not clear how the backups work with config profiles.

**Comment by SirCmpwn** [comment]
Maybe present that info on a summary when attempting to restore it?

**Comment by eatonphil** [comment]
> Maybe present that info on a summary when attempting to restore it?

If we were dedicated to this view, perhaps. But I think it would make more sense to have it here.

**Comment by SirCmpwn** [comment]
Having the same disk info show up 3 times violates DRY, which applies to UIs as much as it applies to code IMO.

**Comment by eatonphil** [comment]
Where else would that info about a backup's disks show up?

**Comment by SirCmpwn** [comment]
Restore backup -> Linode creation flow -> detect that source is a backup and give an extended summary including info about disks

**Comment by SirCmpwn** [comment]
That modal sounds like the right place, then.

**Comment by eatonphil** [comment]
That is only if there is not enough disk space though.

**Comment by SirCmpwn** [comment]
Why not both? We should probably give you a moment to consider your actions before committing to them in this case.

**Comment by SirCmpwn** [comment]
We have to have some kind of UI to pick a linode to restore to anyway, could be a modal and could have space for the disk info.

**Comment by eatonphil** [comment]
> Why not both? We should probably give you a moment to consider your actions before committing to them in this case.

Yep, maybe.

> We have to have some kind of UI to pick a linode to restore to anyway, could be a modal and could have space for the disk info.

This already exists, but I just realized there is not an issue associated with that so the mockup is not on Github yet.

**Comment by SirCmpwn** [comment]
>This already exists, but I just realized there is not an issue associated with that so the mockup is not on Github yet.

Then would the disks fit there instead of here?

**Comment by eatonphil** [comment]
That is in the current details page. So yes. Also, when we take out all the elements you suggested (location, config profiles, disks, total size) we just get the same mockup I put up here initially. Is your point that the details page is just completely useless and the original button should just be "Restore" not "Details"?

**Comment by SirCmpwn** [comment]
Your original mockup was close to the money. My point is that the detail page doesn't need to exist because most of the details are unimportant, and we could probably fit two buttons in the box to deal with the two different kinds of restoration. Or we could use one restore button and a more flexible modal, perhaps with tabs for restore to new linode and to existing linode. The other point is that the manual backups thing should be styled differently from the auto ones and placed in a different place. Sorry this was unclear.

**Comment by eatonphil** [comment]
Ok then I'll be back in a bit with more complete designs on this.

**Comment by eatonphil** [comment]
Here is not diverging too much from the initial version.
![screen shot 2016-06-10 at 11 28 36 am](https://cloud.githubusercontent.com/assets/3925912/15969546/83dfc562-2efe-11e6-97e4-ea5a33f6bedb.png)

But I was thinking it doesn't make that much sense to have them each have their own controls. It would be easier to group them together and select one to restore from. We can even have the disks be here (I don't think they can/should be anywhere else).

![screen shot 2016-06-10 at 11 28 12 am](https://cloud.githubusercontent.com/assets/3925912/15969574/aaeb3614-2efe-11e6-8754-9c474e1070e0.png)
![screen shot 2016-06-10 at 11 28 21 am](https://cloud.githubusercontent.com/assets/3925912/15969582/b1fff1ec-2efe-11e6-9c0d-1892595d9cc5.png)

**Comment by eatonphil** [comment]
Whoops, title on the second one should be "Restore" not "Backups".

**Comment by eatonphil** [comment]
Cleanup up a few things on the page. I think it's more correct to call the slots along these lines.

![screen shot 2016-06-10 at 12 02 42 pm](https://cloud.githubusercontent.com/assets/3925912/15970589/5096375e-2f03-11e6-82d8-8cc39b69d999.png)

**Comment by SirCmpwn** [comment]
This is better, but I still don't feel like the manual backup fits among the automatic ones conceptually speaking.

**Comment by eatonphil** [comment]
Then it seems subjective at this point and worth asking around. I still think the distinction is clear enough and not having a copy of the restore field is nicer. In any case, the other option is simple and shouldn't need a mockup: remove the manual card and add a copy of the "Restore to" section to the manual backup section.

**Comment by SirCmpwn** [comment]
Cool, thanks. I think we have reached a good place to receive some feedback on these, and a mockup isn't necessary for what I have in mind. I'm going to wait for these new mockups to do the rounds before implementing them, if you don't mind.

**Comment by eatonphil** [comment]
No problem. I'm going to call this one done for this round.
