### ISSUE TITLE
Mockup DNS list

### ISSUE THREAD

**Issue by eatonphil** [linode/manager#1071]

**Comment by eatonphil** [comment]
![screen shot 2017-01-23 at 5 34 30 pm](https://cloud.githubusercontent.com/assets/3925912/22225914/442acc40-e192-11e6-8d1c-d11d761454e7.png)

**Comment by abemassry** [comment]
👍

**Comment by eatonphil** [comment]
"Master zone" should probably also be a column here

**Comment by eatonphil** [comment]
![screen shot 2017-01-24 at 10 41 39 am](https://cloud.githubusercontent.com/assets/3925912/22254117/b4a1b314-e221-11e6-97cc-940a02541b9b.png)

**Comment by caker** [comment]
My advice: An Activate / De-activate knob is not warranted here. Hardly ANYONE uses this feature.

**Comment by eatonphil** [comment]
@caker the active vs disabled field is a status like in the Linode list page:

![screen shot 2017-01-24 at 10 45 15 am](https://cloud.githubusercontent.com/assets/3925912/22254309/36c78fc6-e222-11e6-81d0-f9a5b0816c22.png)

So you would not be able to click it and change anything. Clicking on it would bring up a dropdown of actions. If you are able to activate / deactivate a zone I would imagine you'd do that somewhere deeper in the zone's settings.
