### ISSUE TITLE
Community Stackscripts Search Problems

### ISSUE THREAD

**Issue by martinmckenna** [linode/manager#10869]
Hi. I noticed on https://cloud.linode.com/linodes/create?type=StackScripts&subtype=Community, the stackscripts search field doesn't accept any whitespace, so you can't search for multi-word stackscripts

Also at some point these extra filtering options stopped working, so the tooltip hint isn't really accurate anymore

![Screenshot 2024-08-30 at 7 32 14 PM](https://github.com/user-attachments/assets/3e769e3f-4730-4dce-bdd0-7adbf161ebf7)

**Comment by abailly-akamai** [comment]
@martinmckenna I would have hoped to see a contribution from you, not just an ol' plain issue  🧌 🤣 

Thanks for sending!

**Comment by martinmckenna** [comment]
lmao @alioso i'm too lazy!!!

shoutout to cloud manager still being the cleanest codebase i've ever worked on, after changing companies 4 times after. I just can't remember how to write code in it

**Comment by bnussman-akamai** [comment]
Thanks for opening the issue @martinmckenna 💚 

We've implemented a new search parser and I think the easiest route for us right now would be to allow whitespace if the string is wrapped in quotes. We'll update the tooltip to be more clear.

![Screenshot 2024-09-06 at 1 07 02 PM](https://github.com/user-attachments/assets/e63b226d-166d-4bb4-8429-0858fad8ffba)

Think this is okay?
