### ISSUE TITLE
Improper error handling

### ISSUE THREAD

**Issue by Fujiwara16** [linode/manager#10864]
When enabling s3 object storage, the errors from the api 
```
https://cloud.linode.com/api/v4/object-storage/buckets Request Method: POST
``` 
are not shown in the dashboard. The popup window just closes.
I was enabling the object storage and it was responding with 400 due to :-
```
{
    "errors": [
        {
            "reason": "Bucket names must be between 3 and 63 characters, consist only of lowercase letters, numbers, . (period), and - (dash), start and end with a letter or number, and must not have adjacent . (period) and - (dash) characters.",
            "field": "name"
        }
    ]
}
```
Then too the dialog would just close without giving off any error.

**Comment by jaalah-akamai** [comment]
Thank you for issuing a ticket! This was actually very timely since we [recently implemented a fix](https://github.com/linode/manager/pull/10847) for this. It will be out in our next release 9/3 👍
