### ISSUE TITLE
[API] Invoices data is in ASC order

### ISSUE THREAD

**Issue by mmarif4u** [linode/manager#11029]
I hope I am posting this issue in the correct repository.

Currently, the API at https://api.linode.com/v4/account/invoices returns a list of data sorted in ascending order (oldest first).

I can see two options from here:

1- Sort the returned data with the newest first.
OR
2- Add a sort query parameter with options like ASC and DESC, allowing the user to sort the data as they prefer. (https://techdocs.akamai.com/linode-api/reference/get-invoices)

Thanks

**Comment by coliu-akamai** [comment]
Hi @mmarif4u, thanks for reaching out! Could you try these curl requests (and add your authorization token):

```
curl --request GET \
   --url 'https://api.linode.com/v4/account/invoices?page=1&page_size=100' \
   --header 'x-filter: {"+order":"desc","+order_by":"date"}' \
   --header 'accept: application/json' \
```
```
curl --request GET \
   --url 'https://api.linode.com/v4/account/invoices?page=1&page_size=100' \
   --header 'x-filter: {"+order":"asc","+order_by":"date"}' \
   --header 'accept: application/json' \
```

We were able to see the data being ordered by differently - I'll look into getting the tech docs updated to reflect this!

**Comment by coliu-akamai** [comment]
Glad that worked. 

I've submitted an internal ticket to update the documentation for that endpoint. Will let you know when it gets updated

**Comment by mmarif4u** [comment]
Not directly related to invoices, but still related to filters.

I was checking the Events endpoint and found that there is a `read` object, which can also be filtered.
https://techdocs.akamai.com/linode-api/reference/get-events

I tried using the `+or` and `+and` filters, but I had no success.
https://techdocs.akamai.com/linode-api/reference/filtering-and-sorting

Can you please help me understand how the filterable options can be used with the `x-filter` header?

Thanks

**Comment by coliu-akamai** [comment]
@mmarif4u Could you let me know the requests you're trying to send?

**Comment by mmarif4u** [comment]
@coliu-akamai the following is the request with the auth and x-filter headers.

`https://api.linode.com/v4/account/events?page=1&page_size=100`

 Filter header
`x-filter: {"+or":[{"read":"true"}],"+order":"desc","+order_by":"date"}`

I am trying to sort the events by the **read** status here.

**Comment by coliu-akamai** [comment]
Thanks @mmarif4u! I'm not seeing a `date` field for Events - did you mean to sort using the  `created` field?

`{ "+order":"asc", "+order_by":"created" }`

If you want all the Events where `read` is `true`, ordered by `created`, this should work:

`{ "read": true, "+order":"desc", "+order_by":"created" }`

I am seeing errors when I try to use `"+or"` or an explicit `"+and"` for this query when using the `read` field  -- let me check with the API team to see if they have any clarifications. The guide you linked is definitely the way to go for understanding filtering/sorting though!

**Comment by coliu-akamai** [comment]
@mmarif4u I checked with the API team - currently `read` is not able to be used in compound filters, but they are looking into the issue. I'll let you know when there are updates. 😄

**Comment by coliu-akamai** [comment]
Hi @mmarif4u, thanks for your patience. Unfortunately I'm not sure who to contact for this - I'd recommend reaching out to [Akamai Compute support](https://www.linode.com/support/) to see if they can help.  

Going to close this issue - if you have new Cloud Manager related issues, please feel free to open a one. Thanks!
