### ISSUE TITLE
Discuss: Feature branch workflow

### ISSUE THREAD

**Issue by mparke** [linode/manager#1110]
We should start treating master like production, and it may benefit us to adopt a feature branch workflow in this repo so we can iterate on larger features together while keeping master pristine.

Comment here with thoughts/ideas

**Comment by na3d** [comment]
Better to get into the practice sooner than later.

**Comment by abemassry** [comment]
I think we should have a staging branch and a master or production branch, merge to staging, test it out, merge to master, deploy.

**Comment by mparke** [comment]
@abemassry yup, that's essentially what I'm suggesting, but also having feature branches is useful. The version of staging you're talking about (that i've done in the past) has been referred to as release candidate.

so here's a general breakdown of how we could start splitting things up:

- `master`: pristine, all deployed commits tagged with a version and/or date
  - bug fixes can be merged directly into master and tagged
- `feature-{x}`: (staging) generic WIP feature branch, can have multiple contributors, if only 1 feature tested and ready to go, can be merged directly into master
- `rc-{version}`: (staging), Used when 1 or more feature branches / updates need to be combined into a larger release, merges feature branches into the rc branch. tested, then merged into master

TBD: tagging scheme, see https://github.com/linode/manager/issues/1114

**Comment by na3d** [comment]
We now have a release branch.
