### ISSUE TITLE
[API] PageSize does not work on getLinodes

### ISSUE THREAD

**Issue by kamilchodola** [linode/manager#11126]
As per documentation getLinodes endpoint is capable of handling 500 requests per page at maximum so I used it like this"
`const instances = await getLinodes({ page: 1, pageSize: 500 });`

Unfortunately it still keeps capping everything to 100. Is it handled properly in JS wrapper?

**Comment by bnussman** [comment]
`@linode/api-v4` should allow you to pass a page size using `page_size` (rather than `pageSize`)

https://github.com/linode/manager/blob/6ccccdbbd22003e6ec52062665b575d3f6e3f14a/packages/api-v4/src/types.ts#L31-L34

Let us know if this works for you! 😃

**Comment by kamilchodola** [comment]
Ahhh yeah it worked - Guess you need to adjust example on your Readme.md of https://github.com/linode/manager/tree/develop/packages/api-v4
