### ISSUE TITLE
Softer hover on individual notifications

### ISSUE THREAD

**Issue by eatonphil** [linode/manager#1118]
It feels a little too much that hovering on a notification has the effect of looking identical to a read notification. I find this confusing in this inbox setting. For instance, imagine gmail doing this when you hover over an unread email. Actually, gmail's only hover effect is to turn on the pointer / hand cursor. I'd be fine with us doing more than that but I don't think the hover should be identical to a read message.

(The top-most "unread"-looking notification is actually just my mouse hovering over it. The rest of the "unread"-looking notifications are actually unread.)

<img width="415" alt="screen shot 2017-01-30 at 2 59 33 pm" src="https://cloud.githubusercontent.com/assets/3925912/22439208/ba6e2ffe-e6fc-11e6-8a1e-c4b666af878c.png">

**Comment by mparke** [comment]
@eatonphil is this still needed?

**Comment by eatonphil** [comment]
Yes, I would still like it.
