### ISSUE TITLE
Implement account link in sidebar

### ISSUE THREAD

**Issue by eatonphil** [linode/manager#113]

**Comment by eatonphil** [comment]
![screen shot 2016-07-12 at 3 13 45 pm](https://cloud.githubusercontent.com/assets/3925912/16780121/3eb751a4-4843-11e6-8acb-8c2697bf1675.png)

**Comment by SirCmpwn** [comment]
Hmm, weren't we going to put this in the notification drawer on the top right?

**Comment by eatonphil** [comment]
No, not this. The navigation has always been on the left.

**Comment by eatonphil** [comment]
Oh sorry I forgot.

**Comment by eatonphil** [comment]
This is different from that right? There is profile and account

**Comment by eatonphil** [comment]
Profile is in the notification drawer, account is here.
