### ISSUE TITLE
Find a way to clarify when you're spending money

### ISSUE THREAD

**Issue by eatonphil** [linode/manager#114]

**Comment by SirCmpwn** [comment]
Should always be clear when pressing a button leads to spending money.

**Comment by eatonphil** [comment]
True, just maybe not this way.

**Comment by eatonphil** [comment]
Places where buttons lead to purchases so far:

1. Create a Linode: going to go with this is sufficiently obvious because the plan page has all the pricing.
2. Enable backups:
![screen shot 2016-06-17 at 12 20 32 pm](https://cloud.githubusercontent.com/assets/3925912/16157369/3c14b818-3486-11e6-8c26-c54873741e4e.png)
3. Resize: sufficiently obvious.
