### ISSUE TITLE
SSH/Text console text should both probably just be links

### ISSUE THREAD

**Issue by eatonphil** [linode/manager#115]
Otherwise we'd need the SSH button for both that launches native ssh sessions.

**Comment by SirCmpwn** [comment]
Need to be able to copy the SSH command. Lots of systems don't have ssh:// configured to work right.

**Comment by eatonphil** [comment]
You can still copy when there is a link

**Comment by SirCmpwn** [comment]
Yeah, but it's annoying as hell to paste it and then back up and delete ssh://

**Comment by eatonphil** [comment]
On a link you don't... The href has the ssh://, the text does not.

**Comment by SirCmpwn** [comment]
Oh, I see. A textbox that autohighlights when clicked would still be a better UX, though.

**Comment by eatonphil** [comment]
The reason is that Chris wanted both native links for both SSH and Lish so I needed to add another SSH button to the Text Console section. This was getting annoying. My last hope of avoiding just links (which is the current best option IMO) is to have a link appear in a popup when you click on the text area.

![screen shot 2016-06-10 at 2 56 40 pm](https://cloud.githubusercontent.com/assets/3925912/15975531/e024c472-2f1b-11e6-8d4a-0d2763be17f2.png)
![screen shot 2016-06-10 at 2 56 53 pm](https://cloud.githubusercontent.com/assets/3925912/15975532/e0261bb0-2f1b-11e6-9ecf-3221d9680e1b.png)
![screen shot 2016-06-10 at 2 57 05 pm](https://cloud.githubusercontent.com/assets/3925912/15975530/e023aca4-2f1b-11e6-80b5-cd4abc3b6340.png)

**Comment by SirCmpwn** [comment]
I like the third one best.

**Comment by eatonphil** [comment]
To be fair to myself, the last will look a lot better using even just Bootstrap popup and we can change the wording.

**Comment by SirCmpwn** [comment]
Well, honestly I like the original design of these buttons.

**Comment by eatonphil** [comment]
Original meaning current manager?

**Comment by SirCmpwn** [comment]
Like [this](https://cloud.githubusercontent.com/assets/3925912/15975531/e024c472-2f1b-11e6-8d4a-0d2763be17f2.png) or so.

**Comment by eatonphil** [comment]
Oh ok. At this point I'm just left wondering why so many buttons? Especially when two of the buttons are just supposed to be links. idk

**Comment by SirCmpwn** [comment]
Don't be a button hater!

**Comment by eatonphil** [comment]
Cool, then we'll go with that.

**Comment by SirCmpwn** [comment]
Though we could stand to align them a bit better.

**Comment by SirCmpwn** [comment]
And maybe drop the help icons, this is a feature that's easy to figure out through experimentation.

**Comment by eatonphil** [comment]
The help initially had only to do with what Lish and Glish are. There are links in the current manager to docs on both I think. This is still valid.

**Comment by eatonphil** [comment]
![screen shot 2016-06-10 at 3 21 59 pm](https://cloud.githubusercontent.com/assets/3925912/15976173/1ad16974-2f1f-11e6-8c73-393c53e4b725.png)

**Comment by SirCmpwn** [comment]
Alright. I would exercise restraint in general with overuse of help buttons to avoid using them as a crutch for features that are not intuitive, or overloading the user with information. +1 to mockup

**Comment by eatonphil** [comment]
On the other hand, someone recently pointed out to me how Cloudflare uses these help icons all over the place and it works well. Apparently they use them even more copiously than we do. So I'm not too worried about that.

**Comment by SirCmpwn** [comment]
Sounds good, no worries.
