### ISSUE TITLE
Mockup support pages

### ISSUE THREAD

**Issue by eatonphil** [linode/manager#1157]
Some initial ideas and some considerations:

* [ ] Open / closed columns lined up?
* [ ] Include who opened / updated ticket on ticket list here?
* [ ] Label row once or word of context without label row?
* [ ] PrimaryTable (larger height) vs SecondaryTable (smaller height, all fonts same size)
* [ ] Include number / whether or not there are new messages?

![screen shot 2017-02-07 at 9 35 35 am](https://cloud.githubusercontent.com/assets/3925912/22695600/49e1f3ec-ed19-11e6-8e6f-3966c8a9cea3.png)
![screen shot 2017-02-07 at 9 36 22 am](https://cloud.githubusercontent.com/assets/3925912/22695599/49dff0ce-ed19-11e6-814c-0ba0b9a16178.png)
![screen shot 2017-02-07 at 9 35 50 am](https://cloud.githubusercontent.com/assets/3925912/22695604/49f4e010-ed19-11e6-9d49-a78367685fdf.png)
![screen shot 2017-02-07 at 9 36 01 am](https://cloud.githubusercontent.com/assets/3925912/22695603/49e85b2e-ed19-11e6-8063-b817dadf9a31.png)
![screen shot 2017-02-07 at 9 36 15 am](https://cloud.githubusercontent.com/assets/3925912/22695602/49e719ee-ed19-11e6-9c8d-a670cc830cc6.png)
![screen shot 2017-02-07 at 9 36 31 am](https://cloud.githubusercontent.com/assets/3925912/22695601/49e3942c-ed19-11e6-990b-5a105512ab0d.png)

**Comment by abemassry** [comment]
- Include who opened / updated ticket on ticket list here?
  - This is a good idea
- Include number / whether or not there are new messages?
  - Yes, downplay the alertness

**Comment by mparke** [comment]
- are the columns sortable?
- should we just have filter options instead of two separate tables? 
    - for example, a dropdown `all`, `open`, `closed`
- are the ticket numbers links?
- can we make the font consistent with existing? ( falls back to helvetica neue )
- red appears a bit alarming for this use case
    - consider yellow
    - consider badge + count

**Comment by mparke** [comment]
ignore the close/open

**Comment by eatonphil** [comment]
@mparke, columns sortable? Hmm we haven't really approached that anywhere yet. I'd expect it to have the same sort of behavior as other PrimaryTables do in that regard.

Filter options? Maybe, but I like how Google has the split inbox for read / unread and I think it would be convenient here to locate the important ones.

Ticket numbers are probably not links, they are used only for reference in phone calls and things. (Otherwise, and perhaps still, I'd like to drop them from this list).

Yellow may be a good idea, but yellow is often difficult as a background color (hard to read foreground). Am open to yellows and / or other reds. The count is a good idea too, or just an exclamation point. But a count is more consistent.

**Comment by eatonphil** [comment]
Closing this out for this iteration.
