### ISSUE TITLE
Mockup banners

### ISSUE THREAD

**Issue by eatonphil** [linode/manager#1160]
* [ ] App-wide
* [ ] Object-specific (a particular Linode)
* [ ] Page needs to be refreshed to receive new data

**Comment by mparke** [comment]
First iteration of app-wide alerts

![alerts - banner warning ticket](https://cloud.githubusercontent.com/assets/709951/22906472/96532a54-f212-11e6-8664-1eb6739edfb0.png)

![alerts - banner warning migration ready](https://cloud.githubusercontent.com/assets/709951/22906480/9c095752-f212-11e6-84e0-9e8b41cd977d.png)

![alerts - banner warning migration ready detailed](https://cloud.githubusercontent.com/assets/709951/22906503/c3b25d08-f212-11e6-9af2-5456c52501b8.png)

![alerts - banner warning migration scheduled](https://cloud.githubusercontent.com/assets/709951/22906495/b5b384fc-f212-11e6-868e-6c760e576744.png)

![alerts - banner warning migration scheduled detailed](https://cloud.githubusercontent.com/assets/709951/22906499/bc880f32-f212-11e6-8574-727dcf7cf9a5.png)

![alerts - banner danger ticket outstanding balance](https://cloud.githubusercontent.com/assets/709951/22906522/d57e1e1e-f212-11e6-99f9-3ca6371a57f3.png)

![alerts - banner danger ticket](https://cloud.githubusercontent.com/assets/709951/22906586/211b8c62-f213-11e6-8cd0-4dde34382f4c.png)

**Comment by eatonphil** [comment]
We should work on the bg/fg contrast (the orange ones most of all).

Could you try left-aligning the messages? I feel like it will be a little less obnoxious.

I like the use of bold to indicate objects. I have been trying to work that into support tickets too.

I also prefer the use of links here rather than buttons.

**Comment by mparke** [comment]
re: contrast, I was trying to keep contrast high for these, but can play with the red/orange a bit. I've been trying some varied hues/tint/shade 

re: left aligning, I would try that if we had a version that wasn't the whole width. cool if I make a note and backlog for now?

re: links v. buttons, only trying to keep the distinction between actions and links to other pages. if these are actions you can take directly from the alert ( was trying to keep it close to existing ), then we should probably stick with buttons no?

**Comment by mparke** [comment]
re: buttons, I do admit they look a little weird here, with the same sizing as rest of app.

**Comment by mparke** [comment]
Updates:

- more red + less orange + white text
- slightly less bold yellow
- smaller buttons

![alerts - banner danger ticket](https://cloud.githubusercontent.com/assets/709951/22987294/454b8e60-f37c-11e6-989c-62387b33151e.png)
![alerts - banner danger ticket outstanding balance](https://cloud.githubusercontent.com/assets/709951/22987296/45508244-f37c-11e6-8ad5-617c19c6e8f9.png)

![alerts - banner warning host maintenance](https://cloud.githubusercontent.com/assets/709951/22987293/454ad6f0-f37c-11e6-8ed3-feae2a728ca5.png)
![alerts - banner warning ticket](https://cloud.githubusercontent.com/assets/709951/22987299/45573b84-f37c-11e6-87df-6bc3d1522961.png)

![alerts - banner warning migration ready](https://cloud.githubusercontent.com/assets/709951/22987295/454df312-f37c-11e6-9d1b-1395b04a6dfd.png)
![alerts - banner warning migration ready detailed](https://cloud.githubusercontent.com/assets/709951/22987292/454ab4cc-f37c-11e6-8606-a87ddff8d642.png)

![alerts - banner warning migration scheduled](https://cloud.githubusercontent.com/assets/709951/22987298/4556ff34-f37c-11e6-8cf1-7cbff3032084.png)
![alerts - banner warning migration scheduled detailed](https://cloud.githubusercontent.com/assets/709951/22987297/45556f2a-f37c-11e6-8d45-f6e04e77e9af.png)

**Comment by mparke** [comment]
Example on object page.

![alerts - banner warning ticket linode page](https://cloud.githubusercontent.com/assets/709951/22995944/e005b066-f39a-11e6-8b95-3de4039a1bda.png)

**Comment by mparke** [comment]
Note: banners may become problematic if we have more than 1 to show:

- do you show multiple stacked overlaying content?
- do you show multiple stacked pushing down content?
- do you show one at a time and remove them after a timeout?

**Comment by mparke** [comment]
Alternative Notifications/Alerts:

![alerts - notification danger ticket](https://cloud.githubusercontent.com/assets/709951/22999766/28e03346-f3ab-11e6-8494-3a53d8809246.png)

![alerts - notification warning ticket](https://cloud.githubusercontent.com/assets/709951/22999765/28dc7b7a-f3ab-11e6-9c51-881f8c35b8e8.png)

**Comment by mparke** [comment]
And for something like a pending migration, we could place the action on the object page, and link to it, like so:

![alerts - notification warning pending migration link](https://cloud.githubusercontent.com/assets/709951/22999767/28e05948-f3ab-11e6-9f21-0ffe3c88029b.png)

Action as part of status/actions menu:

![alerts - notification warning pending migration linode](https://cloud.githubusercontent.com/assets/709951/22999785/480821a2-f3ab-11e6-981f-871b96a97e08.png)

**Comment by mparke** [comment]
closing for now, can be re-opened with additional comments.
