### ISSUE TITLE
STATS and GRAPHS placeholder

### ISSUE THREAD

**Issue by bralski1** [linode/manager#1166]

**Comment by mparke** [comment]
broken down into known graphs:

Linodes:
https://github.com/linode/manager/issues/1397
https://github.com/linode/manager/issues/1398
https://github.com/linode/manager/issues/1399
https://github.com/linode/manager/issues/1400

NodeBalancers
https://github.com/linode/manager/issues/1402
https://github.com/linode/manager/issues/1403
