### ISSUE TITLE
Networking page update v5

### ISSUE THREAD

**Issue by eatonphil** [linode/manager#119]
* [x] IPv6 can have RDNS too
* [x] "delete" IP address section should be "remove"
* [x] IPv6 ips cannot be deleted
* [x] Add "Add an IP" button to both private and public IP sections
  * note: if user reached limit of allowed public ips then prompt them to explain why they need more
* [x] Add "Global pool" section or something like that for groups of (ipv6) ips that don't really belong with one Linode
  * question: are pools shareable across datacenters?
* [x] Transfer IP section should you checkboxes not radio buttons
* [ ] Transfer IP checkboxes should maybe be in the right and left of the labels as opposed to the current left and left
  * note: look at current design
* [x] RDNS is a higher priority section (should not be at the bottom)
* [x] RDNS should have address selection come first, not hostname lookup.
* [x] Add "reset host entry" button to selected addresses in RDNS section

**Comment by eatonphil** [comment]
Skipping the unchecked task for now.

This overhauls the advanced settings page and adds a subnav. I'm not set with the styles for the subnav, but its a start I'm happy enough with for now.

Networking summary page:
![screen shot 2016-06-13 at 1 44 02 pm](https://cloud.githubusercontent.com/assets/3925912/16017339/5e8a6a62-316d-11e6-8393-1328a630bb5c.png)

Request additional IP modal pops up only if you have already added as many as currently allocated:
![screen shot 2016-06-13 at 1 44 11 pm](https://cloud.githubusercontent.com/assets/3925912/16017337/5e79e804-316d-11e6-955a-475db4ee54a6.png)

IP removal page:
![screen shot 2016-06-13 at 1 44 32 pm](https://cloud.githubusercontent.com/assets/3925912/16017335/5e7271aa-316d-11e6-88d2-cf756cbae040.png)

IP removal confirmation modal:
![screen shot 2016-06-13 at 1 44 43 pm](https://cloud.githubusercontent.com/assets/3925912/16017340/5e8e9c54-316d-11e6-86a2-6ada92ada1f3.png)

IP transfer page:
![screen shot 2016-06-13 at 1 44 54 pm](https://cloud.githubusercontent.com/assets/3925912/16017341/5e953e06-316d-11e6-892c-f6b00532120b.png)

Reverse DNS page:
![screen shot 2016-06-13 at 1 45 03 pm](https://cloud.githubusercontent.com/assets/3925912/16017338/5e7a276a-316d-11e6-91d2-9e09741fa04e.png)

IP sharing page:
![screen shot 2016-06-13 at 1 45 13 pm](https://cloud.githubusercontent.com/assets/3925912/16017336/5e76910e-316d-11e6-90bc-9e5f5b8b8d40.png)

**Comment by SirCmpwn** [comment]
:+1:
