### ISSUE TITLE
moment-timezone intermittent error

### ISSUE THREAD

**Issue by abemassry** [linode/manager#1211]
not sure if this is a problem, @mparke suggested I put it here.
![image](https://cloud.githubusercontent.com/assets/1616275/22759101/3c520e7c-ee1f-11e6-9ba5-2c0ceb587b9c.png)

**Comment by eatonphil** [comment]
You need to reinstall node packages and restart your server.

**Comment by bralski1** [comment]
Abe - please confirm or deny.  Thx.

**Comment by abemassry** [comment]
Deny. Can't reproduce.
