### ISSUE TITLE
Show error message on API request failure

### ISSUE THREAD

**Issue by jfrederickson** [linode/manager#1234]
If the API goes down while you're browsing through the Manager, and you browse to the Linodes page, you'll see this:

![screen shot 2017-02-14 at 11 51 42 am](https://cloud.githubusercontent.com/assets/1923178/22944225/fbcfc26a-f2bd-11e6-97ff-ca7f360e34b0.png)

We should probably show an error message to avoid scaring people, since this makes it look like all their Linodes disappeared.

**Comment by eatonphil** [comment]
Thanks! I think this is a bug actually. We've got some beautiful error pages, but they definitely don't appear to be showing up correctly. Will tag and rename so we can handle it appropriately.
