### ISSUE TITLE
Page load progress bar sometimes goes backwards

### ISSUE THREAD

**Issue by jfrederickson** [linode/manager#1238]
If you rapidly click between pages (open a new one before the progress indicator has completely faded out), you'll see the progress indicator start at the end and move backwards. I think it would probably make more sense to force the current bar to fade out immediately and start the animation from the beginning.

**Comment by eatonphil** [comment]
A known bug, but I wonder if you've happened to pick up on what behavior causes this? If not, no worries -- we'll get it figured out.

**Comment by jfrederickson** [comment]
Gotcha - I didn't see another issue open for this so I decided to open this one.

As far as exactly what causes it, I'm not sure, I just know that it only happens if I click another link before the first progress bar has completely faded.
