### ISSUE TITLE
General updates v5

### ISSUE THREAD

**Issue by eatonphil** [linode/manager#124]
* [x] Notifications modal text is way too small
* [x] Think about boot profile option in the power dropdown on the Linode details page
* [x] All Linode details rows should not extend outside of typical padded area
* [x] Drop all notifications checkmarks
* [x] Add account link to sidebar

**Comment by eatonphil** [comment]
Just going to show screenshot for notifications changes:

![screen shot 2016-06-13 at 2 34 35 pm](https://cloud.githubusercontent.com/assets/3925912/16018797/0b99e8bc-3174-11e6-8d2d-66adadcd148a.png)

Modifying row margins can be seen in #119.

I'm letting the boot profile go for now and spinning out another task to try mocking up a power dropdown with profile options or something similar.

**Comment by na3d** [comment]
Maybe a little smaller text for the word Notifications, it doesn't need to be that big of a focus item.  It is only there as a reference to people if and when they need it, which will be almost never, beyond the first time seeing it.

**Comment by eatonphil** [comment]
It's keeping in line with the current usage of header fonts and whatnot. So it's currently "h2" size. Though I guess it could be "h3" size.

**Comment by na3d** [comment]
For the notifications themselves, try out having the padding the same all around, or a little bit more on bottom, instead of on top.  Traditionally groups of text have more white space below.

**Comment by eatonphil** [comment]
The padding is currently the same all around. Personally, I'm not a fan of asymmetric padding.
