### ISSUE TITLE
DNS: Add slave zone wording/placeholder update

### ISSUE THREAD

**Issue by mparke** [linode/manager#1248]
This is an item to review the slave zone field label, help text, and placeholder.

![screen shot 2017-02-16 at 4 53 09 pm](https://cloud.githubusercontent.com/assets/709951/23043167/6c9c5538-f469-11e6-918c-d78a7f487a6c.png)

- `Masters` - masters what?
- placeholder value looks like a subnet mask?
- if label updated, help text likely simplified

**Comment by eatonphil** [comment]
> Masters - masters what?

+1, Master Zones:

> placeholder value looks like a subnet mask?

+1, even more helpful would be to select from existing master zones or freetext add your own if it's not there (longer term solution)

> if label updated, help text likely simplified

Best case is to have a DelimitedInput component that does this automatically. Something similar is already also needed for the search bar.
