### ISSUE TITLE
Lish Settings: Update label and add placeholder text

### ISSUE THREAD

**Issue by mparke** [linode/manager#1249]
![screen shot 2017-02-16 at 4 44 44 pm](https://cloud.githubusercontent.com/assets/709951/23043280/c13e198c-f469-11e6-939d-ff484b12214e.png)

- label can probably be `SSH keys`
- placeholder could likely do something that's pretty common, denoting example ssh key starts
- with updated label, help text may be irrelevant

**Comment by eatonphil** [comment]
> label can probably be SSH keys

+1

> placeholder could likely do something that's pretty common, denoting example ssh key starts

+1

> with updated label, help text may be irrelevant

Changing would be good, but I think helpful text here is needed.
