### ISSUE TITLE
Create happy error pages

### ISSUE THREAD

**Issue by eatonphil** [linode/manager#125]
Static (can we generate these from React?):
* [ ] 502

In-app:
* [ ] 404

**Comment by SirCmpwn** [comment]
>can we generate these from React?

We might be able, but we shouldn't. This should be static pages served up by nginx and should be as lightweight as possible (to ease the load on an already broken system).

**Comment by SirCmpwn** [comment]
Aside from the 404 page, can be whatever. We already have one, actually.

**Comment by eatonphil** [comment]
I thought generating them from React would be easier so we could reuse the existing components (for headers, styles, assets, etc.). But I guess it could be overkill.

**Comment by SirCmpwn** [comment]
If everything's borken we don't need the headers/styles/assets anyway. We won't have a nav/headers (cause the other pages are probably borken too and we should reduce load while borken) and without that and without any actual content other than a message we don't really need our stylesheets.

**Comment by eatonphil** [comment]
Not completely following, but I guess we can still have "happy" and reduced load. Github's [502](https://github.com/502) qualifies I guess.

**Comment by SirCmpwn** [comment]
Right. That 502 page doesn't need the proper GH stylesheet cause it doesn't reuse any of the GH UI elements. Also, if you look at the source, it doesn't make any extra requests - the styles and image are inlined.
