### ISSUE TITLE
Make select all checkbox a 3 state select all, the way gmail does it

### ISSUE THREAD

**Issue by abemassry** [linode/manager#1255]
States should be:
Some selected. (gmail uses a minus sign)
If some are selected then the behavior of the checkbox is to select none, or clear the selection.

None selected. (gmail is empty)
If none are selected the behavior is to select all

All selected. (gmail is checkmark)
If all are selected the behavior is to clear the selection.

**Comment by eatonphil** [comment]
This has been done!
