### ISSUE TITLE
Refactor API abstractor

### ISSUE THREAD

**Issue by na3d** [linode/manager#1261]

**Comment by mparke** [comment]
@na3d mind providing a short description of the pain points?

**Comment by na3d** [comment]
The abstractor was built pretty early on, and specs have changed since then.  We need to be able to handle all API endpoints in reasonable ways.  We have a couple endpoints, such as linode/ips and account/profile, that need to be handled appropriately.

**Comment by mparke** [comment]
note: because of how we build objects based on endpoint name and response format, we have a case where we build an `undefined` key. This needs to be resolved as part of this issue.

see `this.props.profile.profile.undefined;`

**Comment by na3d** [comment]
- [ ] src/profile/layouts/AuthenticationPage.js
- [ ] src/profile/layouts/DisplayPage.js
- [ ] src/profile/layouts/IndexPage.js
- [ ] src/profile/layouts/ReferralsPage.js
- [ ] src/settings/layouts/IndexPage.js
- [ ] src/users/user/layouts/PermissionsPage.js

**Comment by eatonphil** [comment]
This has been fixed with the addition of the singular vs. plural configs.
