### ISSUE TITLE
Investigate recovering and logging after errors

### ISSUE THREAD

**Issue by eatonphil** [linode/manager#1280]
Ideally, navigating to a new page would recover from an error. We may also benefit from logging errors.

**Comment by mparke** [comment]
related: https://github.com/linode/manager/issues/645

**Comment by mparke** [comment]
broken down into https://github.com/linode/manager/issues/645 and https://github.com/linode/manager/issues/1948

**Comment by mparke** [comment]
nvm, this is about recovering.
