### ISSUE TITLE
CNAME hostname placeholder should not be a FQDN

### ISSUE THREAD

**Issue by eatonphil** [linode/manager#1290]

**Comment by na3d** [comment]
Fixed: Closing

**Comment by eatonphil** [comment]
I don't think this is done:
![screen shot 2017-06-02 at 9 46 04 am](https://cloud.githubusercontent.com/assets/3925912/26728468/540f9310-4778-11e7-8d76-fe7769004218.png)

**Comment by eatonphil** [comment]
This is still an issue.
