### ISSUE TITLE
Fill out NodeBalancer list view

### ISSUE THREAD

**Issue by eatonphil** [linode/manager#1319]
Review list items that may be missing from the node balancer list:
https://projects.invisionapp.com/share/8FALUJ0EY#/screens/220575701

**Comment by mparke** [comment]
moved back into ready, waiting on ipv6 addition to be deployed

**Comment by eatonphil** [comment]
IPv6 is in place just not supported by the alpha. Abe is taking care of the node status in his upcoming PR. The rest are not available at this time. Closing for now.
