### ISSUE TITLE
Find good range slider plugin

### ISSUE THREAD

**Issue by eatonphil** [linode/manager#132]

**Comment by SirCmpwn** [comment]
I'm not sure we need a plugin. Such a component would be pretty straightforward to implement.

**Comment by eatonphil** [comment]
Ok! I just wanted to create an opportunity for prettier sliders than the ones I mocked up.

**Comment by SirCmpwn** [comment]
I think your sliders are quite pretty.

**Comment by eatonphil** [comment]
Aw shucks. Well there are still some annoying parts of a slider (labels on the sides and in other places) that make this about as complex as a dropdown. And we decided to punt on that one. I'd just expect at some point we'd probably rather punt here too. But bottom of the backlog for now and maybe it will be a non-issue.

**Comment by Qtrain** [comment]
Thought I'd throw my two cents in for Slider Revolution - it's pretty good. https://revolution.themepunch.com/jquery/

**Comment by SirCmpwn** [comment]
Thanks for the suggestion, but jQuery isn't involved in our codebase and has little chance of becoming involved in it.

**Comment by SirCmpwn** [comment]
Two more problems with that: we are talking about sliders where you pick a value, not carousels. And we don't use any proprietary dependencies.

**Comment by SirCmpwn** [comment]
To clarify, this issue is about `<input type="range">`.

**Comment by eatonphil** [comment]
Ah, yes it's called a range slider. [Here](http://rangeslider.js.org/) is an example library.

**Comment by eatonphil** [comment]
https://github.com/react-component/slider ++
