### ISSUE TITLE
Banner alert - linode - host maintenance

### ISSUE THREAD

**Issue by na3d** [linode/manager#1324]
Classic Screen Grabs: https://github.com/linode/manager/issues/1044

We want to keep the wording the same as classic, and just have standard banners. 
 This is what we had planned before:
https://github.com/linode/manager/issues/1160

We should, stating the obvious, be able to have a re-usable component for these banners, where based on a value of the type of banner it will dictate what color it will be.

**Comment by howdiz** [comment]
@na3d Can you please add a description to this and other similar tickets? I'd like to understand why different banner alerts require front end work? I'd rather not have to inventory every type of ticket on the front end if possible.

**Comment by na3d** [comment]
Message:
![XenHostMain.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/574f1638af85550e005e0ae3/125516c66e82c728ace21e0d46d091940b8d90bda2e8b64de611b2843b492d762a10e17132d0b47cb9132c030e0918fe415e0c12fdf98d28a4e73b76df4e17ff933c0120996048e6edc00db513bb29814e80b7be8b4fc6e03d23e6888c5d73.png)

Color:
#FFDE4C

**Comment by asauber** [comment]
We don't get this information from the /notifications endpoint. Does it come back somewhere else?
