### ISSUE TITLE
consider using factory functions in unit test mock data

### ISSUE THREAD

**Issue by mparke** [linode/manager#1345]
I see we have some single reference exports in test data shared across tests. This could be more flexible by making these into factories, e.g.:

```
function generateObj(options) {
  return {
  };
}
```

so that they can be clean per-test via explicit call or beforeEach:

```
it('something', function() {
  const obj = generateObj();
  // ...
}
```

```
beforeEach(function() {
  // not sure if mocha shares an object like jasmine, but on `this` or in closure
  this.obj = generateObj();
});
```

**Comment by eatonphil** [comment]
I started doing this in the test data. See the set of `createTestFOO` functions in `test/data/linodes.js` such as `createTestLinode`.
