### ISSUE TITLE
My Applications > Create OAuth Application empty/broken

### ISSUE THREAD

**Issue by mparke** [linode/manager#1364]
![screen shot 2017-03-08 at 3 15 31 pm](https://cloud.githubusercontent.com/assets/709951/23722107/1bb3b61c-0412-11e7-963d-2f2234745a50.png)

**Comment by eatonphil** [comment]
This was actually fixed in #1361 [here](https://github.com/linode/manager/pull/1361/commits/b19a1b882c13091c09f35ef1e2d1cd571b0eeefc)
