### ISSUE TITLE
Mockup create Linode from Clone

### ISSUE THREAD

**Issue by eatonphil** [linode/manager#1425]

**Comment by mparke** [comment]
@eatonphil did you have anything for this previously?

**Comment by eatonphil** [comment]
Nope. Requirements are: it's a list of Linodes you can pick from.

**Comment by mparke** [comment]
round one: https://projects.invisionapp.com/boards/WF36Y3WP4SVH8/

**Comment by mparke** [comment]
working on a round 2 that retains form sections and shows potential clone control from a linode list item

**Comment by mparke** [comment]
@eatonphil round 2 which includes a simple list and the full form is up on the invision board. 

making an example of clone from dropdown next

**Comment by mparke** [comment]
another round of updates added, includes clone in list item dropdown with a modal to clone the selected Linode. see annotations

**Comment by mparke** [comment]
@na3d @abemassry take a look when you have a minute.

**Comment by eatonphil** [comment]
+1 to the clone modal and breaking it out of the create flow.

**Comment by mparke** [comment]
closing for now, can be reopened with comments as needed.
