### ISSUE TITLE
Reboot button overlaps sidebar when scrolling horizontally

### ISSUE THREAD

**Issue by Dorthu** [linode/manager#1430]
<img width="287" alt="screen shot 2017-03-21 at 11 41 54 am" src="https://cloud.githubusercontent.com/assets/7172953/24156133/1b6d6346-0e2c-11e7-9c34-05017d5e6a7a.png">

**Comment by na3d** [comment]
This should be taken care of by [1409](https://github.com/linode/manager/issues/1409)
