### ISSUE TITLE
Add a DNS Zone screen misplaces email address error popup

### ISSUE THREAD

**Issue by Dorthu** [linode/manager#1442]
I was testing adding a DNS Zone, and put garbage in the email address field.  The error popup showed for the wrong input.

![screen shot 2017-03-23 at 7 25 52 am](https://cloud.githubusercontent.com/assets/7172953/24245713/59a37a00-0f9a-11e7-9cc3-1b8506b576e4.png)

**Comment by eatonphil** [comment]
Huh, that's a funny one. What browser are you running?

**Comment by na3d** [comment]
He is running Vivaldi, Chrome doesn't have the same problem.

@Dorthu, do you think it is safe to say this is a problem with Vivaldi instead, since it is based on the same technology as Chrome?

**Comment by na3d** [comment]
I am closing for now.  If someone can justify re-opening it, feel welcome.
