### ISSUE TITLE
Create NodeBalancer sends request without Datacenter if Datacenter wasn't clicked

### ISSUE THREAD

**Issue by Dorthu** [linode/manager#1443]
I would expect this to either not send the request, or to choose a default.  Instead, it sent the request like this:

```json
{
    "label": "didnt-click-datacenter",
    "datacenter": ""
}
```

response was `{"errors": [{"reason": "datacenter is not valid", "field": "datacenter"}]}`

No error was displayed on the page after this happened.

![screen shot 2017-03-23 at 7 28 21 am](https://cloud.githubusercontent.com/assets/7172953/24245766/9e17a8e6-0f9a-11e7-8ca9-502787a993fd.png)

**Comment by eatonphil** [comment]
I think it is actually our policy to allow things to be sent. However, the error is not shown here and that is a bug. Furthermore, we often just set a default for these card inputs to avoid this problem.
