### ISSUE TITLE
Format all x-axis values (not just ticks)

### ISSUE THREAD

**Issue by eatonphil** [linode/manager#1469]
See https://github.com/chartjs/Chart.js/issues/4085

**Comment by na3d** [comment]
Just to skip a few clicks:

    callbacks: {
      label: function(tooltipItem, data) {
        var label = data.datasets[tooltipItem.datasetIndex].label || '';

        if (label) {
            label += ': ';
        }
        label += tooltipItem.yLabel;
        return label;
      },
    },
