### ISSUE TITLE
"Your Linode must be Powered Off" message while provisioning empty Linode

### ISSUE THREAD

**Issue by Dorthu** [linode/manager#1506]
I created an empty Linode, then immediately navigated to the Settings > Advanced tab to manage disks, and found this message: 

![screen shot 2017-04-05 at 8 28 43 am](https://cloud.githubusercontent.com/assets/7172953/24705467/16f79dfe-19da-11e7-98a7-25b2eb035b96.png)

I don't expect provisioning a blank Linode to cause a boot job (since it can't boot), so I expect this message is in error.

**Comment by mparke** [comment]
@Dorthu Thanks! Will update wording in this case.
