### ISSUE TITLE
Discuss feedback

### ISSUE THREAD

**Issue by eatonphil** [linode/manager#1510]
Should there be an explicit feedback form? Are tickets insufficient? Are requests for feedback better delegated to async options like email?

**Comment by na3d** [comment]
Want to discuss this tomorrow after standup?

**Comment by abemassry** [comment]
Here is the possible implementation we've decided on:
A feedback link (possibly in the footer) brings up a feedback form (possibly a modal) that looks like a feedback form but is wired to the backend of the ticket system and adds [Feedback] to the beginning of the title and possibly some information written in the ticket body that says Feedback: also possibly the browser information and version number of the react app they are using.

The advantage of doing it this way is we can respond to the feedback and it opens up a channel of communication.

**Comment by eatonphil** [comment]
Discussion was completed a while ago. Implementation in progress.
