### ISSUE TITLE
Add tracking calls for analytics

### ISSUE THREAD

**Issue by na3d** [linode/manager#1522]
add ga `analytics.track(` calls for #1521

**Comment by mparke** [comment]
While investigating options into implementation for this, consider a couple things:

- do synthetic events in react bubble up to layouts and/or app root? if so, can we catch and filter these for generic components? The tracking of form submissions is ideally uniform.

- if the above is not possible / cannot be implemented easily, investigate a flexible way to dispatch custom events from shared components, to be handled at the app level for tracking ( as to keep tracking well decoupled from component or view implementations ). Event reference: https://developer.mozilla.org/en-US/docs/Web/API/Event/Event
