### ISSUE TITLE
Implement user header section

### ISSUE THREAD

**Issue by eatonphil** [linode/manager#158]
Remove logout and replace with gravatar. This can be done using the md5 hash of the user's email. Also create a dummy notification circle mirroring the following screenshot:
![screen shot 2016-06-17 at 1 43 45 pm](https://cloud.githubusercontent.com/assets/3925912/16159570/891d97b4-3491-11e6-82a0-5033c738050b.png)

**Comment by abemassry** [comment]
#250 is related
