### ISSUE TITLE
Edit NodeBalancer config appears broken

### ISSUE THREAD

**Issue by mparke** [linode/manager#1613]
![screen shot 2017-04-19 at 2 17 13 pm](https://cloud.githubusercontent.com/assets/709951/25195233/f5528542-250a-11e7-9c4e-03b66fffaf54.png)

**Comment by eatonphil** [comment]
I think this may be all FormGroups after the bootstrap change.

**Comment by eatonphil** [comment]
Closed by https://github.com/linode/manager/pull/1691
