### ISSUE TITLE
List blank slates needed

### ISSUE THREAD

**Issue by mparke** [linode/manager#1622]
List where we could implement blank slate / intro states

**Comment by eatonphil** [comment]
* NodeBalancers
* Domains
* Linodes

Less important:
* Users
* Tokens
* Apps

**Comment by eatonphil** [comment]
Some examples:

* https://s3-us-west-2.amazonaws.com/useronboard/shopify/slide-034.jpg
* https://lh6.googleusercontent.com/9q0MMmqKnFDpQclXe82cKBayaECgZN9-SlTkBGOas6-UiN3Reh7xfb4MWbzvHp-ElM8B_28E3DN0SvPD8vENFNhPmY5K8Ro5ZcLZ4DWta8f1THE5XxBd2lzbI6yEVzQYMt6Kmn04
* https://s3-us-west-2.amazonaws.com/useronboard/basecamp/slide-031.jpg

**Comment by mparke** [comment]
Nodebalancers examples https://invis.io/8FALUJ0EY
