### ISSUE TITLE
OAuth Clients show broken image if no image is set (Personal Access Tokens too)

### ISSUE THREAD

**Issue by Dorthu** [linode/manager#1640]
OAuth Clients who I have not yet assigned a thumbnail for show a broken image.  Personal Access Tokens, which never had a thumbnail, also show a broken image.

![screen shot 2017-04-25 at 2 43 19 pm](https://cloud.githubusercontent.com/assets/7172953/25402217/0d8906a8-29c6-11e7-944b-fdb81dd3331e.png)

**Comment by eatonphil** [comment]
The OAuth Clients being broken images if not set is intentional fwiw to encourage people to set it. But PATs should not have any image -- that is a bug.

**Comment by eatonphil** [comment]
The PATs issue was closed in https://github.com/linode/manager/pull/1691

**Comment by mparke** [comment]
Re-opening for more broken images in Profile > Integrations

**Comment by mparke** [comment]
Be sure to test these by uploading an image.

**Comment by eatonphil** [comment]
Dup of #1972
