### ISSUE TITLE
Fix method jump links

### ISSUE THREAD

**Issue by mparke** [linode/manager#1670]
Method jump links (GO TO ...) do not currently work / are not wired up. Fix this or implement something else.

**Comment by mparke** [comment]
If not an easy solution, kill JUMP TO

**Comment by mparke** [comment]
See:

https://github.com/ReactTraining/react-router/issues/394#issuecomment-220221604

**Comment by eatonphil** [comment]
That's unfortunate... what about:

```
window.scrollTo(0, document.getElementById(h).offsetTop);  
```
