### ISSUE TITLE
Webpack 2: tree shaking

### ISSUE THREAD

**Issue by mparke** [linode/manager#1675]
https://webpack.js.org/guides/tree-shaking/

**Comment by stvnjacobs** [comment]
This _should_ be all that it takes to get tree shaking working:

```diff
12:43 $ git diff develop .babelrc
diff --git a/.babelrc b/.babelrc
index 0d44dcc1..adfed0ee 100644
--- a/.babelrc
+++ b/.babelrc
@@ -1,5 +1,11 @@
 {
-  "presets": ["stage-0", "react", "es2015"],
+  "presets": [
+    "stage-0",
+    "react",
+    ["es2015", {
+      "modules": false
+    }]
+  ],
   "compact": true,
   "plugins": [
     "transform-runtime",
```

This worked when I was testing earlier this week.  Currently, though, it fails a few tests.

`test/fetch.spec.js` @ `should default to cors mode and headers for token` 
`test/fetch.spec.js` @ `should fetch the correct path`
`test/fetch.spec.js` @ `should include data`
`test/session.spec.js` @ `redirects to login when the oauth token is null`
`test/session.spec.js` @ `expires and checksLogin on expireAndReAuth`
