### ISSUE TITLE
Backups Enabled event shows strangely

### ISSUE THREAD

**Issue by Dorthu** [linode/manager#1687]
This is in the events dropdown.  I was initially unsure what this meant, but it looks like it's a backups_enable event.

![screen shot 2017-05-02 at 3 08 19 pm](https://cloud.githubusercontent.com/assets/7172953/25634633/4d72020a-2f49-11e7-8520-fb545ea076cc.png)

json looks like this:

```json
{
  "user_id": 365497,
  "action": "backups_enable",
  "rate": null,
  "created": "2017-05-01T00:36:08",
  "status": "notification",
  "username": "wsmith",
  "percent_complete": null,
  "time_remaining": null,
  "seen": true,
  "id": 4502,
  "read": true,
  "entity": {
    "url": "/v4/linode/instances/2020142",
    "id": 2020142,
    "label": "python-test",
    "type": "linode"
  }
}
```

**Comment by eatonphil** [comment]
Thank you! We've got this one down already in https://github.com/linode/manager/issues/1607.
