### ISSUE TITLE
Labels and content don't vertically align

### ISSUE THREAD

**Issue by na3d** [linode/manager#1711]
This exists on the Linode edit config page, Nodebalancer settings page, and elsewhere.

**Comment by na3d** [comment]
Purely a bonus item.  If it is a quick fix, awesome!  Otherwise, not big enough of an issue to worry about.

**Comment by eatonphil** [comment]
I have fixed this in some branch. Not sure if it got merged yet.

**Comment by na3d** [comment]
Ok, if we see it get fixed in master, we can close this.  Noticed it in our current master.
