### ISSUE TITLE
Add a Disk - button says "Saving" when modal appears

### ISSUE THREAD

**Issue by Dorthu** [linode/manager#1714]
This is the display when clicking  "Add a Disk," before doing anything else

![screen shot 2017-05-08 at 11 37 38 am](https://cloud.githubusercontent.com/assets/7172953/25812064/26b75432-33e3-11e7-86de-093728433ba9.png)

**Comment by eatonphil** [comment]
Thanks! Should be dealt with in https://github.com/linode/manager/pull/1698

**Comment by eatonphil** [comment]
Closed in #1698
