### ISSUE TITLE
Creating Empty Disk Errors - No UI Response

### ISSUE THREAD

**Issue by Dorthu** [linode/manager#1715]
The error in the networking log says the root_pass field was invalid, but it shouldn't be passed in at all without a distribution.  UI for this error is missing as well (probably because that field is hidden).

![screen shot 2017-05-08 at 11 37 49 am](https://cloud.githubusercontent.com/assets/7172953/25812092/3ff76770-33e3-11e7-98da-0e41994375d2.png)
![screen shot 2017-05-08 at 11 38 53 am](https://cloud.githubusercontent.com/assets/7172953/25812093/3fff0b9c-33e3-11e7-8c28-633642aba7dd.png)

**Comment by eatonphil** [comment]
Thanks! Should be dealt with in #1698

**Comment by eatonphil** [comment]
Closed in #1698
