### ISSUE TITLE
Add a Disk - cannot enter a root password

### ISSUE THREAD

**Issue by Dorthu** [linode/manager#1716]
When I type in the "Root password" box, no text appears.

![screen shot 2017-05-08 at 11 42 56 am](https://cloud.githubusercontent.com/assets/7172953/25812198/88c003b8-33e3-11e7-81a3-3e63699388f9.png)

**Comment by eatonphil** [comment]
Thanks! Should be dealt with in #1698

**Comment by eatonphil** [comment]
Closed in #1698
