### ISSUE TITLE
Implement restore from backup to current Linode

### ISSUE THREAD

**Issue by SirCmpwn** [linode/manager#173]

**Comment by eatonphil** [comment]
![screen shot 2016-07-05 at 1 38 07 pm](https://cloud.githubusercontent.com/assets/3925912/16593927/c3434452-42b5-11e6-9d6c-af17889d260f.png)
![screen shot 2016-07-05 at 1 38 16 pm](https://cloud.githubusercontent.com/assets/3925912/16593926/c342985e-42b5-11e6-960d-cf9cf42c640d.png)
