### ISSUE TITLE
Backups - UX and functional enhancements

### ISSUE THREAD

**Issue by phuegel** [linode/manager#1734]
**Backup Scheduler sample UI**
1. Config a schedule
2. Config a pattern
3. Config specific dates
4. Config time restrictions

![image](https://cloud.githubusercontent.com/assets/19841047/25913266/23c35040-3588-11e7-898f-49a1d54898f4.png)

_Reference link for Form language:_
https://www.veritas.com/support/en_US/article.v96219234_v113799574

**Backup Run History sample UI**
1. Display next backup job run scheduled date/time in UTC timezone
2. Display job UUID
3. Display Result - list of total Linodes, Partitions or Files backed up
4. Display date since last State change
5. Display total duration time taken to complete job

**Comment by stvnjacobs** [comment]
UTC is a large improvement from the current Manager.  Even now, in the current manager, we report it in "GMT -5 (EST)", which isn't entirely correct (we are currently "GMT -4 (EDT)").

I would like to propose that the backup window be set in the user's configured timezone.  The rest of the Manager (new and existing)  uses the user's timezone.  To the best of my knowledge, backups are the only place that deviates from this.

One example benefit is that backups can be planned according to lowpoints in activity using the Linode's graphs.
