### ISSUE TITLE
Reverse DNS page needs to support RDNS lookup

### ISSUE THREAD

**Issue by eatonphil** [linode/manager#1736]
Right now you can only modify reverse DNS for IPs that already have a reverse DNS assigned.

**Comment by eatonphil** [comment]
This is not currently supported by the API.

**Comment by eatonphil** [comment]
I believe this is still not supported by the API.

**Comment by asauber** [comment]
The API correctly queries DNS for A and AAAA records before assigning RDNS for an IP address.

Closing this issue because the original report isn't true anymore.
