### ISSUE TITLE
Update login panel css/wording

### ISSUE THREAD

**Issue by mparke** [linode/manager#1746]
![screen shot 2017-05-11 at 11 31 53 am](https://cloud.githubusercontent.com/assets/709951/25957960/7489bf7c-363d-11e7-9955-a8ecca083d63.png)

- remove alpha specific text
- update header text ( if needed, double check )
- reduce width of panel
- update css from recent manager changes if possible
- check redirect on success

**Comment by mparke** [comment]
@eatonphil part of this was updated, yeah?

**Comment by eatonphil** [comment]
Yep, all but setting a max-width.

**Comment by eatonphil** [comment]
Max-width has been set.
