### ISSUE TITLE
Fix layout error on some redirects

### ISSUE THREAD

**Issue by mparke** [linode/manager#1749]
![screen shot 2017-05-11 at 11 29 28 am](https://cloud.githubusercontent.com/assets/709951/25958601/0cb7bc9e-363f-11e7-8a98-e5d440963be9.png)

**Comment by na3d** [comment]
Wasn't able to replicate, may already be solved.  If anyone can verify and close, that would be great.

**Comment by na3d** [comment]
Appears to be solved, closing.
