### ISSUE TITLE
Text Overlap on Users > Permissions page

### ISSUE THREAD

**Issue by Dorthu** [linode/manager#1761]
The table headers for Access and Delete overlap, regardless of the size of the viewport.

![screen shot 2017-05-12 at 8 40 14 am](https://cloud.githubusercontent.com/assets/7172953/25998383/b7f35154-36ee-11e7-83f9-8ff758425074.png)

**Comment by eatonphil** [comment]
This has been fixed on master and will be deployed within the week. Thank you!
