### ISSUE TITLE
Mockup zone edit

### ISSUE THREAD

**Issue by eatonphil** [linode/manager#180]

**Comment by eatonphil** [comment]
There are two immediate options: an edit modal and inline-editing.

Here is the edit modal:

![screen shot 2016-06-29 at 8 05 25 am](https://cloud.githubusercontent.com/assets/3925912/16451333/57bc91aa-3dd0-11e6-98c3-af15849555a0.png)

I cannot demonstrate inline editing well, but hopefully you get the picture:

![screen shot 2016-06-29 at 8 05 34 am](https://cloud.githubusercontent.com/assets/3925912/16451341/68a56528-3dd0-11e6-90cc-85457f141f5c.png)

**Comment by SirCmpwn** [comment]
+1 to modal design for add/edit
