### ISSUE TITLE
Restoring from backup to an empty Linode doesn't change disk or configs state.

### ISSUE THREAD

**Issue by abemassry** [linode/manager#1810]
Steps to reproduce:
Create empty Linode
Restore backup to empty Linode
Manager automatically takes you to empty Linode's dashboard page
Click on Advanced, Settings
Linode has no disks or configs (still empty)
Refresh page
Linode now has restored configs and disks

Expected Behavior:
Configs and Disks should be there when you check without having to refresh

Some type of information probably needs to be added into the redux store.

**Comment by eatonphil** [comment]
This issue was unrelated to backups and happened anytime you landed on the Linode page and navigated through tabs to the advanced page. This has been fixed.
