### ISSUE TITLE
Mockup StackScripts create/edit

### ISSUE THREAD

**Issue by eatonphil** [linode/manager#182]

**Comment by eatonphil** [comment]
Very rough first draft sketches.
![screen shot 2016-07-05 at 10 18 04 am](https://cloud.githubusercontent.com/assets/3925912/16587720/f7ad45c4-4299-11e6-92df-0a4dca677dd6.png)
![screen shot 2016-07-05 at 10 18 13 am](https://cloud.githubusercontent.com/assets/3925912/16587719/f7a64e36-4299-11e6-9541-5b94b1f7389d.png)

**Comment by SirCmpwn** [comment]
Seems busy.

- Distro selection could hide the versions until you tick a vendor
- Distro selection should probably go underneath the script
- "Make public" checkbox should just say "Make public" and put the rest into the terms of service

**Comment by SirCmpwn** [comment]
I still think stackscripts should live under /stackscripts instead of /linodes by the way.

**Comment by eatonphil** [comment]
* Fair
* Just following the current order
* Do we have a link here to the TOS then?

**Comment by eatonphil** [comment]
I'm not necessarily against /stackscripts but I just want to make sure we don't throw too much in the top-level or have a good organization strategy.

**Comment by SirCmpwn** [comment]
Nah, we don't need the link to the ToS. Common sense applies.

>Just following the current order

Again, please don't take inspiration from the current manager when making new mockups. We don't want to make some of the bad decisions again.
