### ISSUE TITLE
Access section - improve the labels for better communication what it does

### ISSUE THREAD

**Issue by phuegel** [linode/manager#1822]
We use Linode specific terms that need to be defined when someone new to our platform using our services.

Console - indicate that access using these buttons are using Lish
eg. "Console via Lish"

Lish - should spell out what it represents in the helper text area.
eg. "Linode Shell (Lish) listens on ports 22, 443, and 2200."

Launch - this is an ambiguous term. What am I launching? This is actually a button that connects you to Lish using a web browser. Let's state that in the button itself.

**Option#1:**
![image](https://cloud.githubusercontent.com/assets/19841047/26257536/01747fce-3c8f-11e7-9ed6-90fd0d420e1c.png)

**Option#2:**
![image](https://cloud.githubusercontent.com/assets/19841047/26257429/9b828080-3c8e-11e7-953d-bdb10baca341.png)

**Comment by eatonphil** [comment]
I like it.
