### ISSUE TITLE
No indication of which backup you are on once you select a backup from the summary page

### ISSUE THREAD

**Issue by eatonphil** [linode/manager#1828]

**Comment by eatonphil** [comment]
Not true actually, there is a label field on the page that tells you what backup you are on. Making this more helpful would probably involve giving each backup its own full page (like the relationship between NodeBalancers and its configs). That's a bit more work. I think we should put those changes off for a bit especially since there is in fact a label present.

... Unless the issue is that you don't know if this is a daily / weekly backup. If that is the case... why would you need to know that?

**Comment by na3d** [comment]
You always have the start/end DT to work off of.
