### ISSUE TITLE
Ticket overflow on Domains on SOA record

### ISSUE THREAD

**Issue by RobertDeRose** [linode/manager#1830]
![screen shot 2017-05-19 at 3 33 09 pm](https://cloud.githubusercontent.com/assets/388745/26263960/ea2a4cd0-3ca8-11e7-8ad4-ee58fc81b4fd.png)

**Comment by mparke** [comment]
increase `th` width

**Comment by mparke** [comment]
Address in : https://github.com/linode/manager/issues/1873

**Comment by eatonphil** [comment]
This has been dealt with.

**Comment by zasdfgbnm** [comment]
Is this really resolved? I can still see it on:
https://cloud.linode.com/domains/XXXXXXX.XXXX
![screenshot_20171227_093147](https://user-images.githubusercontent.com/1032377/34384322-692c67ac-eb13-11e7-99eb-e3c5a320b55b.png)
