### ISSUE TITLE
Linode plans displayed in wrong order on /linodes/create

### ISSUE THREAD

**Issue by jfrederickson** [linode/manager#1836]
I think this is a Manager thing and not an API thing - curl appears to return them in the correct order.

![screen shot 2017-05-22 at 1 42 15 pm](https://cloud.githubusercontent.com/assets/1923178/26321978/10e75534-3ef7-11e7-8040-06c9e017eb1f.png)

**Comment by eatonphil** [comment]
Thanks! Actually that's already been fixed here https://github.com/linode/manager/pull/1783. It will be deployed soon.

**Comment by jfrederickson** [comment]
Oh awesome, thanks!
