### ISSUE TITLE
Support Page load bar disappears/reapears

### ISSUE THREAD

**Issue by yoshizzle** [linode/manager#1862]
When I click on the Support link, the green horizontal page load indicator starts, gets about 30% across the page, then completely disappears to reappear a second or two later from the beginning. At that point the page successfully loads.

**Comment by eatonphil** [comment]
This seems to happen on pages that take a long time to load. Did you have a ton of support tickets?

**Comment by yoshizzle** [comment]
Maybe 70? With no pagination it's hard to say, but I also suspect my number of tickets is low compared to others.
