### ISSUE TITLE
Disks not showing in Manager

### ISSUE THREAD

**Issue by Dorthu** [linode/manager#1876]
Disks do not show on the Linode > Settings > Advanced tab.  Querying the api I can retrieve the disks.  Looking at the requests the manager has sent, I don't see any requests for disks either.

![screen shot 2017-05-25 at 8 05 21 am](https://cloud.githubusercontent.com/assets/7172953/26449571/f27d10b2-4120-11e7-8799-be049c0e9169.png)
_This Linode has 2 disks and no unallocated space_

**Comment by na3d** [comment]
[Completed]
