### ISSUE TITLE
Snapshot errors formatting is incorrect and snapshot taken not shown after snapshot has been taken

### ISSUE THREAD

**Issue by abemassry** [linode/manager#1883]
I took a snapshot and was then directed to a page saying snapshot was being taken.

I went back to the same page there was no change, it said take first snapshot.  This is a problem because I just clicked the button.

I decided to click it again and it said Linode Busy.

Then after a few minutes I clicked it again and it said it was taking a snapshot, this is a problem because I have taken 2 first snapshots.

Same thing happened again, a third time.

The fourth time I clicked take snapshot it said a snapshot is already in progress.

![pasted image at 2017_05_25 10_54 am](https://cloud.githubusercontent.com/assets/1616275/26456070/0d17ea82-413a-11e7-86e5-1d9658598515.png)

![image](https://cloud.githubusercontent.com/assets/1616275/26456037/f586d108-4139-11e7-94a2-2369e41cc0b4.png)

The desired behavior is to disable the button after the first click and say snapshot in progress.

**Comment by eatonphil** [comment]
This is still an issue.
