### ISSUE TITLE
Delete modal can prompt for typed verification before deleting

### ISSUE THREAD

**Issue by eatonphil** [linode/manager#1890]

**Comment by abemassry** [comment]
For Linodes this would be ok

**Comment by mparke** [comment]
related: https://github.com/linode/manager/issues/1790

**Comment by phuegel** [comment]
1. On Deletion modal of Linodes/NodeBalancers/Domains ADD either a confirmation checkbox or an "I agree" text input box as required input before allowing the destructive "Delete" action to take place.

**Option #1:**
[x] Yes, remove this Linode from my account.

**Option #2:**
This action will permanently remove this Linode from your account.
Type "I agree" to confirm [ I agree ] 


2. Add the following warning disclosure to all destructive action modals:

**"This operation cannot be undone."**
