### ISSUE TITLE
Implement Linode detail settings Boot settings tab

### ISSUE THREAD

**Issue by eatonphil** [linode/manager#191]

**Comment by eatonphil** [comment]
![screen shot 2016-07-05 at 1 38 55 pm](https://cloud.githubusercontent.com/assets/3925912/16593941/db10d77a-42b5-11e6-806d-1e2f67e58e44.png)

**Comment by eatonphil** [comment]
If there is more than 1 config profile, everything below the kernel selection does not show up.

**Comment by SirCmpwn** [comment]
obsolete
