### ISSUE TITLE
Increase Client Secret modal to display full secret key

### ISSUE THREAD

**Issue by phuegel** [linode/manager#1915]
1. The Client Secret modal is not wide enough to properly display the full secret key (see screenshot). It need to be wider by ~ 3-4 more characters.

![image](https://cloud.githubusercontent.com/assets/19841047/26506440/a0a2974e-421a-11e7-9c2e-1d0314d65966.png)

2. Suggestion: Replace the "I Understand" button with a "Copy" button in order to automatically copy client secret key into memory.

**Comment by mparke** [comment]
Modal size increased in https://github.com/linode/manager/pull/1922, re-test client secret visibility

**Comment by eatonphil** [comment]
Done:
![screen shot 2017-05-31 at 2 52 10 pm](https://cloud.githubusercontent.com/assets/3925912/26648540/c82dfb1a-4610-11e7-829f-ce09ad4e64ed.png)
