### ISSUE TITLE
Implement Linode detail settings Advanced tab skeleton

### ISSUE THREAD

**Issue by eatonphil** [linode/manager#192]

**Comment by eatonphil** [comment]
![screen shot 2016-07-05 at 1 42 05 pm](https://cloud.githubusercontent.com/assets/3925912/16594033/5e9c9610-42b6-11e6-9ca2-1b3c68c4b53d.png)

**Comment by eatonphil** [comment]
1. Drop boot settings
1. Add warning

**Comment by phuegel** [comment]
Suggested UI improvement:

1. Remove ‘…settings’, from sub-menu as its redundant. You are already at ‘Settings’ menu tab
2. Selected sub-menu tab should be Blue+Bold to keep consistency in UI. When you select an option its Blue vs not selected its Gray.
3. Remove ‘Advanced title’,  its redundant
4. ‘WARNING’ message - requires a tooltip to explain what are usability optimizations, what is done automatically before these changes, is there are list of optimizations (which will be skipped), etc. 
5. ‘Profiles’ and ‘Disks’ sub-headings are virtual machine profiles, yes? calling this section ‘VM Profiles’ helps understand what this is used for.
6. To each Add button include ‘VM’ to each button - + Add a VM profile / + Add a VM Disk

**Comment by SirCmpwn** [comment]
1 3 4 :+1: 

2 5 6 :-1:
