### ISSUE TITLE
fix known missing param types

### ISSUE THREAD

**Issue by mparke** [linode/manager#1965]
param name: label, description: Creates a new Linode.

param name: group, description: Creates a new Linode.

param name: root_pass, description: Creates a new Linode.

param name: root_ssh_key, description: Creates a new Linode.

param name: with_backup, description: Creates a new Linode.
param name: label, description: Creates a new config for a given Linode.

param name: disks, description: Creates a new config for a given Linode.

param name: comments, description: Creates a new config for a given Linode.

param name: ram_limit, description: Creates a new config for a given Linode.

param name: root_device_ro, description: Creates a new config for a given Linode.

param name: devtmpfs_automount, description: Creates a new config for a given Linode.

param name: run_level, description: Creates a new config for a given Linode.

param name: virt_mode, description: Creates a new config for a given Linode.
param name: label, description: Creates a snapshot backup of a Linode. <div class="alert alert-danger">
  <strong>WARNING</strong>
  <p>
    If you already have a snapshot, this is a destructive operation.
    The previous snapshot will be deleted.
  </p>
</div>
param name: label, description: Create a new StackScript.

param name: description, description: Create a new StackScript.

param name: is_public, description: Create a new StackScript.

param name: rev_note, description: Create a new StackScript.

param name: script, description: Create a new StackScript.
param name: domain, description: Create a Domain.

param name: type, description: Create a Domain.

param name: soa_email, description: Create a Domain.

param name: description, description: Create a Domain.

param name: refresh_sec, description: Create a Domain.

param name: retry_sec, description: Create a Domain.

param name: expire_sec, description: Create a Domain.

param name: ttl_sec, description: Create a Domain.

param name: status, description: Create a Domain.

param name: master_ips, description: Create a Domain.

param name: axfr_ips, description: Create a Domain.

param name: display_group, description: Create a Domain.
param name: type, description: Create a Domain Record.

param name: name, description: Create a Domain Record.

param name: target, description: Create a Domain Record.

param name: priority, description: Create a Domain Record.

param name: weight, description: Create a Domain Record.

param name: port, description: Create a Domain Record.

param name: service, description: Create a Domain Record.

param name: protocol, description: Create a Domain Record.

param name: ttl, description: Create a Domain Record.
param name: label, description: Creates a new NodeBalancer.

param name: client_conn_throttle, description: Creates a new NodeBalancer.
param name: label, description: Creates a NodeBalancer config.

param name: port, description: Creates a NodeBalancer config.

param name: protocol, description: Creates a NodeBalancer config.

param name: algorithm, description: Creates a NodeBalancer config.

param name: stickiness, description: Creates a NodeBalancer config.

param name: check, description: Creates a NodeBalancer config.

param name: check_interval, description: Creates a NodeBalancer config.

param name: check_timeout, description: Creates a NodeBalancer config.

param name: check_attempts, description: Creates a NodeBalancer config.

param name: check_path, description: Creates a NodeBalancer config.

param name: check_body, description: Creates a NodeBalancer config.

param name: check_passive, description: Creates a NodeBalancer config.

param name: cipher_suite, description: Creates a NodeBalancer config.
param name: label, description: Creates a new NodeBalancer config node.
param name: address, description: Creates a new NodeBalancer config node.
param name: weight, description: Creates a new NodeBalancer config node.
param name: mode, description: Creates a new NodeBalancer config node.

**Comment by eatonphil** [comment]
nice!
