### ISSUE TITLE
Really long header text forces horiz scroll

### ISSUE THREAD

**Issue by mparke** [linode/manager#1993]
<img width="363" alt="screen shot 2017-06-01 at 4 00 45 pm" src="https://cloud.githubusercontent.com/assets/709951/26698324/89b715dc-46e3-11e7-959c-8048f8607e18.png">

**Comment by eatonphil** [comment]
This will interfere with the status dropdown before it hits here. We should set a max-length on these headers before then.

**Comment by mparke** [comment]
Also effects event notifications list:

![screen shot 2017-06-09 at 4 31 05 pm](https://user-images.githubusercontent.com/709951/26993457-191adf58-4d31-11e7-9740-fffeb1548a31.png)

**Comment by na3d** [comment]
Does 1873 fix this?

**Comment by na3d** [comment]
#2007 Closes this
