### ISSUE TITLE
Linodes List View - Add LinodeID and plan info to view

### ISSUE THREAD

**Issue by phuegel** [linode/manager#2042]
1. At a glance in Linode list view, display the original linodeID which we use to identify and bill for Linodes. Even if customers change the name of the Linode continue to display the initial LinodeID. This keeps parity with the way we display the Hostname for our NodeBalancers. With NBs, customers are able to rename them but we still show the original hostname without allowing them to edit it.

2. Also, display a brief summary of the plan details on the same line in the list view.

![image](https://user-images.githubusercontent.com/19841047/26939922-dafe6cd4-4c46-11e7-8ca5-66197fd31dff.png)

3. ADD - original LinodeID to Linode > Settings > Display that cannot be edited or renamed.
https://cloud.linode.com/linodes/centos-block1/settings

![image](https://user-images.githubusercontent.com/19841047/26939813-852958dc-4c46-11e7-9637-1d327a7a8b20.png)

**Comment by phuegel** [comment]
We should display the ID# at minimum in ALL Edit dialog boxes.

![image](https://user-images.githubusercontent.com/19841047/27599888-28292698-5b38-11e7-91ae-f4810f48ee4d.png)

**Comment by eatonphil** [comment]
That seems less useful to me than where we currently display ids: on label hover.

Furthermore, the majority of users won't care what the id is. The classic Manager doesn't show ids at all. It's most helpful IMO to developers trying to write scripts and use the Manager as a helper.
