### ISSUE TITLE
Linode - Multiple Linode action (Delete confirmation) add scrolling list past a 5+ selection

### ISSUE THREAD

**Issue by phuegel** [linode/manager#2046]
In order to keep the delete confirmation list of Linodes to a manageable/readable list, make the confirmation modal scrollable if the user selects more than say 5 Linodes to delete.

![image](https://user-images.githubusercontent.com/19841047/26945780-e63e32a0-4c5a-11e7-9aee-c147b34a8ed6.png)

**Comment by eatonphil** [comment]
Does it not scroll? That component's name is ScrollingList because the intent was that it scrolls. :)

**Comment by phuegel** [comment]
Not with 5 items or 6. What is the limit to allow it to scroll?

**Comment by eatonphil** [comment]
200px of height is the limit I believe.

**Comment by displague** [comment]
The count of affected Linodes would be nice.  I think the most common permutations would be:
- "...delete these 15 Linodes?". 
- Or "15 Linodes something [pad to right] This operation..."..
- Or "[cancel] [delete 15 Linodes]"

**Comment by eatonphil** [comment]
@displague that is a good idea.
