### ISSUE TITLE
Deletion modal of Linodes/NodeBalancers/Domains require user confirmation input

### ISSUE THREAD

**Issue by phuegel** [linode/manager#2054]
1. On Deletion modal of Linodes/NodeBalancers/Domains ADD either a confirmation checkbox or an "I agree" text input box as required input before allowing the destructive "Delete" action to take place.

**Option #1:**
[x] Yes, remove this Linode from my account.

**Option #2:**
This action will permanently remove this Linode from your account.
Type "I agree" to confirm [ I agree ] 

2. Add the following warning disclosure to all destructive action modals:

**"This operation cannot be undone."**

**Comment by eatonphil** [comment]
Could you mention this here https://github.com/linode/manager/issues/1890 instead?

**Comment by phuegel** [comment]
Dup of #1890
