### ISSUE TITLE
Docs - Add "Copy" text all copy button images

### ISSUE THREAD

**Issue by phuegel** [linode/manager#2064]
Do not reply solely on the icons to explain what they do. We need to include a some form of helper text to all images.

This is one example in our documentation where we need to provide a "Copy" action text as part of the icon being displayed. In addition, once the action completes on the subsequent "check-mark" displayed a "Copied" message should appear under the "check-mark."

![image](https://user-images.githubusercontent.com/19841047/26990657-5b595360-4d25-11e7-949f-34940980baff.png)

**Comment by Dorthu** [comment]
Migrated to here: https://github.com/linode/linode-api-docs/issues/27
