### ISSUE TITLE
Status is missing

### ISSUE THREAD

**Issue by eatonphil** [linode/manager#207]

**Comment by eatonphil** [comment]
![screen shot 2016-07-01 at 3 04 52 pm](https://cloud.githubusercontent.com/assets/3925912/16531995/3600f370-3f9d-11e6-9fa4-fa28d85f5957.png)
![screen shot 2016-07-01 at 3 04 25 pm](https://cloud.githubusercontent.com/assets/3925912/16531996/36275f6a-3f9d-11e6-8635-c2fa830e404d.png)

**Comment by SirCmpwn** [comment]
Needs more detail, cannot repro

**Comment by SirCmpwn** [comment]
Bump
