### ISSUE TITLE
Error handling for power management UIs

### ISSUE THREAD

**Issue by SirCmpwn** [linode/manager#210]
Split from #202.

Show error tooltip for:
- [ ] Boot jobs
  - [ ] Bulk reboot (and power off, etc.) on /linodes
  - [ ] Single reboot on /linodes
  - [ ] Single reboot on /linodes/:id

**Comment by eatonphil** [comment]
Since they could happen up to minutes after the action starts it makes more sense to me to have them show up as notifications instead of inline tooltips.

**Comment by eatonphil** [comment]
Closed by event dropdown implementation.
