### ISSUE TITLE
Can't deploy Centos 6.8 - distribution is not valid

### ISSUE THREAD

**Issue by akerl** [linode/manager#2102]
Repro steps:

* "Add a Linode"
* Centos 6.8 from the dropdown for Centos
* Newark
* Linode 1G
* Give it any label / root password
* Hit "Add Linode"
* I get "distribution is not valid" in red

**Comment by akerl** [comment]
Also appears to affect Debian 7

**Comment by akerl** [comment]
I've confirmed that I can deploy Centos 6.8 from the old manager (wanted to rule in/out that it was a Manager-side bug vs an issue w/ the Centos image itself.

**Comment by eatonphil** [comment]
Perhaps none of the items in the dropdown (aside from the top-level version) are working correctly. I'll take a look. Thanks for the bug report!

**Comment by akerl** [comment]
Tested that a moment after your comment; it does look like Fedora's older options work, so it doesn't seem to be global to all non-defaults.

**Comment by eatonphil** [comment]
Turns out you can't actually deploy deprecated distributions. I've hide them now in #2141.

**Comment by akerl** [comment]
You mean specifically via the new manager? I did successfully deploy Centos 6.8 via the old Manager

**Comment by eatonphil** [comment]
Thanks for pointing this out. After looking again, this is actually an issue where the API is returning the wrong id for the distribution. For instance for CentOS 6.8, it says the id is `linode/centos6.5`. Which is not a valid distro to deploy from. I'm closing out #2141 and getting the API guys to take a look. Will follow up when things look good.

**Comment by eatonphil** [comment]
The CentOS result is returning correctly now. And a fix for deploying Debian 7 will be going out in the next few days as well.

**Comment by eatonphil** [comment]
You should now also be able to deploy Debian 7. Thanks for the report!
