### ISSUE TITLE
Text bleed over styles for docs

### ISSUE THREAD

**Issue by abemassry** [linode/manager#2112]
![image](https://user-images.githubusercontent.com/1616275/27292900-cdff4e32-54e2-11e7-9eb8-484e402c6895.png)

**Comment by eatonphil** [comment]
Nice. Good catch.

**Comment by abemassry** [comment]
This specific issue of IPAddressType will be fixed when a fix for #2195 is done.  When the types are standardized we will know the length of each type and can adjust the width of the column appropriately
