### ISSUE TITLE
Mockup stackscript source selection

### ISSUE THREAD

**Issue by eatonphil** [linode/manager#212]

**Comment by eatonphil** [comment]
First take:
![screen shot 2016-07-13 at 11 08 54 am](https://cloud.githubusercontent.com/assets/3925912/16808365/3ab3adbc-48ea-11e6-8599-6d92bacb1ce7.png)

**Comment by na3d** [comment]
Is there going to be a toggle for StackScripts under their own account?

**Comment by eatonphil** [comment]
Good call. Hmm. Will think on that.

**Comment by SirCmpwn** [comment]
:+1:

**Comment by SirCmpwn** [comment]
ditto for nick's feedback

**Comment by eatonphil** [comment]
I also forgot you'll still need to be able to actually select the distro to use in addition to the stackscript.

**Comment by eatonphil** [comment]
![screen shot 2016-07-14 at 9 48 21 am](https://cloud.githubusercontent.com/assets/3925912/16841634/2427a846-49a8-11e6-8dd3-a4c3107bc22d.png)

**Comment by SirCmpwn** [comment]
Your choice of stackscript influences the distros you can choose. We should do these in the other order.

I also think that the means of not using a stackscript should be more obvious.

**Comment by eatonphil** [comment]
> Your choice of stackscript influences the distros you can choose. We should do these in the other order.

Ultimately the choice of order comes from that fact that a StackScript does not give you a Linode, a StackScript is "nothing more" than a provisioning step on top of a Linode. Now there are a few ways we can make this easier for users not to screw up:

* All "Featured Stackscripts" are fully supported by Linode for every distro
* Clicking on a StackScript that is not available for the distro you selected will give a small prompt indicating it is not available, the available distros, and a choice of selecting the recommend distro.

We can choose any level of either of these and I do not think it will be hard to brainstorm others. Ideally, the "Featured Stackscripts" will take care of enough of the most popular apps (WP, Drupal, etc.) that the only people using other stackscripts would be comfortable enough selecting a different distro.

> I also think that the means of not using a stackscript should be more obvious.

I agree but I can't think of a good way yet that is consistent with not selecting a source and not that disruptive in general.

**Comment by SirCmpwn** [comment]
I don't understand the aversion to simply switching their order of appearance. Sounds like both of those solutions have flaws.

**Comment by eatonphil** [comment]
My aversion to it is because that is not how provisioning works. You can't provision something without having the thing to provision.

**Comment by SirCmpwn** [comment]
I think the mental gap there is less important than having a more usable UI.

**Comment by eatonphil** [comment]
How about if someone is on some stackscript page and clicks deploy, it defaults to selecting the recommend distro and the stackscript (or on a stackscript page, I don't have a problem with letting them pick a distro there). But if someone just wants to create a Linode we keep this as a true provisioning step.

**Comment by SirCmpwn** [comment]
I don't think we have a recommended distro for stackscripts. I think we just have a list of supported distros, each of equal weight. And I'm more concerned about the usual create flow than I am about the stackscript page -> create page flow.

**Comment by SirCmpwn** [comment]
I think we should just resolve this by making stackscripts a tab on the source selection again and adding a mini-distro-selection to it.

**Comment by na3d** [comment]
I was thinking that StackScripts were going to stay up with everything else, some sort of toggle button (or checkbox Only Mine), and the distros would be loaded below the list of StackScripts, and change based on the selected StackScripts...

The reason I like the idea of in the tab group of distros and backups, is that it doesn't make it seem like it is required, more straight forward user flow.  It shouldn't be a big deal to recycle the distro cards at the bottom of the StackScripts tab.

**Comment by eatonphil** [comment]
As I've thought about it, I fully disagree with StackScripts being a source. StackScripts are not a source. They run on a source. We already have a source selection area. StackScripts happen on top of a source and are a completely separate step. It's one thing we tell users they can deploy "Wordpress" but that's not what is happening. Furthermore, StackScripts are not just applications. A StackScript can install 40 different dbs on a Linode; this is not an application. We should not conflate StackScripts with the source itself.

**Comment by na3d** [comment]
Can you have multiple non-related StackScripts?

**Comment by SirCmpwn** [comment]
No

**Comment by eatonphil** [comment]
That is probably more complex (UI-wise) than we need to allow.

**Comment by na3d** [comment]
You're right...  StackScripts should be a prerequisite to Source though, and the only clean way to do that, without having a wonky user flow, is including it in the sources, making is a Distro with StackScript, no?

**Comment by na3d** [comment]
Or maybe a toggle inside of distro for including StackScript?

**Comment by eatonphil** [comment]
![screen shot 2016-07-15 at 2 22 30 pm](https://cloud.githubusercontent.com/assets/3925912/16884488/b6632a24-4a97-11e6-8fcb-5180e6cb2e32.png)
![screen shot 2016-07-15 at 2 22 38 pm](https://cloud.githubusercontent.com/assets/3925912/16884486/b6611964-4a97-11e6-806d-8489cf8692b0.png)
![screen shot 2016-07-15 at 2 22 46 pm](https://cloud.githubusercontent.com/assets/3925912/16884487/b6629e2e-4a97-11e6-9a86-bd97b8d26213.png)

**Comment by SirCmpwn** [comment]
Less patronizing language, more straightforward messaging.

**Comment by SirCmpwn** [comment]
Looks good though, :+1:

**Comment by eatonphil** [comment]
> Less patronizing language, more straightforward messaging.

Wasn't intentional, is this better?

![screen shot 2016-07-15 at 2 33 05 pm](https://cloud.githubusercontent.com/assets/3925912/16884753/1cad2fcc-4a99-11e6-96f6-6e6c73f55918.png)
![screen shot 2016-07-15 at 2 33 13 pm](https://cloud.githubusercontent.com/assets/3925912/16884754/1cade55c-4a99-11e6-8090-802301ce18d8.png)

**Comment by SirCmpwn** [comment]
Yes.

Also, what happens if I pick a backup from the list of sources?

**Comment by eatonphil** [comment]
> Also, what happens if I pick a backup from the list of sources?

Good question. Do not provision could be checked and clicking it could be disabled. Or this same failure message would just appear for all StackScripts because a backup source is invalid. Or we enable StackScripts on first boot of a backup (would be cool to have a custom script you ran on first restore boot.)

**Comment by eatonphil** [comment]
If we went with the last point then we would also probably include a warning saying it can be dangerous to use an arbitrary stackscript on a restored linode. Or have stackscripts that are flagged only for backup restore use.

**Comment by eatonphil** [comment]
Or the provision step just goes away if you click a backup.
