### ISSUE TITLE
Block storage mockups

### ISSUE THREAD

**Issue by abemassry** [linode/manager#2124]
TODO:

* Volumes page listing all volumes in all datacenters
  * Add a Volume
  * Edit volume?
* Volumes list on settings advanced page
  * Edit volume?

**Comment by eatonphil** [comment]
![screen shot 2017-06-25 at 3 19 22 pm](https://user-images.githubusercontent.com/3925912/27518997-c4f31202-59b9-11e7-8a12-97283b65f8d7.png)
![screen shot 2017-06-25 at 3 19 30 pm](https://user-images.githubusercontent.com/3925912/27518999-c4f59c7a-59b9-11e7-8fe2-edd7591df44d.png)
![screen shot 2017-06-25 at 3 19 38 pm](https://user-images.githubusercontent.com/3925912/27518998-c4f3fa1e-59b9-11e7-8578-aa9ce7d55f48.png)
![screen shot 2017-06-25 at 3 19 51 pm](https://user-images.githubusercontent.com/3925912/27518996-c4f31ec8-59b9-11e7-941d-a17bba05e199.png)

**Comment by mparke** [comment]
Looks cool,

Question:

- what should we use as the default volume size when creating?

**Comment by eatonphil** [comment]
@mparke whatever they currently do or whatever @briansteffens suggests? :D

**Comment by eatonphil** [comment]
Closing for now.
