### ISSUE TITLE
Mockup needed for status dropdown needs feedback on failure

### ISSUE THREAD

**Issue by abemassry** [linode/manager#2126]
Mockup needed for #1775

**Comment by eatonphil** [comment]
Here are a few options. I don't really feel strongly about any of them in particular.
![screen shot 2017-06-26 at 12 34 20 pm](https://user-images.githubusercontent.com/3925912/27549981-f0729b52-5a6b-11e7-851f-719241d80a24.png)
![screen shot 2017-06-26 at 12 34 27 pm](https://user-images.githubusercontent.com/3925912/27549982-f07368c0-5a6b-11e7-8703-fce13992ddae.png)
![screen shot 2017-06-26 at 12 34 35 pm](https://user-images.githubusercontent.com/3925912/27549983-f0734c96-5a6b-11e7-9d35-2de02e61ff3d.png)
![screen shot 2017-06-26 at 12 34 44 pm](https://user-images.githubusercontent.com/3925912/27549980-f072988c-5a6b-11e7-990e-5f18ab7df0e3.png)
![screen shot 2017-06-26 at 12 34 52 pm](https://user-images.githubusercontent.com/3925912/27549984-f073d3dc-5a6b-11e7-99f6-ede3b18c1c77.png)

**Comment by abemassry** [comment]
I like these two
![screen shot 2017-06-26 at 12 34 44 pm](https://user-images.githubusercontent.com/3925912/27549980-f072988c-5a6b-11e7-990e-5f18ab7df0e3.png)
![screen shot 2017-06-26 at 12 34 52 pm](https://user-images.githubusercontent.com/3925912/27549984-f073d3dc-5a6b-11e7-99f6-ede3b18c1c77.png)

**Comment by mparke** [comment]
Ditto to abe's likes.

A couple questions:

- do we know in the message associated with the error state *why* exactly it failed? and can we show if that's the case
- if we don't/won't know, and failure state is unrecoverable, should we link to open a support ticket? should also open with linode id selected
- how does the failure state resolve once fixed?

**Comment by eatonphil** [comment]
@mparke I don't think we have any more errors to report right now. But if we did I think we could just show it in the text bubble.

**Comment by eatonphil** [comment]
Closing for now.

**Comment by eatonphil** [comment]
After thinking on it a bit more, some pros / cons:

Pros for positioning alert by the notification icon:

1.  Doesn't duplicate information in multiple places
2. If the user navigates away from the Linodes section, they still get a bigger notification that the job failed
3. A little more flexible across other parts of the site that may have jobs triggered in places other than their equivalent StatusDropdown

Pros for positioning alert by the StatusDropdown:

1. It's nearer the event that triggered the failure (only if they don't use the mass dropdown, but even then it's still associated near the row and where power status is displayed)
