### ISSUE TITLE
Mock-up Stackscripts create function

### ISSUE THREAD

**Issue by bralski1** [linode/manager#2127]

**Comment by mparke** [comment]
Create form basics

https://projects.invisionapp.com/boards/SR3A0W6MA87CJ/

**Comment by eatonphil** [comment]
lgtm

**Comment by eatonphil** [comment]
This has a few things I've wanted for us for a while: filterable select and a list input. Those would both be useful in many places. Actually now that I look at it, I'm not really sure which one seems more reasonable... the giant list of checkboxes or a select. What makes you feel one way or the other?

**Comment by eatonphil** [comment]
One other thing we may want to think about is if we're heading toward smaller "create" modals, it may be better to put off some details to the edit page. So the stackscript (editor) itself and maybe even the distros should go on the edit page so the create modal is short and concise.

**Comment by mparke** [comment]
> Actually now that I look at it, I'm not really sure which one seems more reasonable for distributions... the giant list of checkboxes or a select. What makes you feel one way or the other?

Anything that has more than 5 options I've typically seen in a select, otherwise we're left with this sort of wall of text on the page. It should be easy to search / find distros from the multi-select, especially since the creator will likely know which distros they need / want to target.

> if we're heading toward smaller "create" modals, it may be better to put off some details to the edit page.

I like this idea, since it's also more inline with many of the pages already setup, so you'd imagine name + description maybe in a modal, submit + redirect to edit page ?

**Comment by eatonphil** [comment]
> Anything that has more than 5 options I've typically seen in a select, otherwise we're left with this sort of wall of text on the page. It should be easy to search / find distros from the multi-select, especially since the creator will likely know which distros they need / want to target.

Fair. I think the one advantage may have been to be able to select an entire family of versions at a time in the previous one. But we could make that happen here too with a custom Select element (and not using unselectable optgroups).

> I like this idea, since it's also more inline with many of the pages already setup, so you'd imagine name + description maybe in a modal, submit + redirect to edit page ?

I think we should focus on streamlining creates more and this would do something just like that.

**Comment by abemassry** [comment]
👍

**Comment by mparke** [comment]
Screenshots in link above updated

**Comment by mparke** [comment]
Just closing to mark done, but we should re-open when updates needed

**Comment by eatonphil** [comment]
I like the idea behind having includes and UDFs defined in the UI. However, that makes things more complicated. I'm still not certain about searching for StackScripts (having been considering how that would work on the Linoide create from stackscript page)... Perhaps we should open up a new window whenever something needs to search for StackScripts. That search is just going to be humongous...

Throwing out another layout for the StackScript page:

![screen shot 2017-07-09 at 6 09 55 pm](https://user-images.githubusercontent.com/3925912/27998010-fae49052-64d1-11e7-8c2c-63b76b235c37.png)
