### ISSUE TITLE
Mock-up site wide grouping

### ISSUE THREAD

**Issue by bralski1** [linode/manager#2130]

**Comment by eatonphil** [comment]
First shot:

![screen shot 2017-06-26 at 2 46 45 pm](https://user-images.githubusercontent.com/3925912/27554997-4abb3954-5a7e-11e7-8e05-b1b490ec97cf.png)

**Comment by eatonphil** [comment]
For now we'd just sort the groups themselves consistently alphabetically or something.

**Comment by eatonphil** [comment]
This filter option would not preclude us from having a global search feature. I think this would be a good idea anyway.

**Comment by mparke** [comment]
I like the sort menu and how it works with groups here.

Question:

- how do you select ASC/DESC?

**Comment by eatonphil** [comment]
Oh whoops. Forgot that:
![screen shot 2017-06-26 at 4 12 57 pm](https://user-images.githubusercontent.com/3925912/27558170-5ef16a2c-5a8a-11e7-90ac-cdb8e895140c.png)

Then on mobile these should probably just collapse below the mass select things and filter.

**Comment by eatonphil** [comment]
Closing for now.
