### ISSUE TITLE
Mock-up create from backup

### ISSUE THREAD

**Issue by bralski1** [linode/manager#2133]

**Comment by eatonphil** [comment]
Some pretty new stuff here:
![screen shot 2017-06-26 at 2 22 56 pm](https://user-images.githubusercontent.com/3925912/27553996-06d6659a-5a7b-11e7-93b4-db7e34a309db.png)
![screen shot 2017-06-26 at 2 23 02 pm](https://user-images.githubusercontent.com/3925912/27553995-06d54c8c-5a7b-11e7-9492-ff3070abc2aa.png)

**Comment by eatonphil** [comment]
And what "Add a Linode" might look like along these lines:
![screen shot 2017-06-26 at 2 28 53 pm](https://user-images.githubusercontent.com/3925912/27554252-d6e09422-5a7b-11e7-9d64-aad952c1ad48.png)

**Comment by eatonphil** [comment]
And in the spirit of ignoring more complex features of configs and disks, clone from linode might look like:
![screen shot 2017-06-26 at 3 32 54 pm](https://user-images.githubusercontent.com/3925912/27556738-c89fbb6e-5a84-11e7-9027-a127c608d82c.png)

**Comment by phuegel** [comment]
Sugested changes:
1. Change dialog box title from "Clone from Linode" --> to "Clone from an existing Linode"
2. Change order to "Select a Linode" first, then set the "Label"

**Comment by eatonphil** [comment]
1. That's pretty long for a button text and doesn't seem that much clearer.
2. It would be more consistent with the rest of the add modals to keep the label first. :shrugs:

**Comment by eatonphil** [comment]
Closing for now.
