### ISSUE TITLE
Implement Linode detail settings Advanced Profile list

### ISSUE THREAD

**Issue by eatonphil** [linode/manager#215]

**Comment by eatonphil** [comment]
![screen shot 2016-07-05 at 1 42 05 pm](https://cloud.githubusercontent.com/assets/3925912/16594029/5869e16c-42b6-11e6-910d-b9384b318cb0.png)

**Comment by eatonphil** [comment]
Sorry about that, that was an old mockup.
![screen shot 2016-08-19 at 8 49 31 am](https://cloud.githubusercontent.com/assets/3925912/17810226/e3dfa668-65e9-11e6-828e-3ecd8e2602a1.png)

**Comment by na3d** [comment]
Could we use the trashcan, instead of the word delete?

**Comment by eatonphil** [comment]
I am trying to move us away from icons especially when there is no
associated text. I do not care that it looks slightly more redundant.

**Comment by SirCmpwn** [comment]
What if we made the word "Delete" use text-danger?

**Comment by eatonphil** [comment]
-1, that would probably bring unnecessary attention to it. Just add a confirm delete modal to be safe.

**Comment by SirCmpwn** [comment]
I'd like to find a way to visually distinguish between a thing that is a link and a thing that does an action.

**Comment by eatonphil** [comment]
That's fairish. Github does it by using gray. Then on hover become darker gray or blue.

**Comment by SirCmpwn** [comment]
Let's see how that ends up looking, then.

**Comment by SirCmpwn** [comment]
Github also uses icons, fwiw.

**Comment by eatonphil** [comment]
Github is not perfect. Gmail also uses lots of icons. And I have no idea what many of them mean.

**Comment by SirCmpwn** [comment]
That's why they clarify when you hover over them.

**Comment by na3d** [comment]
Gmail also uses color coding, which may be interesting to explore later, way too early right now.

So, go with gray, and hover color change for now.

**Comment by eatonphil** [comment]
> That's why they clarify when you hover over them.

Although we talked about that once before (trash can expands and shows delete), you haven't been very in favor of tooltips. If we needed icons alone I'd say yes we should include tooltips.

I'm sure the reason for having labels is obvious enough anyway. But if you want a read, here are two articles by a famous UX research group on [icon usability](https://www.nngroup.com/articles/icon-usability/) and (slightly less relevant) [icon testing](https://www.nngroup.com/articles/icon-testing/). One quote from the first article:

> And **always include a visible text label**. As Bruce Tognazzini once said, “a word is worth a thousand pictures.”

**Comment by eatonphil** [comment]
> Gmail also uses color coding, which may be interesting to explore later, way too early right now.

Gmail and Google in general really, really suck at usability. That's not to say that they don't do anything well. But just because a major company does stuff doesn't make it right - and I think a lot of what they do is clearly inhibitive to users.

**Comment by SirCmpwn** [comment]
Not everything you read online is true :wink: 

And I'm not really opposed to icons. Dunno why I would have said that.

**Comment by eatonphil** [comment]
That group's articles are based on the research they do. That doesn't make it true, but they put a lot more effort into actually studying/recording behavior than your average Medium author does.

> And I'm not really opposed to icons. Dunno why I would have said that.

I don't think I said you were opposed to icons, but you previously have not been in favor of tooltips when the easier solution was just to have labels.
