### ISSUE TITLE
Unable to close drop-down after deleting a group of Linodes from the /linodes page

### ISSUE THREAD

**Issue by jfrederickson** [linode/manager#2150]
When you delete several Linodes at once (by selecting their checkboxes and choosing "delete" from the drop-down) you're unable to close the drop-down menu once deletion is complete. The drop-down button is greyed out when there's nothing selected, but if you've just deleted the items you've selected it'll be both open and greyed out.

It's also possible to replicate this by checking a Linode's checkbox, opening the drop-down menu, and unchecking the checkbox again.

Proposed fix: close the drop-down menu automatically if all Linodes are unchecked.

**Comment by eatonphil** [comment]
Woah, nice catch. I think we may end up disabling the disabled button when nothing is selected. People seem to find that pretty annoying.
