### ISSUE TITLE
Implement Linode detail settings Advanced Profile edit part un

### ISSUE THREAD

**Issue by eatonphil** [linode/manager#217]

**Comment by eatonphil** [comment]
![screen shot 2016-07-05 at 1 49 13 pm](https://cloud.githubusercontent.com/assets/3925912/16594263/96531272-42b7-11e6-8206-9da5daecb512.png)
![screen shot 2016-07-05 at 1 49 22 pm](https://cloud.githubusercontent.com/assets/3925912/16594264/96530b38-42b7-11e6-9f0a-a9ab95e561af.png)

If Xen:
![screen shot 2016-07-05 at 1 49 34 pm](https://cloud.githubusercontent.com/assets/3925912/16594262/964f89c2-42b7-11e6-8f1f-f19313abf695.png)

If there are more than 2 config profiles, the boot settings section should be included here below the block device assignment.

**Comment by eatonphil** [comment]
1. Add boot helpers and kernel dropdown to a last section
1. All disks show up in xen mode
1. No paravirt option stuff in xen mode

**Comment by eatonphil** [comment]
Do all above the block device assignment.

**Comment by SirCmpwn** [comment]
https://github.com/react-component/slider
