### ISSUE TITLE
Implement Linode detail settings Advanced Disk add a disk

### ISSUE THREAD

**Issue by eatonphil** [linode/manager#218]

**Comment by eatonphil** [comment]
![screen shot 2016-07-05 at 1 41 41 pm](https://cloud.githubusercontent.com/assets/3925912/16594004/3c3d7ca6-42b6-11e6-8993-7eeb1bc9fa96.png)

**Comment by SirCmpwn** [comment]
![buttslol](https://cloud.githubusercontent.com/assets/1310872/17485242/18129770-5d5b-11e6-8eb0-2f8f57129f14.png)

**Comment by SirCmpwn** [comment]
(I got paid to make that)

**Comment by SirCmpwn** [comment]
Discussed on IRC: we should add a list of your disks underneath the fancy UI.

Also:

* Disks in the fancy UI should have a minimum width
* Maybe we should put a max on the number of disks a linode can have?
* Dragging where the red arrows indicate resizes the disk
* Clicking a disk would pop up a modal to edit its label and size
* Same modal would be reused for disk creation
* Disks cannot be rearranged
