### ISSUE TITLE
Further discussion/adjustments to advanced profile/disk editing

### ISSUE THREAD

**Issue by SirCmpwn** [linode/manager#220]

**Comment by eatonphil** [comment]
Here is where we are today:

![screen shot 2016-07-12 at 10 28 00 am](https://cloud.githubusercontent.com/assets/3925912/16770614/9a3e6b98-481b-11e6-917a-eb287b29f9f6.png)
![screen shot 2016-07-12 at 10 28 20 am](https://cloud.githubusercontent.com/assets/3925912/16770615/9a3e8b50-481b-11e6-8452-e1ae51341c33.png)
![screen shot 2016-07-12 at 10 28 26 am](https://cloud.githubusercontent.com/assets/3925912/16770617/9a44c268-481b-11e6-9285-db6160eed6bc.png)
![screen shot 2016-07-12 at 10 28 07 am](https://cloud.githubusercontent.com/assets/3925912/16770618/9a449bda-481b-11e6-8ca1-87db2e90435c.png)
![screen shot 2016-07-12 at 10 28 33 am](https://cloud.githubusercontent.com/assets/3925912/16770616/9a439438-481b-11e6-9aee-bb3700a0989c.png)

**Comment by SirCmpwn** [comment]
Several thoughts.

First, we discussed making disks editable with a custom UI more along the lines of gparted. [Screenshot](http://gparted.org/screens/gparted-main-window.png)

Second, I feel like we're trying to overcomplicate things by making all of this UI different based on what your Linode looks like. Our discussions thus far have made me think this is pretty overengineered. I don't think we should consider our users to dumb to understand profiles and disks. The ones who won't grok it probably won't even see this UI. So let's make it nice for the users who do.

I think we should make an alerts tab, a disks tab, and a profiles tab. On the profiles tab, if you have just one profile we can drop you straight into `/linodes/:id/settings/profiles/:id` to edit that profile. If you have several, you get a selection.

**Comment by SirCmpwn** [comment]
We can include sufficiently scary warnings about how these are advanced features and links to the docs explaining them, too.

**Comment by SirCmpwn** [comment]
Further inspiration for disk editing:

![](http://www.howtogeek.com/wp-content/uploads/2014/03/ubuntu-partitioning-installer.png)

**Comment by SirCmpwn** [comment]
Another thing that was mentioned is that your kernel lives on your config profile, not on the linode.

**Comment by SirCmpwn** [comment]
So does everything else in the boot settings tab. So it would get weird when you have several profiles.
