### ISSUE TITLE
cloud linode manager: single instance delete action delay

### ISSUE THREAD

**Issue by arturmartins** [linode/manager#2232]
Delete is next to Launch Console. 

In a scenario that something is wrong and the person is doing troubleshooting late in the night, mistakes can happen and accidentally machines might be deleted.

To avoid those, I would recommend the following:

Delete action is only active after mouseover during 5 seconds (show a process bar below the text)
The prompt to confirm, should be in RED as well as the delete and cancel buttons need to apart from each other. Delete button should have a waiting time of 2 seconds.

**Comment by eatonphil** [comment]
Hey! Delete always launches a confirm modal. So you never need to worry about accidentally pressing it.
