### ISSUE TITLE
Consider switching to testdouble.js for mocking

### ISSUE THREAD

**Issue by SirCmpwn** [linode/manager#227]
[testdouble.js](https://github.com/testdouble/testdouble.js) has a nicer API and is more stable and plays more nicely with newer JS developments. Sinon has also been working on 2.0.0 for 10 months now, and this morning our build was broken because we depend on the 2.0.0 prerelease version and a breaking change was made overnight.

**Comment by eatonphil** [comment]
http://blog.testdouble.com/posts/2016-03-13-testdouble-vs-sinon.html

**Comment by SirCmpwn** [comment]
They have an [article](http://blog.testdouble.com/posts/2016-03-13-testdouble-vs-sinon.html) on testdouble versus sinon.

**Comment by eatonphil** [comment]
hehe

**Comment by mparke** [comment]
Related: https://github.com/linode/manager/issues/1677

**Comment by rjstires** [comment]
Switched to Jest, closing.
