### ISSUE TITLE
Mockup new graph layout to display more at once

### ISSUE THREAD

**Issue by eatonphil** [linode/manager#2336]

**Comment by eatonphil** [comment]
![screen shot 2017-08-11 at 1 59 47 pm](https://user-images.githubusercontent.com/3925912/29225780-97ea899e-7e9d-11e7-8f54-06b34a5fbb1e.png)

**Comment by abemassry** [comment]
Looks really good only suggestion is swap IO and IPv4 in the 2x2 view that way the networking lines up chronologically and the CPU and IO line up chronologically.

**Comment by na3d** [comment]
Definitely like the 2X2 grid, gives the ability to see everything at the same time.
