### ISSUE TITLE
Styles for backup restore radio buttons is wonky

### ISSUE THREAD

**Issue by SirCmpwn** [linode/manager#234]

**Comment by SirCmpwn** [comment]
![2016-07-08_13 16 46](https://cloud.githubusercontent.com/assets/1310872/16695503/418b5aca-450e-11e6-93e1-9e3300838661.png)

**Comment by eatonphil** [comment]
Here is an example radio button:
https://github.com/linode/manager/issues/173

**Comment by bralski1** [comment]
Scope is to make compatible in all browsers.
