### ISSUE TITLE
Add group and quantity options to add a linode

### ISSUE THREAD

**Issue by eatonphil** [linode/manager#235]
Quantity is a number field - as it increases, more label fields are added for each linode. There should be some reasonable max.

Group should be a switch toggling between existing (which is a select of existing groups) and new (which is a text input).

**Comment by Dorthu** [comment]
Doh, sorry.

**Comment by eatonphil** [comment]
Here are two variations:

![screen shot 2016-08-04 at 11 17 37 am](https://cloud.githubusercontent.com/assets/3925912/17407527/9c887a48-5a35-11e6-9528-9f0645f2b31c.png)
![screen shot 2016-08-04 at 11 21 19 am](https://cloud.githubusercontent.com/assets/3925912/17407526/9c87e47a-5a35-11e6-80d6-7117298c9046.png)
![screen shot 2016-08-04 at 11 20 36 am](https://cloud.githubusercontent.com/assets/3925912/17407528/9c8d5e50-5a35-11e6-9f81-fd336817f73e.png)

**Comment by eatonphil** [comment]
I feel meh about that first one because it lacks context. So here are two better shots of the last two again (noting the create linode button should say create linodes if you have multiple):

![screen shot 2016-08-04 at 11 23 07 am](https://cloud.githubusercontent.com/assets/3925912/17407635/03d817a8-5a36-11e6-8e81-99f3adc9f567.png)
![screen shot 2016-08-04 at 11 22 57 am](https://cloud.githubusercontent.com/assets/3925912/17407634/03d6d6a4-5a36-11e6-8305-92b9d8fbd62d.png)

**Comment by phuegel** [comment]
Details section corresponds to the VM creation workflow. So for clarity renaming some items will make it more clear to the enduser what data is being requested in this section. By adding ‘Linode’ or ‘VM’ to labels

1. Rename 'Details' heading to 'Linode Creation Details'
2. Rename Group label 'Linode Group Name:' or 'VM Group Name:'. Now is Group name optional? if so, call it out in placeholder text
3. Rename 'Quantity:' to 'Linode Quantity:' or 'VM Quantity:'
4. Rename each label to 'Linode Label:'  or 'VM Label:' for single node creations and add 'Linode Label (1):'  or 'VM Label (1):' depending on quantity selected.
5. If multiple VM quantities are selected, call out that the root password will be the same on all Linodes created using a tooltip or default ALERT: under or password selection field.
6. Also, if multiple quantities are selected AND the Backups checkbox is selected it will enable backups on all VMs created. We need to display per Linode and call it out as per VM ($2.50ea. VM / month)

**Comment by SirCmpwn** [comment]
I think most of those changes are unncessarily verbose.

5 - good idea

6 - maybe we should put the enable backups button next to the label?

**Comment by phuegel** [comment]
Yes there should be some level over verbosity but I agree not too much to make it simple and extremely intuitive for the typical enduser of this management tool.

So navigating to a section labeled 'Linode Creation Details' a new Manager user would know exactly what is being requested there.

Same goes for seeing "Group" vs. "Linode Group Name", "Label" vs. "VM Label" will definitely help the uninitiated or experienced Manager user with usability.

Making things easy for endusers is our goal. Clearly labeling and/or using iconography will help us achieve great usability with this tool.

**Comment by SirCmpwn** [comment]
I mean, they will have arrived at this page by clicking the "Add a Linode" button. The heading on the top of the page says "Add a Linode".
