### ISSUE TITLE
Syntax highlighting for StackScripts should be based on the script's shebang

### ISSUE THREAD

**Issue by rmcintosh** [linode/manager#2361]
We should switch between syntax highlighting modes based on the language indicated in the script, rather than assuming a default

**Comment by eatonphil** [comment]
👍

**Comment by eatonphil** [comment]
This is a bigger deal than I originally thought. We'd having to dynamically load the mode files if we wanted to keep the bundle light. That's going to require a bit of work and we'd also have to make sure the mode files are available. Putting this on hold for the moment.
