### ISSUE TITLE
Fix docs breadcrumbs like /domains -> /domains and /volumes -> /volumes

### ISSUE THREAD

**Issue by eatonphil** [linode/manager#2372]

**Comment by eatonphil** [comment]
![screen shot 2017-08-04 at 8 56 19 am](https://user-images.githubusercontent.com/3925912/28969500-cd606306-78f2-11e7-823c-68b389411a78.png)

**Comment by Dorthu** [comment]
Migrated this to here: https://github.com/linode/linode-api-docs/issues/26

**Comment by displague** [comment]
Likewise,
![image](https://user-images.githubusercontent.com/317653/34490220-3134019a-efad-11e7-88e4-d460c293c4a5.png)
In situations like this, the $id page should be accessible through the breadcrumb(s).

Perhaps using two links in the sub-item (with distinguishing styles/classes):
[Top Level](http://0.0.0.0) > [/sub/$id](http://0.0.0.0) [/lower](http://0.0.0.0)
