### ISSUE TITLE
Revoke Dialog Incorrectly Hides Duplicate Labels

### ISSUE THREAD

**Issue by Dorthu** [linode/manager#2444]
I happened to have some 14 OAuth Tokens with the same label on my account, and went to mass-revoke them.  The UI only showed one token in the list of things to revoke:

![screen shot 2017-08-23 at 8 58 46 am](https://user-images.githubusercontent.com/7172953/29617011-54943ed6-87e1-11e7-8d68-23fc41239528.png)

It did correctly revoke all 14 tokens.

**Comment by na3d** [comment]
${label} (xN)
