### ISSUE TITLE
Label Validation

### ISSUE THREAD

**Issue by illblew** [linode/manager#247]
If you provide a Linode label invalid symbols it locks "Create Linode" even after providing valid characters. To fix this you currently need to refresh the page. Screenshot below.

![derp](https://cloud.githubusercontent.com/assets/1937357/16778116/7b67a2b0-483a-11e6-9462-472d8434dff9.png)

**Comment by eatonphil** [comment]
Nice. Thanks!

**Comment by RobertDeRose** [comment]
@illblew you beat me too it

**Comment by RobertDeRose** [comment]
Can I recommend that you do client side validation for things, or maybe we make an it possible to send an OPTIONS request to an endpoint to get the validation requirements, or just a query parameter to the endpoint that just sends back the validation requirements

POST /linodes?validationonly=1

Something like that would allow you to dynamically add client side validation, would be interesting.

**Comment by SirCmpwn** [comment]
:-1: to client side validation, for now. We talked about this a while ago, and I don't want to try and make up some wire format for validation rules, especially ones as complicated as label rules, and I don't want to duplicate them by writing them both in the API and in the manager.

**Comment by RobertDeRose** [comment]
Well, I think it would be awesome, it would allow the manager to be up to date without needing coding changes. The wire format, just a JSON object with field names and an array of validation types; length, character limit via PCRE, type (string, integer, etc, etc), and other thinks we thing of. Pretty basic to start with, expand as our use-cases increase. You could even make it so it returns the required payload as well and completely dynamically generate new fields.  A dynamic generated manager!!!! OK, I'm getting a little crazy now, but I love the idea.

**Comment by SirCmpwn** [comment]
The manager is already always up to date without coding changes. Just press submit and it'll report the errors the API gives :)

**Comment by RobertDeRose** [comment]
Yes, but you need to know ahead of time what fields the payload takes, It doesn't dynamically add and remove fields as the API changes, I mean I know that's insanity, I'm just toying with an idea of how this could dynamically support v5 of the API when we work on that, without needing to be completely re-written. A pure hateoas based Manager. The true purpose of REST APIs!!!
