### ISSUE TITLE
linode/distributions docs has overlapping text and missing json example response data

### ISSUE THREAD

**Issue by yoshizzle** [linode/manager#2477]
You probably already know about the overlapping, but here is an example so you can see.

![screen shot 2017-08-28 at 13 08 06](https://user-images.githubusercontent.com/9656795/29784459-0268d4ae-8bf2-11e7-8c4c-df836bc4285e.png)

Also, there is no example JSON return data for this endpoint.

**Comment by eatonphil** [comment]
No longer an issue.
