### ISSUE TITLE
docs - /linode/instances/:id/ips/sharing goes to wrong place

### ISSUE THREAD

**Issue by yoshizzle** [linode/manager#2480]
Clicked on the link on docs page here:

![screen shot 2017-08-29 at 08 24 27](https://user-images.githubusercontent.com/9656795/29820756-8a009a22-8c93-11e7-833d-0f47bd5f3039.png)

Takes me here:

![screen shot 2017-08-29 at 08 22 34](https://user-images.githubusercontent.com/9656795/29820665-3d7f170a-8c93-11e7-899a-32d91d45bae7.png)

**Comment by eatonphil** [comment]
Thanks! This is a dup of #2454
