### ISSUE TITLE
TTL dropdown stays within modal window

### ISSUE THREAD

**Issue by jfrederickson** [linode/manager#2490]
This looks a bit weird, IMO:

<img width="630" alt="screen shot 2017-08-30 at 3 16 05 pm" src="https://user-images.githubusercontent.com/1923178/29890653-5a651c6c-8d96-11e7-8783-c353e22cbdf6.png">

I think in most applications, the drop-down would behave as if it were outside the modal window.

**Comment by eatonphil** [comment]
Yep that's an "issue" right now. You can scroll down outside of the select in the meantime.
