### ISSUE TITLE
Logout Logic

### ISSUE THREAD

**Issue by illblew** [linode/manager#250]
Currently clicking "Logout" will kick you out and drop you to a 404. If you click "Linodes" after doing this you can add a Linode. This then causes an uncaught exception in session.js.

See below:

`session.js:9 Uncaught (in promise) TypeError: Cannot convert undefined or null to object(…)o @ session.js:9i @ fetch.js:18(anonymous function) @ fetch.js:47`

**Comment by illblew** [comment]
To be clear, adding the Linode fails.

**Comment by eatonphil** [comment]
Closed by #158
