### ISSUE TITLE
Editing RDNS for IPv6 duplicates the address entry

### ISSUE THREAD

**Issue by da2x** [linode/manager#2503]
After clicking Save in the Edit RDNS dialog, a the address is duplicated and is displayed with an extra “/ 64” prefix. The entered RDNS address isn’t displayed on the page.

Reloading the page removes the extra entry and displays the RDNS address in the UI as expected. Seems like it works beside the entry duplication in the UI.

![rdns-duplication](https://user-images.githubusercontent.com/1102886/30135226-55b48c4c-935a-11e7-8be2-e8b8c16ac4d6.png)

**Comment by eatonphil** [comment]
Nice catch. Thank you!
