### ISSUE TITLE
Clone a Linode option is missing

### ISSUE THREAD

**Issue by mallorn** [linode/manager#2509]
The classic Linode manager has a 'clone' option for each individual Linode that creates a copy of the Linode on another host.  The Linode cloud manager does not have that option.

**Comment by displague** [comment]
The clone option is currently available on the Linodes dashboard.

![image](https://user-images.githubusercontent.com/317653/30329224-aeb99492-979f-11e7-8ec9-0f5d349b8113.png)

![image](https://user-images.githubusercontent.com/317653/30329242-bc4820ba-979f-11e7-8b43-d2002c5ce531.png)
