### ISSUE TITLE
Implement enable backups on create page

### ISSUE THREAD

**Issue by RobertDeRose** [linode/manager#251]
![screen shot 2016-07-12 at 2 32 39 pm](https://cloud.githubusercontent.com/assets/388745/16778809/a3551c6e-483d-11e6-9442-12092311e646.png)

**Comment by eatonphil** [comment]
Yes, it does not enable backups yet. Thanks

**Comment by RobertDeRose** [comment]
Why not?

**Comment by SirCmpwn** [comment]
That's a link to /backups, where you can click the backups enable button (once we get that wired up). I think this is working as expected.

**Comment by RobertDeRose** [comment]
ok

**Comment by eatonphil** [comment]
Actually we can keep this open because the backups are not hooked up in the create linode flow.

**Comment by eatonphil** [comment]
(And there isn't another task yet)

**Comment by SirCmpwn** [comment]
Ah, I was misled by the screenshot.

**Comment by eatonphil** [comment]
To make things easier the API is being adjusted to accept a `{ backups: { enabled: true } }` option or similar on POST /linodes.

**Comment by displague** [comment]
I used the multi-create flow for 3 Linodes, and then 1 Linode, enabling backups each time.  This workflow didn't work for me - backups were not enabled.  

## At Creation
> ![image](https://cloud.githubusercontent.com/assets/317653/18347258/ab2a4a22-7592-11e6-8209-670779497196.png)

---

## Following Dashboard
> ![image](https://cloud.githubusercontent.com/assets/317653/18347305/da7eadcc-7592-11e6-931b-c55d5d31d2db.png)

**Comment by SirCmpwn** [comment]
The checkbox was added and wired up in advance of the API feature existing.
