### ISSUE TITLE
Random Generated Root Password, needs some work

### ISSUE THREAD

**Issue by RobertDeRose** [linode/manager#252]
So the idea of offering to generate a random root password for the customer is interesting, however, it doesn't recommend to the customer to save it so they can log in with it. One idea, you could use https://clipboardjs.com to copy it to their clipboard, but that's not the safest thing, or at least have a button to copy it.

At a minimum, you should make a nice bright alert warning them to write it down or copy it. Also is it OK that you are showing it in clear text? How about a password strength indicator as well?

I would also recommend not offering to generate root password for the user unless they have an SSH  key added. Not really sure about the feature all together really

**Comment by SirCmpwn** [comment]
>At a minimum, you should make a nice bright alert warning them to write it down or copy it. Also is it OK that you are showing it in clear text? How about a password strength indicator as well?

:+1: 

>I would also recommend not offering to generate root password for the user unless they have an SSH key added. Not really sure about the feature all together really

:-1: 

If they have an SSH key set up we should not even tell them what the pw is, and just generate a secure one (or better yet set up the rest of the stack to passwd -d it and disable PasswordAuthentication in the sshd config).

**Comment by RobertDeRose** [comment]
Yeah, sure, I'm all in favor of ssh key only option.

**Comment by eatonphil** [comment]
> How about a password strength indicator as well?

#233  @RobertDeRose
