### ISSUE TITLE
"Oh no! This page is broken." because `g5-standard-3-s` is not a valid Linode type

### ISSUE THREAD

**Issue by infinitewarp** [linode/manager#2522]
Using the "new" Linode Manager on cloud.linode.com, I get an "Oh no!" error when loading my account dashboard page (https://cloud.linode.com/linodes/myaccountname).

It seems to be broken "out of the box" for my account regardless of which browser I use. Broken in Chrome (latest version) and Firefox (latest version) in regular and private/incognito modes with any ad/nuisance blockers disabled that might be intercepting requests.

### Steps to reproduce: 
1. Go to cloud.linode.com
2. Log in.
3. Click account name to go to my dashboard.
4. Watch page load and then immediately overlaid with an error alert. See screenshots below.
5. Can't do anything other than reload the page and see the same error.

### Probable cause:
It looks like the cause is a 400 Bad Request coming back from Linode's servers for `GET https://cloud.linode.com/api/v4/linode/types/g5-standard-3-s`. When I access that URL manually, I get the following response:

```{"errors": [{"reason": "This is not a valid Linode type"}]}```

I do have a relatively _old_ Linode account that has gone through numerous migrations over the years. I guess your new backend doesn't recognize my account type.

### Screenshots:
![network inspector](https://i.imgur.com/WhNURtU.png)
![javascript console](https://i.imgur.com/qzkVSlx.png)

**Comment by jamesottinger** [comment]
We just updated our backend to address this issue. It should now be resolved for you.

Thank you @infinitewarp for taking the time to report this and for providing such detailed information!

**Comment by jamesottinger** [comment]
I'm marking this as resolved. Let us know if you run into any other issues.
