### ISSUE TITLE
Find place for delete and add delete confirmation modal

### ISSUE THREAD

**Issue by RobertDeRose** [linode/manager#253]
Deleting a linode does not seem intuitive and seems like you could accidentally delete a bunch of linodes by accident as there is no confirmation when you click delete from the drop down.  I think the destructive action warrants its own distinctive button, maybe a nice bright red "danger" button. 

Or at a minimum change the dropdown to a button group with a separator and the delete button use the danger css

**Comment by eatonphil** [comment]
This is not permanent. There is not a set place for the delete button yet, but it probably won't be where it is now.

**Comment by inderpreetsingh** [comment]
What if I accidently delete a linode, is there any way to get back up?

**Comment by SirCmpwn** [comment]
The same deal as it is now, you'll be warned before you actually commit to it and if you do it anyway, you have a small window during which you can reach out to support and we can fix it for you.

**Comment by inderpreetsingh** [comment]
What is that window like? how much time?

**Comment by SirCmpwn** [comment]
It varies, I'm not sure. That decision doesn't lie with the manager team, though.

**Comment by inderpreetsingh** [comment]
Okay, thanks for the help. I really appreciate it. I hope I can get back the linode I lost.

**Comment by SirCmpwn** [comment]
If you lost a Linode in production, reach out to support immediately. If you lost a Linode in the alpha, you'll just have to live with it being gone.

**Comment by eatonphil** [comment]
We'll be going forward with this by adding a delete action to the Linode action dropdown. See https://github.com/linode/manager/issues/582

**Comment by inderpreetsingh** [comment]
Thanks for the support :)
