### ISSUE TITLE
Tooltip issues in ZonePage (Minor UI Issue)

### ISSUE THREAD

**Issue by roydondsouza** [linode/manager#2536]
**Affected Page:**

- Source: https://github.com/linode/manager/blob/v0.13.0/src/domains/layouts/ZonePage.js
- Version: v0.13.0
- Page Link: https://cloud.linode.com/domains/<your_domain_name>

**Steps to reproduce:**
- Login to https://login.linode.com/login
- Go to "Domains" page

![linodeissue](https://user-images.githubusercontent.com/8610709/30344327-7900eb46-981e-11e7-9716-06c44b156df8.jpg)

- Click on your domain
- In NS Records, the tooltip shows the last items' contents.
- I checked the code, the issue is that tooltips for all items open at the hover event and the last tooltip stays on the top.

![vohasyyh5t](https://user-images.githubusercontent.com/8610709/30343938-ddfa8fd6-981c-11e7-8f92-d2a6a07d513f.gif)

**Comment by eatonphil** [comment]
Awesome. Thanks for the great report!
