### ISSUE TITLE
Vertical scrollbar appears when notification menu is opened

### ISSUE THREAD

**Issue by multiwebinc** [linode/manager#2540]
I would have submitted a pull request, but I don't know SCSS at all.

`.NotificationList--open` needs something similar to `height: calc(100% - 83px);` where 83px is the value calculated for `top`.

**Comment by eatonphil** [comment]
Thanks! Could you submit a screenshot illustrating the issue?

**Comment by multiwebinc** [comment]
@eatonphil Sure:

![screenshot_2017-09-14_16-22-28](https://user-images.githubusercontent.com/901732/30458485-0836d92e-9969-11e7-9489-22fb848a8c4c.png)
![screenshot_2017-09-14_16-22-44](https://user-images.githubusercontent.com/901732/30458486-083b176e-9969-11e7-943a-8dc834d689d2.png)
