### ISSUE TITLE
Login app incorrectly calls CSRF-related timeouts "403"

### ISSUE THREAD

**Issue by bdube** [linode/manager#2559]
When a session times out, logging back in using the form that is presented after timeout causes a 403 error.

**Comment by bdube** [comment]
This worked correctly for me today.

**Comment by bdube** [comment]
403 again...

**Comment by eatonphil** [comment]
This is a matter of CSRF validation and it is not strictly-speaking a Manager issue. This is in our Login app. The actual issue is that Login calls it a 403 and doesn't call it a CSRF-related timeout.

**Comment by sharkgit** [comment]
If I visit the sign in page and leave it open for "a while," would I get the same response I'm seeing or a successful sign in? Regardless of the cause, I think the behavior in the two scenarios should be consistent.

**Comment by bdube** [comment]
If I visit the sign in page and leave it open for "a while," would I get the same response I'm seeing or a successful sign in? Regardless of the cause, I think the behavior in the two scenarios should be consistent.

**Comment by bdube** [comment]
It's still dumb that having the sign in page open for a while before using it means it's not going to work. And that still happens regularly.
