### ISSUE TITLE
Backup schedule time Select isn't rendering the proper backup windows.

### ISSUE THREAD

**Issue by na3d** [linode/manager#2563]
There are inconsistencies between backup schedule between managers.

**Comment by howdiz** [comment]
@na3d can you please update this title to be more specific. The description could probably be clearer too. Thanks.

**Comment by na3d** [comment]
![Screen Shot 2017-11-16 at 1.29.45 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/574f1638af85550e005e0ae3/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b76226455f56b7191a379f110224f5b5a5ecc3c4a4356bcbbd671f3e57862804e0eead53b5e73946c47faea8219ec57bb208f4c87e7bb8c19d2f42f67b6d5db1063474f4dcbed5727a19041c95df74be94852a411306ae7772431.png)
![Screen Shot 2017-11-16 at 1.30.01 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/574f1638af85550e005e0ae3/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b76226455f56b7191a379f1112b4f5f5e5ecc3c4a4356bcbbd671f3e57862804e0eead53b5e73946c47faea8219ec57bb208f4c87e7bb8c19d2f42f67b6d5db1063474f4dcbed5727a19e41c95df74be94852a411306ae6742431.png)

**Comment by howdiz** [comment]
@na3d can you please update this title to be more specific. The description could probably be clearer too. Thanks.

**Comment by howdiz** [comment]
@rjstires passing to @na3d for clarification.

**Comment by na3d** [comment]
As the screenshots show above, the Backup Window/Time of Day for scheduling backups do not match.    In EST, Time of Day should be 1AM-3AM if it was rendering properly.

Side Note:
Rob and I plan on working on this together so we can go over the code in more detail.

**Comment by na3d** [comment]
[Pending API Fix]

**Comment by na3d** [comment]
Windows are based on GMT-1
