### ISSUE TITLE
Nothing renders in safari private mode

### ISSUE THREAD

**Issue by na3d** [linode/manager#2574]

**Comment by eatonphil** [comment]
This is because calls to localstorage fail -- Safari incognito disables
localstorage. We can wrap them in try-catch to prevent the crash. But
they'll be grabbing a new oauth token each time so their sessions will end
up being 45 minutes (based on login) not 2 hours (like normal).

**Comment by na3d** [comment]
Could throw up a message about that in that case, no?

**Comment by eatonphil** [comment]
Not a page-render-stopping message. But we could put up a small exitable
banner or something so that they can keep using it anyway.
