### ISSUE TITLE
CoreOS not listed in Linode create or rebuild, dashboard shows name as Unknown

### ISSUE THREAD

**Issue by sixcorners** [linode/manager#2576]
It doesn't show CoreOS Container Linux as a distribution choice on the rebuild page. The API does return it as an option. If CoreOS is the current distribution then it shows the current as "Unknown".
Also there doesn't seem to be a way to specify disk sizes like the classic linode manager but I don't really know what that setting is for.

**Comment by eatonphil** [comment]
Thanks! To fix these we'll need to add coreos to the DISTRIBUTION_DISPLAY_ORDER in src/constants and we'll have to find an icon for it as well.

**Comment by eatonphil** [comment]
I am not sure why the name shows up as unknown though.
