### ISSUE TITLE
Longview Client Overview (Dashboard)

### ISSUE THREAD

**Issue by na3d** [linode/manager#2595]
![longview.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/57598fa56b48630e00666b1b/125516c66e82c728ace21e0d46e49b9424948aac98abf301b44fff9e2c4533317346f67c2483b27fbd437d070d5f48ff17595f40fffbd82ca0e32e6c981e5ab38532022d8c6853beb2901eb80bbb258b4885b3b98c4fc1ee3b2cf5c6.png)

**Comment by displague** [comment]
https://github.com/linode/manager/pull/2633 includes the top processes, a CPU and Network graph.  There are still a number of problems with these graphs in this PR.
