### ISSUE TITLE
Implement Linode networking reverse DNS entry

### ISSUE THREAD

**Issue by eatonphil** [linode/manager#262]

**Comment by eatonphil** [comment]
![screen shot 2016-07-13 at 12 09 19 pm](https://cloud.githubusercontent.com/assets/3925912/16810638/ab6cb640-48f2-11e6-9c78-e77ef2d2f16e.png)

**Comment by na3d** [comment]
It looks odd having Addresses: hanging out like that.  Would moving Addresses and everything to the right be acceptable?  Clearly that table has a lot of unused space.
