### ISSUE TITLE
"Oh no! This page is broken." when volume events are present

### ISSUE THREAD

**Issue by Dorthu** [linode/manager#2621]
<img width="685" alt="screen shot 2017-10-07 at 2 49 30 pm" src="https://user-images.githubusercontent.com/7172953/31310910-d7afba92-ab6e-11e7-94b5-850e75f20033.png">

I believe this is related to the recent [change to Event actions](https://developers.linode.com/v4/changelogs)

**Comment by eatonphil** [comment]
What version of the Manager were you on? This was fixed in 14.2.

**Comment by eatonphil** [comment]
Should be fixed.
