### ISSUE TITLE
add support for CAA records

### ISSUE THREAD

**Issue by displague** [linode/manager#2626]

**Comment by na3d** [comment]
Domain Record Type

**Comment by na3d** [comment]
<img width="970" alt="screen shot 2017-11-16 at 1 22 32 pm" src="https://user-images.githubusercontent.com/6047142/32908338-3f6a2e7a-cad1-11e7-86bc-42764eb96350.png">
<img width="986" alt="screen shot 2017-11-16 at 1 21 50 pm" src="https://user-images.githubusercontent.com/6047142/32908339-3f77a65e-cad1-11e7-8ec7-14f22901b806.png">

**Comment by rjstires** [comment]
Blocked by: https://jira.linode.com/browse/MR-174
