### ISSUE TITLE
Deleted Linodes persist on Linode Index page

### ISSUE THREAD

**Issue by na3d** [linode/manager#265]
On the index page, delete a Linode.
Then click add Linode, and create a new Linode.
Then go back to the Linode index page.

The deleted Linode is still displayed

**Comment by eatonphil** [comment]
It is in the process of being deleted, so after a few seconds it will in fact disappear. But yeah this is a bug. If the state of the linode is "deleting" or something like that, it should not be shown.

**Comment by SirCmpwn** [comment]
Unable to reproduce.

**Comment by eatonphil** [comment]
I am able to produce it the same way @na3d mentioned. Hard refreshing gets rid of it though.

**Comment by SirCmpwn** [comment]
No dice, tried three times.

**Comment by SirCmpwn** [comment]
Is this still a problem?
