### ISSUE TITLE
Selecting an expiry date of never on a Personal Access token doesn't work

### ISSUE THREAD

**Issue by abemassry** [linode/manager#2651]
![pasted image at 2017_10_19 09_54 am](https://user-images.githubusercontent.com/1616275/31893523-c5c47cb0-b7d9-11e7-81d9-f0e808153c59.png)

```
{label: "asdfaddf", scopes: "", expiry: "2017-10-19T15:10:49"}
expiry
:
"2017-10-19T15:10:49"
label
:
"asdfaddf"
scopes
:
""
```

the request payload makes it look like a manager issue

**Comment by stephenyeargin** [comment]
Relevant block of code:

https://github.com/linode/manager/blob/601c1c5132b5b27cc57dc9739258a4a231789586/src/profile/components/SelectExpiration.js#L8-L33

Perhaps 'never' should be handled more akin to:

https://github.com/linode/manager/blob/601c1c5132b5b27cc57dc9739258a4a231789586/src/components/TimeDisplay.js#L12-L13
