### ISSUE TITLE
Upgrade to React 16

### ISSUE THREAD

**Issue by displague** [linode/manager#2690]
This builds off of #2676 

React 16 provides fibers, which should offer performance updates to our app, error boundaries, and a smaller footprint:
- https://edgecoders.com/react-16-features-and-fiber-explanation-e779544bb1b7
- https://reactjs.org/blog/2017/09/26/react-v16.0.html
- https://medium.com/netscape/whats-new-in-react-16-1608390ffe39

I took a stab at this but found that some of our external components have not been updated for React 16:
- https://github.com/akiran/react-highlight/pull/43
- https://github.com/HubSpot/react-select-plus/issues/94
- a few others

We should pursue those PRs (some are very stale) or replace those components with more active alternatives.

**Comment by asauber** [comment]
Began working on this.

Working branches:
https://github.com/asauber/manager/tree/react-16-upgrade
https://github.com/asauber/linode-react-components/tree/react16-upgrade

Here are my notes so far:

Upgraded react-select-plus to 1.1.0

Removed react-highlight, replaced with <code> element (we weren’t using the highlighting for any syntax)

Added prop-types package to manager and linode-react-components
We already import PropTypes from ‘prop-types’, which must have resolved from a dependency
Some of our dependencies still refer to react.PropTypes (react-router 2 is one of them)

Our version of react-test-renderer depends on react-15
Upgraded to enzyme-adapter-react-16 and modified testSetup.js
