### ISSUE TITLE
Backup just created broken Last backup date in linode list

### ISSUE THREAD

**Issue by eatonphil** [linode/manager#270]
<img width="352" alt="screen shot 2016-07-14 at 12 48 48 pm" src="https://cloud.githubusercontent.com/assets/3925912/16847963/7693513e-49c1-11e6-9812-0bf693e96d1f.png">

**Comment by eatonphil** [comment]
Was going to label this a bug, but my branch was just behind. This still isn't too pretty.
<img width="327" alt="screen shot 2016-07-14 at 12 50 45 pm" src="https://cloud.githubusercontent.com/assets/3925912/16847995/a6f12644-49c1-11e6-89d2-f09a7a807d26.png">

**Comment by SirCmpwn** [comment]
Maybe ~14 hours would be better?

**Comment by eatonphil** [comment]
I like it.
