### ISSUE TITLE
show newly added images on the image list

### ISSUE THREAD

**Issue by displague** [linode/manager#2711]
Use the imagize response to add the image to redux.

Polling would also (eventually) correct the problem.  This page does not currently poll.

**Comment by bralski1** [comment]
From PO review: Image did  not appear in the list.

**Comment by displague** [comment]
The next API release may be moving `POST ...disks/123/imagize` to `POST images {diskid:123}`.   When that API change happens we may get this task for free.

It may be worth deferring this task.

**Comment by na3d** [comment]
Agreed with the deferment.

**Comment by displague** [comment]
But we should still poll the images, which gives us a useful workaround and something to act on now without duplicating effort.
