### ISSUE TITLE
split docs, components, and styleguide repos from manager

### ISSUE THREAD

**Issue by displague** [linode/manager#2718]

**Comment by howdiz** [comment]
This is high priority and will significantly streamline things for API team and Ops deployment workflow

**Comment by asauber** [comment]
I'll take this on

[ ] Create two new GitHub repos (docs, components)
[ ] Move code and push up initial commits
[ ] Yarn lock both docs and manager to a specific GitHub revision
[ ] Test local development of both docs and manager
[ ] Move and test tests for docs and manager
[ ] Set up CI for docs and manager
[ ] Add these repos to local dev environment
[ ] Modify build CI as needed
