### ISSUE TITLE
CSS is sometimes slow to load

### ISSUE THREAD

**Issue by iONinja** [linode/manager#2724]
Usually, when I first load the new manager, the CSS takes a few seconds to load.

Here is an example:
![Example](https://user-images.githubusercontent.com/20980384/32976807-57d161e2-cc73-11e7-822a-d0c6feaa10b7.png)

Any ideas why? How would it be fixed?

**Comment by displague** [comment]
I've seen this too.  The file it loads is:
https://login.linode.com/static/login.css which is currently about 150k.  This is fairly hefty considering the minimalistic style on that page, but I don't believe that is the problem.

If you encounter this with some frequency or predictability, could you clear browser cache and capture the output of the Networking console panel in your browser? (Ctrl (or Command on Mac) +Shift+I )

![image](https://user-images.githubusercontent.com/317653/32995178-f05ce2ee-cd3e-11e7-99d0-cb3cc60b28dc.png)
