### ISSUE TITLE
No feedback or notification when Linode boot fails

### ISSUE THREAD

**Issue by asauber** [linode/manager#2736]
If a Linode boot fails with the following error in a development environment, the only Notification that we receive is  "Linode #nnn Booted". The Linode stays in the Powered Off state.

The classic manager reports:
> Linode disk /dev/sda not ready to boot. Please contact support.

**Comment by displague** [comment]
This may be similar to creating a Direct Disk config and booting it on a Linode whose disk does not have an MBR.
