### ISSUE TITLE
Linode add/edit Config: Virtualization Mode and Run Level radio buttons don't work

### ISSUE THREAD

**Issue by asauber** [linode/manager#2741]

**Comment by na3d** [comment]
Both Virt Mode and Run Level clear all radios if you try to change the value, in Linode Config Add and Edit.
![Screen Shot 2017-11-28 at 9.21.44 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/574f1638af85550e005e0ae3/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b76226456fb6b7191a371f1102a4f5b5b5edd3c4a4356bcbbd671f3e57862804e0eead53b5e73946c47faea8219ec57bb208f4c87e7bb8c19d2f42f67b6d5db1063474f4dcbed5727a19141c95df74ae94a5dad123f6be4752431.png)
