### ISSUE TITLE
Linod Manager Breaks when loading "Users" Page

### ISSUE THREAD

**Issue by wpconsulate** [linode/manager#2762]
Please check this for reference: http://prntscr.com/hgo2fx

Details:
AJAX URL: https://cloud.linode.com/api/v4/account/users/?page=1
headers: 
![image](https://user-images.githubusercontent.com/266207/33363339-fc427cda-d505-11e7-8dc8-4387b7c0b4f0.png)

Fetch.js:8 -> Error in JS 
![image](https://user-images.githubusercontent.com/266207/33363386-2667cc18-d506-11e7-990f-47575450dce9.png)

**Comment by displague** [comment]
Thanks for reporting this.

I have confirmed that Restricted User accounts are receiving a 403 when accessing the /profile/users API endpoint, which should rather return the restricted users self.

I've filed an internal ticket - MR-177 to track this item.  I believe this is a recent bug introduced during the Grants refactor: https://developers.linode.com/v4/changelogs (2017-11-20)
