### ISSUE TITLE
Imagize modal form breaks if you swap choices in the Linode dropdown back and forth

### ISSUE THREAD

**Issue by asauber** [linode/manager#2771]
If you swap choices for "Linode" in the Imagize modal back and forth, eventually it gets into a bad state and the "Type" and "Size" fields disappear.

At this point you can't save the image.

Looks like this:
![Screen Shot 2017-11-29 at 6.55.52 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a0c757bdf7dac0013122aee/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b76226456fa6b7191a37ef1172e4f5a5d5ecc3c4a4356bcbbd671f3e57862804e0eead53b5e73946c47faea8219ec57bb208f4c87e7bb8c19d2f42f67b6d5db1063474f4dcbed5727a19041c95df74ae8445ca3153062e2752431.png)

**Comment by displague** [comment]
I've also witnessed this

**Comment by na3d** [comment]
How do you reproduce this?

**Comment by rjstires** [comment]
Closed by #2831

**Comment by asauber** [comment]
Confirmed fixed in #2831
