### ISSUE TITLE
An offline Linode goes into the "powering off" state upon rebuild

### ISSUE THREAD

**Issue by asauber** [linode/manager#2790]
An offline Linode shouldn't go into the "powering off" state upon a rebuild.
![Screen Shot 2017-11-30 at 3.13.02 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a0c757bdf7dac0013122aee/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b76226457f36b7191a37bf113284f5f5d5ecc3c4a4356bcbbd671f3e57862804e0eead53b5e73946c47faea8219ec57bb208f4c87e7bb8c19d2f42f67b6d5db1063474f4dcbed5727a29941c95df749e14a56a5123166ee772431.png)

**Comment by na3d** [comment]
Turns out the events were are polling switches it to powering off, and it looks like this was done on purpose, until the API side responded appropriately.
