### ISSUE TITLE
Docs - URL rendering doesn't handle :ids and sub-items on the first level :id

### ISSUE THREAD

**Issue by na3d** [linode/manager#2800]
If we have 2 endpoints:
/account/payments/:id
/account/payments/paypal

Observed Behavior:
If someone goes to the paypal URL, it renders the :id URL instead.

Expected Behavior:
Render the proper information for the paypal URL, instead of the :id URL.

Side Note
This is already handled in the for the second level of ids:
/linode/instances/$id/ips/$ip_address
/linode/instances/$id/ips/sharing

[Ignore the above]

**Comment by na3d** [comment]
Switch : to $

**Comment by rjstires** [comment]
@na3d are we just doing a blanket replace of  : with $  throughout all of the YAMLs?
