### ISSUE TITLE
Host Job Queue in Dashboard

### ISSUE THREAD

**Issue by s4l3h1** [linode/manager#2802]
There is no such thing like Host Job Queue in basic manager,
"manager/src/linodes/linode/layouts/DashboardPage.js"

**Comment by displague** [comment]
The Host Job Queue has been replaced with an Events feed.

The API for this feed is available at https://developers.linode.com/v4/reference/endpoints/account/events

Some of the detail of the Host Job queue is no longer available.  However, Events are a promising alternative that reveals account wide actions, not limited to an individual Linode's host jobs, all within in a single feed.

In the new manager interface, events appear in the top right corner.  

![image](https://user-images.githubusercontent.com/317653/33558018-dee8bbca-d8d6-11e7-8adf-4940a6fbcc56.png)

**Comment by displague** [comment]
Feel free to reopen this or reply -- I closed this for housekeeping.
