### ISSUE TITLE
Show steps completed in create a linode flow

### ISSUE THREAD

**Issue by eatonphil** [linode/manager#281]
Show in the top right section in line with the title once the section has been completed. (Also include the total or to go or something.)

**Comment by SirCmpwn** [comment]
Mockup wanted

**Comment by eatonphil** [comment]
![screen shot 2016-07-25 at 11 39 44 am](https://cloud.githubusercontent.com/assets/3925912/17107280/8e753a3a-525c-11e6-886c-f90134dc0f47.png)

**Comment by na3d** [comment]
So what would it look like with Provision with StackScripts unchecked?

**Comment by eatonphil** [comment]
The second card would not exist and it would be Step 1 of 4.

**Comment by na3d** [comment]
ok :+1:

**Comment by SirCmpwn** [comment]
I don't really dig this tbh. I don't have much constructive feedback. I would prefer if this UI wasn't included at all.

**Comment by eatonphil** [comment]
The reason this started was because of a request by some users that we give an indication of how far along they are. I don't really feel strongly either way.

**Comment by SirCmpwn** [comment]
It's a pretty short flow. Scrolling down is enough to see what's left. Doesn't sound that important imo.

**Comment by eatonphil** [comment]
Will shelve for now.

**Comment by SirCmpwn** [comment]
Bumping for further discussion

**Comment by na3d** [comment]
Adding create linodes label to see if we can close.

**Comment by eatonphil** [comment]
Closed by #1045
