### ISSUE TITLE
Editing settings for multiple nodes/balancers simultaneously

### ISSUE THREAD

**Issue by birdie-github** [linode/manager#287]
It would be nice if Linode manager could allow to select multiple nodes/balancers (also filtering for that would be nice by e.g. name, tariff, other features) and change their settings as a whole (e.g. e-mail notification settings, tariff, etc.).

For customers who have dozens/hundreds of servers modifying settings for multiple servers becomes an extremely tedious task prone to major problems.

Thank you!

**Comment by SirCmpwn** [comment]
Hmm, I'm not sure how common this is. Wouldn't this use-case be better served by a script that talks to the API?

**Comment by birdie-github** [comment]
So in order to manage multiple nodes simultaneously I have to read your documentation and write some code?

**Comment by SirCmpwn** [comment]
Presumably a bash one-liner with the Linode command line tool would also do the trick.

**Comment by SirCmpwn** [comment]
I think once we have node balancer support up to the level it is in the current manager we can start to consider more niche features for it like this, but I can't make any promises. This'd be a good candidate for sending us a pull request if it's integral to your workflow and you need it sooner than we have the bandwidth to support it ourselves.

**Comment by mparke** [comment]
This is a neat idea, @birdie-github, will investigate options as we iterate on nodebalancers.

**Comment by rjstires** [comment]
re MAN2-287
