### ISSUE TITLE
Kernel dropdown doesn't have the 4.14 option

### ISSUE THREAD

**Issue by emersonveenstra** [linode/manager#2888]
In the Profile editor, the latest is still Latest 64 bit (4.9.68-x86_64-linode89), and there's no option for 4.14.2

**Comment by displague** [comment]
You should now see these kernels.  The caching involved with this is a little more aggressive than we would like, and we'll address that before the Manager rewrite and API are final.

![image](https://user-images.githubusercontent.com/317653/34743030-4b1a4ba6-f556-11e7-8a52-bfa7416a0895.png)
