### ISSUE TITLE
Demonstrate when backups are not finished

### ISSUE THREAD

**Issue by eatonphil** [linode/manager#289]
Once a backup starts running, indicate this on its card so, for instance, the user can immediately see a backup starts running when they first click manual snapshot when no other backups exist.

**Comment by SirCmpwn** [comment]
How do we determine that a backup is running?

**Comment by eatonphil** [comment]
Once they hit the button show them something - that's the expected behavior.

**Comment by SirCmpwn** [comment]
when in progress render something cool in the card such as the text literal "backup in progress" or a picture of @na3d's mom.

**Comment by na3d** [comment]
Discovered a browser caching issue that needs to be resolved before we will be able to complete this task.

**Comment by na3d** [comment]
API does not return snapshot or backup status inside the Linode object currently.  This will be fixed in the future.  Currently have to fetch the backups.
