### ISSUE TITLE
Unknown prop `focus` on <li> tag.

### ISSUE THREAD

**Issue by eatonphil** [linode/manager#290]
Go to any page with tabs: /linodes or /linodes/create.

![screen shot 2016-07-18 at 11 18 00 am](https://cloud.githubusercontent.com/assets/3925912/16919886/627c212e-4cd9-11e6-9e4d-19b5e97f206c.png)

**Comment by SirCmpwn** [comment]
Will be automagically fixed when the next release of react-tabs drops.

**Comment by eatonphil** [comment]
Awesome.

**Comment by eatonphil** [comment]
Closed by 6b1c1b7c21abb5b36c8f2a5cdc3dedf969fbef8d
