### ISSUE TITLE
Linode says first backup in ~x hours even after manual backup

### ISSUE THREAD

**Issue by eatonphil** [linode/manager#291]
If you take a manual backup before the first scheduled backup occurred, the UI says the "first" backup is in ~x hours. If we want to ignore the manual backup here, we should clarify in the wording (include "auto" or "scheduled"). If not, we should include the manual backup in the calculation for the UI.

**Comment by SirCmpwn** [comment]
Sounds like an API issue. It should be setting linode.backups.last_backup for us.

**Comment by Dorthu** [comment]
Looking into this now..

**Comment by Dorthu** [comment]
Looks like @eatonphil is right - the backups.last_backup field intentionally shows only automatic backups, snapshots are handled separately.  This is not an API issue.

**Comment by SirCmpwn** [comment]
Well can you intentionally make it behave differently?

**Comment by Dorthu** [comment]
Opened an item for discussion, but I think a more likely outcome is updating our docs to make the distinction more clear.

**Comment by eatonphil** [comment]
I think we're good to close this now? @SirCmpwn

**Comment by eatonphil** [comment]
We're going to replace previous and upcoming backups with a simple notice that backups are enabled due to the extra cost in looking up more backup information.
