### ISSUE TITLE
says "You have a host migration scheduled for this Linode!" but I don't have one scheduled

### ISSUE THREAD

**Issue by collinanderson** [linode/manager#3024]

**Comment by asauber** [comment]
Hi Collin, thanks for bringing the lack of detail in this messaging to our attention.

You should see some more detail about this migration if you view the page for this Linode in the classic manager. Let me know if you have any further questions upon doing so.

**Comment by collinanderson** [comment]
Linode classic doesn't show anything about a migration. (The issue is it's saying I have migration scheduled when I don't have one scheduled.)

**Comment by asauber** [comment]
I see what you mean. If you have a chance, please email support@linode.com and link to this issue so that we can look into what may be triggering this notification in your specific instance.

Thanks again for bringing this to our attention.

**Comment by collinanderson** [comment]
Ok, just emailed. Feel free to close this issue. Thanks!
