### ISSUE TITLE
External Links in the footer broken

### ISSUE THREAD

**Issue by roydondsouza** [linode/manager#3086]
**Please Note:** Contributing guidelines tells us not to report links that leads to 404s as this project is a work in progress. In my defence, this was a working feature before, and this helps in locating source pages for new contributors. Details of the issue below. 

**Affected Page:**

- Version: v0.18.5
- Page Link: https://cloud.linode.com/linodes (+ All pages)

**Steps to reproduce:**

- Login to https://login.linode.com/login
- Go to "Linodes" page
- Click on "Page Source" in the footer  
<img width="122" alt="screen shot 2018-03-27 at 1 12 55 am" src="https://user-images.githubusercontent.com/8610709/37928910-0fb69370-315c-11e8-926e-4cf9f192181d.png">

- Target URL = https://github.com/linode/manager/blob/v0.18.5/undefined

- Screenshot:

<img width="1272" alt="screen shot 2018-03-27 at 12 41 13 am2222" src="https://user-images.githubusercontent.com/8610709/37929550-ee5409ae-315d-11e8-8567-8a0afe3821f9.png">

**Comment by displague** [comment]
Thanks for the report, Roydon!

Unfortunately this issue will not be prioritized as we work to release the [develop](https://github.com/linode/manager/tree/develop) branch, which no longer includes this feature.

We do not have a live preview of this available, and it is still very rough, but it is possible to run it locally.
 
> ![image](https://user-images.githubusercontent.com/317653/37931420-8ba2321c-3113-11e8-9768-a1f5822e8e8b.png)

**Comment by roydondsouza** [comment]
Yes, I have this set up locally, I was surprised to see the new UI changes. Thanks for the update. 
Any place where we can find the present place/roadmap to these features?

**Comment by roydondsouza** [comment]
Is this a complete rewrite @displague, I see TypeScript everywhere now :) While you are at it; do I also assume the linode-react-components will also be rewritten?

**Comment by displague** [comment]
It's not a complete rewrite, @roydondsouza.

The logic from cloud.linode.com will be reused where ever possible.  

As you noticed, the project has gone through a number of recent, rapid, evolutions.  TypeScript is in, and Redux may be out.  linode-react-components is in limbo as the project has begun using material-ui.

We've moved the ticket tracking to an internal process, so I can't offer anything in terms of a public roadmap / timeline.

@asauber and @rjstires could probably say more.
