### ISSUE TITLE
Implement Linode detail general tab

### ISSUE THREAD

**Issue by SirCmpwn** [linode/manager#31]

**Comment by eatonphil** [comment]
![screen shot 2016-06-01 at 2 52 04 pm](https://cloud.githubusercontent.com/assets/3925912/15721771/6fef879c-2808-11e6-9bad-87ddb4dd2de2.png)

**Comment by eatonphil** [comment]
![screen shot 2016-06-07 at 10 22 51 am](https://cloud.githubusercontent.com/assets/3925912/15861191/d1816328-2c99-11e6-9b83-5b6e0cdbcd9b.png)

**Comment by eatonphil** [comment]
![screen shot 2016-06-07 at 1 18 14 pm](https://cloud.githubusercontent.com/assets/3925912/15867675/5addd88c-2cb2-11e6-9693-2628645dd6d9.png)
