### ISSUE TITLE
Reset root password

### ISSUE THREAD

**Issue by SirCmpwn** [linode/manager#322]

**Comment by eatonphil** [comment]
1. If you have only 1 disk (not swap), show password with generate field and strength meter and a button to do the thingy
2. Otherwise if multiple disks, dropdown to pick the disk to use and rest of ui

**Comment by SirCmpwn** [comment]
![](https://cloud.githubusercontent.com/assets/3925912/15721565/8fd6e0b0-2807-11e6-9511-12d7d40174c8.png)
