### ISSUE TITLE
Implement booting to rescue mode

### ISSUE THREAD

**Issue by SirCmpwn** [linode/manager#33]
Mockups outdated

**Comment by eatonphil** [comment]
![screen shot 2016-06-01 at 2 45 23 pm](https://cloud.githubusercontent.com/assets/3925912/15721552/8030809e-2807-11e6-81a4-2594b110adec.png)

![screen shot 2016-06-01 at 2 45 42 pm](https://cloud.githubusercontent.com/assets/3925912/15721565/8fd6e0b0-2807-11e6-9511-12d7d40174c8.png)

**Comment by eatonphil** [comment]
<img width="1195" alt="screen shot 2016-07-20 at 4 59 25 pm" src="https://cloud.githubusercontent.com/assets/3925912/17002866/6884e93e-4e9b-11e6-82a1-cc78e1968817.png">
![Uploading Screen Shot 2016-07-20 at 4.59.33 PM.png…]()
