### ISSUE TITLE
Show backup boxes and predicted schedule on backups page when backup in slot does not exist

### ISSUE THREAD

**Issue by eatonphil** [linode/manager#335]

**Comment by eatonphil** [comment]
Also, add a blurb below the "Restore" title such as "Select a backup to restore from:"

**Comment by SirCmpwn** [comment]
* [ ] Remove snapshot section
* [ ] Change text in empty snapshot box to "You haven't taken any snapshots yet"
* [ ] Add "Take snapshot" button next to the restore backup button, use outline class
* [ ] When clicking "Take snapshot", if you already have a snapshot, a modal should appear explaining that it'll be overwritten and asking them to confirm their choice
