### ISSUE TITLE
Implement Linode detail networking tab (view only)

### ISSUE THREAD

**Issue by SirCmpwn** [linode/manager#34]
This only entails viewing the information here. Note that feedback from @caker suggests we do not hide any IPs but instead just show the full list at all times.

**Comment by eatonphil** [comment]
![screen shot 2016-06-01 at 2 43 14 pm](https://cloud.githubusercontent.com/assets/3925912/15721490/34c37c42-2807-11e6-8528-3396c8d6362a.png)

![screen shot 2016-06-01 at 2 43 34 pm](https://cloud.githubusercontent.com/assets/3925912/15721496/3ee7dfe2-2807-11e6-9cfd-fc58be61556c.png)

![screen shot 2016-06-01 at 2 43 52 pm](https://cloud.githubusercontent.com/assets/3925912/15721512/53f8851c-2807-11e6-8170-cd6f33a57eab.png)

**Comment by eatonphil** [comment]
![screen shot 2016-06-07 at 10 24 59 am](https://cloud.githubusercontent.com/assets/3925912/15861334/1cb145a2-2c9a-11e6-9d6e-60ea6181ad7b.png)

**Comment by eatonphil** [comment]
Updated screenshot:
![screen shot 2016-06-16 at 4 58 17 pm](https://cloud.githubusercontent.com/assets/3925912/16132981/95dbdadc-33e3-11e6-933d-78a71c0c9117.png)
