### ISSUE TITLE
Maximum size for create volume input

### ISSUE THREAD

**Issue by roydondsouza** [linode/manager#3437]
Hi there,

I am aware this is a work in progress, just thought I should get it to your attention. In volume creation, we must define a maximum size for the input. I didn't hit the API on production to avoid causing any issues. 

![Screencast](http://g.recordit.co/XyLkJd7Pkb.gif)

**Comment by rjstires** [comment]
Hi @roydondsouza! Thank you for the heads up, I made sure to capture that on our internal bug tracker. I'll leave this issue open until it's been resolved.

Thank you again!

**Comment by patthiel** [comment]
Closing, as this has been addressed by https://github.com/linode/manager/pull/3646 . Thanks for the feedback @roydondsouza !
