### ISSUE TITLE
Warn users when they navigate away from unsaved changes

### ISSUE THREAD

**Issue by SirCmpwn** [linode/manager#361]

**Comment by eatonphil** [comment]
+1

**Comment by SirCmpwn** [comment]
Not sure that react-router is sophisticated enough to handle this situation correctly. I will file the appropriate bugs with react-router soon but for now I'm going to tank this issue.

**Comment by eatonphil** [comment]
Ah. That's unfortunate. But not super necessary immediately.

**Comment by mparke** [comment]
Look at react-router options, look at window.onunload handling

**Comment by rjstires** [comment]
MAN2-361
