### ISSUE TITLE
Block volumes not listed in Advanced Configurations

### ISSUE THREAD

**Issue by andysh-uk** [linode/manager#3821]
When editing the Advanced Configuration for a Linode, block volumes are not listed in the disk assignment dropdowns (/dev/sda, /dev/sdb etc.)

This leaves a blank item which cannot be saved, and I have to resort to the old manager to do so.

The disk containing my block volume is empty (other dropdowns with no disk assigned show as "None"):

<img width="441" alt="screen shot 2018-09-11 at 21 37 47" src="https://user-images.githubusercontent.com/12907944/45386331-05066200-b60b-11e8-9e81-542bdc0e582b.png">

No volumes are populated in the dropdown:

<img width="446" alt="screen shot 2018-09-11 at 21 37 52" src="https://user-images.githubusercontent.com/12907944/45386358-164f6e80-b60b-11e8-89ee-1394c0fd76ef.png">

Other disk assignment dropdowns, such as on the Rescue page, show the volume fine:

<img width="435" alt="screen shot 2018-09-11 at 21 38 06" src="https://user-images.githubusercontent.com/12907944/45386370-1f404000-b60b-11e8-9247-17cc1cb50f11.png">

**Comment by rjstires** [comment]
Thank you for this feedback, we've created a ticket internally to track progress. I will update when this issue is resolved.

**Comment by rjstires** [comment]
A quick update on this; the issue has been resolved on an internal build and should be released Oct 7th.

**Comment by patthiel** [comment]
Confirming this has indeed fixed in the cloud manager @andysh-uk.  Thanks for filing the issue!
