### ISSUE TITLE
Ability to clear linode history.

### ISSUE THREAD

**Issue by b350** [linode/manager#3894]
Please add it, cause it contains a lot of unnecessary information, like when old currently **deleted** linode was created rebooted etc... or make the activity display only for the last 30 days.

Thanks.

![history](https://user-images.githubusercontent.com/43731239/46262249-55d0f280-c507-11e8-82ce-e4079d6f36c6.JPG)

**Comment by rjstires** [comment]
Thank you for your feedback @b350. We will continue to iterate over the design and information made available through the User Events Menu.
