### ISSUE TITLE
Cache latest blog title and link

### ISSUE THREAD

**Issue by eatonphil** [linode/manager#393]
Login makes one for all users every 6 hours. Manager might not be able to do that exactly but it can do a bit better than just caching in this.state.

**Comment by SirCmpwn** [comment]
Can cache it in localStorage with an expiration time.

**Comment by eatonphil** [comment]
It would be weird if it cached it inconsistently with login... something to think about

**Comment by SirCmpwn** [comment]
I'm not particularly concerned about that.

**Comment by na3d** [comment]
Feature removed.
