### ISSUE TITLE
Multiple uses of applyMiddleware is not recommended

### ISSUE THREAD

**Issue by markerikson** [linode/manager#397]
The current version of `store/index.js` uses `applyMiddleware` twice:
```js
const createStoreWithMiddleware = compose(
  applyMiddleware(thunk),
  applyMiddleware(routerMiddleware(browserHistory)),
  DevTools.instrument()
)(createStore);
```

There really shouldn't be any reason to use two separate instances of the middleware enhancer.  You should be able to do `applyMiddleware(thunk, routerMiddleware(browserHistory) )`.  See https://github.com/reactjs/redux/issues/1051 for some discussion on this topic.

Also, as a side note: while the curried-ish syntax for setting up the enhancers works, that approach is now considered obsolete.  The current preferred usage for creating a store is:
```js
const composedEnhancers = compose(applyMiddleware(thunk), DevTools.instrument() );

const store = createStore(reducer, preloadedState, composedEnhancers);
```

**Comment by SirCmpwn** [comment]
Thanks! I opened #399 to address this.
