### ISSUE TITLE
Use one-word labels for buttons in modals (at least)

### ISSUE THREAD

**Issue by eatonphil** [linode/manager#412]
Buttons represent the final step of some sequence. (The sequence can be 1- or 10-steps long.) The context around the button should be sufficiently clear that at the point the user chooses to click the button, there need be only one thought in their mind - agree or disagree. If a button seems to need multiple words to clarify context, attempts should be made to refactor the UI to make the context clearer. Possible options include: clearer headers, clearer explanatory text. This should almost always be possible in modals where the button represents the entirety of the context at hand. This may be less possible in other contexts (such as headers and footers) where space is a constraint.

**Comment by SirCmpwn** [comment]
:-1: 

The eye is immediately drawn to buttons and away from walls of text. I think the text of the button should provide enough information for the user to make an informed decision to click them or not, without having to read the walls of text explaining the full implications of the button. Or at least enough information to give them a reason to read that wall of text. This is especially the case with dangerous red buttons which do a very good job at attacting the viewer's eye away from the warnings.

**Comment by eatonphil** [comment]
Walls of text is a pretty extreme side of this. Mostly, the context can be made clear by the header - which I'd argue is where the eye is actually drawn first to rather than buttons.

**Comment by SirCmpwn** [comment]
Oh no, the eye is most certainly drawn first to the big colorful buttons.

**Comment by SirCmpwn** [comment]
Tested with marques, first thing he saw was button

**Comment by eatonphil** [comment]
Then why even have a header?

**Comment by SirCmpwn** [comment]
Asthetics?

**Comment by eatonphil** [comment]
The header gives it context

**Comment by SirCmpwn** [comment]
What are we even arguing about at this point?

**Comment by eatonphil** [comment]
The point is, headers exist to give context. So they should be used to give context. Buttons do not need to give context so they can and should be short and leave the context-giving to other elements whose full job is to do so.

**Comment by na3d** [comment]
Headers only have a purpose a very small fraction of the time.  When people are using a product, they are focusing on the interactions, which is why buttons tend to have colors to indicate good, bad, and hey look at me.  People have been trained to ignore text content and everything else, and only look for the buttons.  So it is more important for the buttons to explain the best they can, so the user spends less time trying to figure out what is going on.

**Comment by eatonphil** [comment]
I think we should decide on a format for save/edit/delete buttons in particular because right now we are inconsistent between `${action} ${type}` and `${action}`. For instance, in the delete modals [here](https://github.com/linode/manager/pull/410) we use `${action} ${type}`. But in the profile edit section [here](https://github.com/linode/manager/pull/420), we just use `${action}`. I think we should be consistent. And I think we should go with `${action}`.

**Comment by SirCmpwn** [comment]
I don't think consistency is important here. Use whatever's correct for the kind of modal you're using. We can standardize where it makes sense, though, i.e. all save buttons should be "Save changes", all delete buttons should be "Delete ${type}", etc

**Comment by eatonphil** [comment]
Closed by #901.
