### ISSUE TITLE
Incorrect price information on Backups page

### ISSUE THREAD

**Issue by tkulick** [linode/manager#4125]
I was playing around on manager earlier tonight and went to enable Backups on one of my Linodes.  When the rate came up, it was listed as "$2.5".  This should be listed as $2.50 to follow standard USD currency.  Not a huge deal, but wanted to list it in here.

Page in question: https://cloud.linode.com/linodes/MYLINODE/backup

**Comment by rjstires** [comment]
Moved into internal bug tracking.
