### ISSUE TITLE
Clicking on an event for a deactivated/terminated service results in ungraceful error

### ISSUE THREAD

**Issue by tkulick** [linode/manager#4131]
I deactivated a Linode a few days ago while I was testing things, and I have two notifications from the event:
- Linode LINODE-NAME has been shut down.
- Linode LINODE-NAME has been deleted.

The deleted item is greyed out and cannot be clicked.  However, the shut down item is clickable.  When I click it, it takes me to a not found screen instead of a more graceful message "Linode has been deactivated" or something similar.  I would suggest putting in a graceful error message or greying out items that no longer can be referenced.

**Comment by rjstires** [comment]
Also resolved!
