### ISSUE TITLE
`${h1Content} - Linode Manager` title scheme

### ISSUE THREAD

**Issue by eatonphil** [linode/manager#419]
In the login service, the page `<title>` scheme has been to use the title of the page (indicated by the text within `<h1>` on the page) as the first part of the `<title>` followed by "- Linode Manager". This is a common scheme and has the benefit of showing the most important information first (rather than the less important "what site am I on"). We should use the same scheme in the Manager especially now that the two services are so integrated.

**Comment by na3d** [comment]
Absolutely, the favicon will take care of the what site am I on question.

**Comment by eatonphil** [comment]
Whoops, just realized the formatting was wonky. Hopefully this doesn't change the meaning on you guys.

**Comment by na3d** [comment]
Still good, definitely a fan of the idea.
