### ISSUE TITLE
historical backups and snapshots are displayed the same as ones that are interactable

### ISSUE THREAD

**Issue by na3d** [linode/manager#426]
For snapshots, the only one you can interact with is the most recent successful one.  Previous and pending/running/postProcessing snapshots can't be interacted with.

For backups, I believe we may display historical backups as well.  This needs to be double checked, and fix it if so.

![screen shot 2016-09-08 at 10 59 57 am](https://cloud.githubusercontent.com/assets/6047142/18354400/6cf93472-75b3-11e6-9471-323fd9f3a000.png)

**Comment by eatonphil** [comment]
This is being taken care of in @abemassry's #365

**Comment by eatonphil** [comment]
This issue is not relevant any more given #481
