### ISSUE TITLE
the snapshot <backup> bleeds outside of the page-card when window widths is low

### ISSUE THREAD

**Issue by na3d** [linode/manager#427]
![screen shot 2016-09-08 at 10 56 21 am](https://cloud.githubusercontent.com/assets/6047142/18354343/2ed5b8c8-75b3-11e6-8ac5-7f5a5bda32fc.png)

**Comment by eatonphil** [comment]
This is getting removed in @abemassry's #365

**Comment by eatonphil** [comment]
Actually, I'll let him close this one when it gets merged.

**Comment by eatonphil** [comment]
This is no longer relevant.
