### ISSUE TITLE
Cannot access lish/glish after hitting "Launch Console"

### ISSUE THREAD

**Issue by eatonphil** [linode/manager#4397]
Trying to use Lish/Glish and I get the following:

<img width="1367" alt="screen shot 2019-01-19 at 7 07 38 pm" src="https://user-images.githubusercontent.com/3925912/51433653-8c995880-1c1d-11e9-88e6-909596230a75.png">

The network tab shows the response as `{"errors": [{"reason": "remote_addr must be a valid ip address", "field": "remote_addr"}]}`.

So it looks like the request format is wrong and there's missing error handling.

**Comment by rjstires** [comment]
IPv6 users cannot access Lish tokens. There's an open PR for it and should be resolved soon(ish).

👋
