### ISSUE TITLE
Add private ip address button

### ISSUE THREAD

**Issue by eatonphil** [linode/manager#441]
Change current add private ip address button to actually say Add private IP address. Do the same for the public one.

**Comment by na3d** [comment]
Do we want this to say Add private address, Add private IP, or Add private IP address?

**Comment by eatonphil** [comment]
Add private IP address

**Comment by na3d** [comment]
That seems a bit long, do we have precedent where we have done something similar somewhere?

**Comment by eatonphil** [comment]
I don't think there is another button yet that has four words on it... but personally I'm not worried about it. We wanted to be more precise about what the button was here.
