### ISSUE TITLE
Can edit unallocated or not in use disks while powered on

### ISSUE THREAD

**Issue by eatonphil** [linode/manager#448]

**Comment by SirCmpwn** [comment]
:-1: the complexity of this feature is huge

**Comment by SirCmpwn** [comment]
for little gain

**Comment by mparke** [comment]
@eatonphil is this still desired? what's the use case?

**Comment by eatonphil** [comment]
The CF manager allows you to edit any disks that are not in use. The current v4 API does not support this. It would need to tell us if the disk is in use or it would need to tell us what config is in use so we could look up the config and see which disks are associated with it. All other disks would be fine to be resized.

**Comment by rjstires** [comment]
MAN2-448
