### ISSUE TITLE
"Group by tag" isn't saved in the context of Domains

### ISSUE THREAD

**Issue by AlexMax** [linode/manager#4492]
On the Linodes page, if I click "Group by Tag:", the setting is still set if I navigate away from the page and then back to it.  On the other hand, doing the same thing with Domains doesn't work, as the page forgets about the setting if I navigate away.

I haven't exhaustively tested the entire site for this, but it seems like the sort of setting one would want saved in any case.

**Comment by martinmckenna** [comment]
Hey @AlexMax. Sorry for the late reply on this. We've just opened up a ticket in our tracking software, so this will definitely be resolved as soon as we can.

**Comment by martinmckenna** [comment]
Hey @AlexMax. This issue is fixed and will be deployed on Monday - look out for it on our changelog.
