### ISSUE TITLE
Sorting is backwards

### ISSUE THREAD

**Issue by rhoths** [linode/manager#4494]
This appears to be globally true on lists that are sortable, but I first encountered it on the Domains list. Loading the Domains page displays the list in reverse order by default. The header for "Domain" has a single triangular shape next to it that is narrow on top and wide on bottom indicating an ascending sort. Looking for further examples, the Linodes list appears to behave the same. This behavior is present with and without "Group by Tag" being enabled.

**Comment by rhoths** [comment]
As way of clarification, it looks like there are two "issues" in play here.

- One isn't something I'd normally report and is just a UI convention. The sort direction arrow feels like it's reversed compared to what I'd expect, but it is operating consistently across the Manager. Given that it's consistent, I'll write that off as operating as expected.
- The other is that the default sort order on the Domains page is reversed. Loading that page fresh lists the domains in descending order. This is the issue that I'd like to highlight on this report.

**Comment by martinmckenna** [comment]
Hey @rhoths. It looks like the Domains list is now sorted by default in ascending order. Can you confirm this bug is resolved?

As for the UX part of this, to be clear you're saying that you expect the arrow to be pointing up when in ascending order? If so, I'll create a ticket in our tracking software and we can get that in the pipeline.

**Comment by rhoths** [comment]
> It looks like the Domains list is now sorted by default in ascending order. Can you confirm this bug is resolved?

It does appear to be correct now. I should have said something here sooner, but it appeared that all the GitHub Issues were mostly being ignored. At two months+, I'd more or less given up hope I'd get a response.

> As for the UX part of this, to be clear you're saying that you expect the arrow to be pointing up when in ascending order? If so, I'll create a ticket in our tracking software and we can get that in the pipeline.

As I alluded to, I think the orientation of the "arrow" is consistent in the UI, it just seemed reversed to me. On discussion with some colleagues, it would seem we couldn't agree which way made sense (and found examples both ways). Adding in that the arrow seems to flip to an upper and lower position depending on the sort order, it's really not worth further acting on here as long as it remains consistent.

**Comment by martinmckenna** [comment]
For what it's worth, I agree with you and I've created a ticket anyway.

Also, we definitely will not let issues go stale going forward 🙏

**Comment by martinmckenna** [comment]
https://github.com/linode/manager/pull/4862
