### ISSUE TITLE
OAuth Redirect Protocols are HTTP or HTTPS Only

### ISSUE THREAD

**Issue by Andrew-Quebe** [linode/manager#4495]
During the creation of a new OAuth App, when attempting to use a custom scheme for the redirect URI, an error is presented stating that you can only use HTTP or HTTPS as a valid scheme. For applications on mobile platforms such as Android and iOS, deep links often do not work properly without a custom scheme for the redirect. This is due to the browser application being the default handler for the HTTP/HTTPS schemes.

An example of this not working would be the redirect in a Chrome Custom Tab on Android. When redirecting back to the application after logging the user in (the first OAuth step), the callback fails to redirect, and instead, loads in the tab itself, as if browsing forward one page.  If it were a custom scheme/host such as `foo://bar` rather than `https://foo`, the redirect would properly work.

Is this intentional? A security feature? I know most API's don't do limit the schemes, so as to provide support for mobile deep linking.

**Comment by martinmckenna** [comment]
Hey @Andrew-Quebe - sorry for the late response on this. This issue does not directly affect Cloud Manager, as this request is more geared towards our API team, but I will make note of this in our idea tracking software and make the team aware of it.

Thanks for the feedback!
