### ISSUE TITLE
Display uninvoiced balance on account page

### ISSUE THREAD

**Issue by ElectronicWar** [linode/manager#4497]
As the title says, use the classic manager as reference (see screenshot below).
Currently the account page only displays your balance you may have from manual payments.

![image](https://user-images.githubusercontent.com/1890874/52714811-23e29900-2f9b-11e9-875c-ca1de0799ecf.png)

**Comment by martinmckenna** [comment]
Hey @ElectronicWar. This is fixed as of v0.51.1 and is live. Thanks for pointing this out to us!
