### ISSUE TITLE
Only show (...) on details page if more than 2 ips exist

### ISSUE THREAD

**Issue by eatonphil** [linode/manager#450]
And show the extra ips in the same page instead of redirecting. And add a (Hide) link afterward - developer discretion advised.

**Comment by eatonphil** [comment]
Relabeling as enhancement

**Comment by na3d** [comment]
Let's make sure this won't be a problem for some users.  It is ends up making them scroll forever, we may need to implement this differently, if at all.

**Comment by na3d** [comment]
@eatonphil  is this still applicable?

**Comment by eatonphil** [comment]
Yes.

**Comment by eatonphil** [comment]
But ignore my first comment from Sept 12. We should only show the (...) if you have more than one IPv4 or IPv6 address.

**Comment by na3d** [comment]
Is this overcome by events?
