### ISSUE TITLE
Prevent disk size label from bleeding over in disk edit view

### ISSUE THREAD

**Issue by eatonphil** [linode/manager#453]

**Comment by eatonphil** [comment]
<img width="538" alt="screen shot 2016-09-12 at 1 53 36 pm" src="https://cloud.githubusercontent.com/assets/3925912/18448949/186d508c-78fb-11e6-84be-c15ce427059e.png">

**Comment by na3d** [comment]
Ok, the size displayed in the hover is also what is displayed in the label for the slider.
