### ISSUE TITLE
Support truncation of raw volumes (with expert mode)

### ISSUE THREAD

**Issue by shentino** [linode/manager#4545]
You should be able to shrink a raw disk that an expert linode user knows can be safely truncated.

Example:

A raw disk that has a btrfs on it.  I resize it internally from 50g to 40g, and then I want to shrink the disk itself from 50g to 40g.  The linode manager, understandably, would worry about the last 10g, but since I know what I'm doing I should be able to invoke some sort of "expert mode" and override the safety check, and have the disk forcibly truncated.

This is obviously dangerous, but I can foresee this being productively used by an adventurous user.

**Comment by martinmckenna** [comment]
Hey @shentino - while this is not an issue directly affecting the Cloud Manager, I will make note of it in our idea tracking software for our API and infrastructure team to review. Thanks for the feedback.
