### ISSUE TITLE
Fix backup page

### ISSUE THREAD

**Issue by eatonphil** [linode/manager#457]

**Comment by eatonphil** [comment]
Make (Edit scheduled) a modal

**Comment by eatonphil** [comment]
Taking this a bit of a step further depending on new stuff:

![screen shot 2016-09-14 at 4 07 21 pm](https://cloud.githubusercontent.com/assets/3925912/18528074/6c125d2c-7a95-11e6-9db9-d8f79a750fab.png)
![screen shot 2016-09-14 at 4 07 42 pm](https://cloud.githubusercontent.com/assets/3925912/18528075/6c12a23c-7a95-11e6-847e-ed9d01e20a5f.png)
![screen shot 2016-09-14 at 4 07 35 pm](https://cloud.githubusercontent.com/assets/3925912/18528073/6c128644-7a95-11e6-8210-3a7a8f38f7a2.png)

**Comment by eatonphil** [comment]
![screen shot 2016-09-16 at 2 40 37 pm](https://cloud.githubusercontent.com/assets/3925912/18597455/216d3afc-7c1c-11e6-9fa8-73801ca84485.png)
![screen shot 2016-09-16 at 2 40 54 pm](https://cloud.githubusercontent.com/assets/3925912/18597456/2170c122-7c1c-11e6-8a17-85a01d3c5a07.png)
![screen shot 2016-09-16 at 2 40 25 pm](https://cloud.githubusercontent.com/assets/3925912/18597457/2173db78-7c1c-11e6-8f50-cb6a3c38bc4b.png)

**Comment by eatonphil** [comment]
![screen shot 2016-09-16 at 2 53 42 pm](https://cloud.githubusercontent.com/assets/3925912/18597764/6bb06110-7c1d-11e6-85ad-308e8fac4da6.png)

![screen shot 2016-09-16 at 2 53 50 pm](https://cloud.githubusercontent.com/assets/3925912/18597763/6ba42454-7c1d-11e6-8413-b264c72fb440.png)

**Comment by eatonphil** [comment]
![screen shot 2016-09-16 at 3 13 15 pm](https://cloud.githubusercontent.com/assets/3925912/18598318/264ef2be-7c20-11e6-84cc-31806dcc678a.png)
![screen shot 2016-09-16 at 3 13 23 pm](https://cloud.githubusercontent.com/assets/3925912/18598317/264bef1a-7c20-11e6-84e0-6660d3ce1c84.png)

**Comment by eatonphil** [comment]
![screen shot 2016-09-16 at 3 14 12 pm](https://cloud.githubusercontent.com/assets/3925912/18598345/3fcbbbc8-7c20-11e6-8ab2-861f0e87e248.png)

**Comment by SirCmpwn** [comment]
Need mockup for backups not enabled UI

**Comment by eatonphil** [comment]
I had no plans to change it from how it is right now.

**Comment by SirCmpwn** [comment]
So there wouldn't even be subtabs if you don't have backups enabled?

**Comment by SirCmpwn** [comment]
Would the routes even exist?

**Comment by eatonphil** [comment]
No subtabs if you don't have backups, correct. Would the routes exist? They could just redirect to the enable backups page.

**Comment by SirCmpwn** [comment]
Well, I guess we'll see how it shakes out. Sounds complicated to me.
