### ISSUE TITLE
Linode page delete button

### ISSUE THREAD

**Issue by eatonphil** [linode/manager#458]
Two variations of an idea (delete as the last "tab" option that opens up a confirmation modal):

![screen shot 2016-09-13 at 2 00 30 pm](https://cloud.githubusercontent.com/assets/3925912/18485376/8fe59862-79ba-11e6-856d-18f423f7720a.png)
![screen shot 2016-09-13 at 2 00 48 pm](https://cloud.githubusercontent.com/assets/3925912/18485378/8fe6a3ce-79ba-11e6-9879-2ece2a7f19c2.png)

**Comment by na3d** [comment]
Not a fan of this idea, maybe on the settings page, where the rename will happen.

**Comment by SirCmpwn** [comment]
btn-danger-outline "Delete this Linode" next to the save button on the group/label edit?

**Comment by eatonphil** [comment]
Close, but we've repeatedly had issues in discussion when a save button was placed next to a cancel/delete button. But it would be a good convention to have the delete button be on the settings page.

How about this?

![screen shot 2016-09-20 at 10 26 56 am](https://cloud.githubusercontent.com/assets/3925912/18674317/cdd22dfe-7f1c-11e6-8dc8-4afdb73d20c2.png)

**Comment by SirCmpwn** [comment]
I don't like delete as a tab.

**Comment by eatonphil** [comment]
We could put it in a section in the advanced page... but that's getting really hard to reach...

**Comment by SirCmpwn** [comment]
What issues have we had with save next to cancel? We still do that all over the place.

**Comment by eatonphil** [comment]
Although I'm not the one that requested having save and cancel service/delete object not next to each other, I get the idea. And although we haven't necessarily made these changes yet, they've still been requested.

**Comment by eatonphil** [comment]
The need for this still may stand. Will change title appropriately and back out.

**Comment by na3d** [comment]
This can be done elsewhere in a more intuitive way.
