### ISSUE TITLE
display/edit slave details for slave domain

### ISSUE THREAD

**Issue by tonycoz** [linode/manager#4646]
The detail/edit display for slave domains in the new cloud manager displays as if the domain was a Master domain, including details and UI for managing MX, A, TXT records etc.

The UI allows you to attempt to add records but fails with a "Zones must be set to the master type to update resource records using the API." error.

It also fails to display slave specific information - in particular the address of the master.

**Comment by martinmckenna** [comment]
Hey @tonycoz - this should be fixed as of v0.51.1 which is live. Thanks for pointing this one out
