### ISSUE TITLE
"Group by tag" should allow collapsing of groups in list view. 

### ISSUE THREAD

**Issue by fiacovino** [linode/manager#4711]
When I group my Linodes by tag and view the list it would be nice to be able to collapse the list of Linodes with tags I am not interested in right now. This would free up space to display the remaining groups I am interested in viewing right now.

**Comment by martinmckenna** [comment]
Hey @fiacovino - thanks for the UX consideration. This is not something in our immediate roadmap, but we do have a feature currently being designed that will provide a better user experience for grouping entities that are easily viewable without the need for scrolling.

That being said, we'll definitely consider this feedback in the future. Thanks!
