### ISSUE TITLE
Use icons with a label for list/grid view toggle

### ISSUE THREAD

**Issue by eatonphil** [linode/manager#474]
I'm using fa-align-justify and fa-th-large. The selected one should be disabled and grayed out. Also, double check that the view defaults to list.

![screen shot 2016-09-20 at 10 14 34 am](https://cloud.githubusercontent.com/assets/3925912/18673802/1c463400-7f1b-11e6-9674-f568d3aa35af.png)

**Comment by na3d** [comment]
Is it better to show the selected one disabled, or highlighted in a color to show that it is the active one?  This relates to caker's feedback during our meeting.
