### ISSUE TITLE
Improve order summary styling/layout

### ISSUE THREAD

**Issue by eatonphil** [linode/manager#48]

**Comment by eatonphil** [comment]
![screen shot 2016-06-08 at 2 28 05 pm](https://cloud.githubusercontent.com/assets/3925912/15906053/43a744fe-2d85-11e6-91e2-554f05907893.png)

**Comment by SirCmpwn** [comment]
We should ditch the border and the additional protection. Just putting the checkbox there should be sufficient.

**Comment by eatonphil** [comment]
It looked empty without _some_ border and no other border looked ok. Plus this modal is actually floating above everything else, so it's not really going into another design realm to add it here I think.

![screen shot 2016-06-08 at 2 55 19 pm](https://cloud.githubusercontent.com/assets/3925912/15906964/27eb3230-2d89-11e6-80c6-9421a9f86788.png)

**Comment by SirCmpwn** [comment]
The border looks pretty tryhardy.

**Comment by eatonphil** [comment]
hehe. ok here is no border. idc too much actually.
![screen shot 2016-06-08 at 2 58 58 pm](https://cloud.githubusercontent.com/assets/3925912/15907076/9a675078-2d89-11e6-83d9-f4cc4c02f124.png)

**Comment by SirCmpwn** [comment]
...wrong screenshot?

**Comment by eatonphil** [comment]
Were you talking about a different border?

**Comment by eatonphil** [comment]
Ah you're talking about the backups border. The thing is Chris wanted it to be its own section. This is an easier way to do it than giving it its own title and whatnot.

**Comment by SirCmpwn** [comment]
:-1:

**Comment by SirCmpwn** [comment]
It looks tacky.

**Comment by eatonphil** [comment]
I'll show Chris both of these tomorrow and see what he says.
![screen shot 2016-06-08 at 3 25 14 pm](https://cloud.githubusercontent.com/assets/3925912/15907954/3ab73efa-2d8d-11e6-8c73-cad58625f8ab.png)

**Comment by SirCmpwn** [comment]
Much better, thanks.

**Comment by SirCmpwn** [comment]
I'd like up the checkbox with the columns on the right, though.

**Comment by eatonphil** [comment]
Cool. @briansteffens gets credit for the line idea.
![screen shot 2016-06-08 at 3 27 44 pm](https://cloud.githubusercontent.com/assets/3925912/15908053/adad6efc-2d8d-11e6-8646-636030be5c21.png)

**Comment by SirCmpwn** [comment]
(would drop the colon too, best to make the whole thing consistent)

**Comment by eatonphil** [comment]
No, colons are consistent throughout the site where input is requested.

**Comment by SirCmpwn** [comment]
Ick.
