### ISSUE TITLE
Implement backup details and restore page

### ISSUE THREAD

**Issue by abemassry** [linode/manager#492]

**Comment by na3d** [comment]
- [ ] Generalize SnapshotPanel to support backups as well.
- [ ] Burry current summary page, which will be the page when a backup/snapshot is clicked
- [ ] Create a summary page that lists the 3 backups and 1 snapshot, with interactivity
- [ ] Wire everything up with the Linode object
- [ ] Wire up action buttons for take snapshot and restore

**Comment by briansteffens** [comment]
Are there mockups for these pages?

**Comment by eatonphil** [comment]
![screen shot 2016-12-09 at 9 56 39 am](https://cloud.githubusercontent.com/assets/3925912/21053580/0652671a-bdf8-11e6-85ab-64405ec10945.png)
![screen shot 2016-12-09 at 9 56 55 am](https://cloud.githubusercontent.com/assets/3925912/21053581/06596196-bdf8-11e6-93ec-6c81a698d6c9.png)
