### ISSUE TITLE
Show more linode details on page that lists all the linodes.

### ISSUE THREAD

**Issue by ericmutta** [linode/manager#4936]
When looking at the [list of linodes](https://cloud.linode.com/linodes) in grid view, we get something like this:

![linode_summary_card](https://user-images.githubusercontent.com/20465797/57673925-65c8bd00-7626-11e9-951f-d92e4e27cb8c.png)

Currently you see the linode name, specs, region, IP addresses and operating system. There's quite a bit of vertical white space between the name of the operating system and the `Launch Console` button. In that space you could probably squeeze in the following information:

1. **Linode creation date** along with how many days have passed since that date so you can easily tell how long a given Linode has existed.

2. **Linode cost to date** so you can easily see how much the given Linode has contributed to the current uninvoiced balance. In simple terms this answers the question: how much is this Linode costing me? If we can get a dollar figure and a percentage value relative to the total uninvoiced balance that would be great.

**Comment by martinmckenna** [comment]
Hey @ericmutta. Thanks for reaching out on this. I agree with you that we could definitely keep iterating on which information is most valuable to display in the Linodes landing page.

In this case, I'm going to create a ticket in our internal tracking system so we can collaborate with both our product owner, design and API teams to see if this information aligns with other feedback we received and our tracked analytics.

In the meantime, I'm going to close this ticket out.

**Comment by ericmutta** [comment]
Hi @martinmckenna many thanks for the speedy response!

Are there any plans to move away from (or at least integrate) your internal tracking system to this Github one? I ask because it's rather discouraging to file an issue and see it vanish into a black box where you can't track its progress :disappointed:

Also the current system of closing issues and moving them to the internal system makes this repo feel like a ghost town. When I first landed here I was like **this early-access project only has one active issue?! Is _anybody_ using this thing?**

I appreciate the reality of having internal systems that are hard to move away from, but if the new Linode Manager is going to do well as an open-source project I really strongly believe it needs to have issue tracking happen in the open too.

**Comment by martinmckenna** [comment]
@ericmutta Unfortunately, while the Cloud Manager's source code is open-source, many of the internal discussions surrounding it aren't, since our other services (such as our API and build processes) are closed-source.

That being said, being more transparent about our roadmap is something we've had discussions about and it's worth continuing the conversation

**Comment by ericmutta** [comment]
> I'm all for leaving GitHub issues open until a decision is made on whether or not to implement the feature.

This is a reasonable compromise and now I feel more inspired to file other issues I had in mind. Many thanks! :+1:

**Comment by johnwcallahan** [comment]
Hey @ericmutta, I know this issue has been open a while, but I wanted to provide a quick update.

We have an app-wide UI refresh coming in a few months, and part of this effort is to include more info on the Linodes Listing page:

![Screen Shot 2020-07-20 at 3 30 40 PM](https://user-images.githubusercontent.com/16911484/87978183-fd813100-ca9d-11ea-9b8b-d6fd718c5044.png)

Note that "cost to date" as you requested is unfortunately not available, but several other details are, including the creation date and SSH access info.

**Comment by ericmutta** [comment]
Hi @johnwcallahan many thanks for the update, I am happy to see the created date has been added and the new UI looks very fresh! Looking forward to the release whenever it comes out :+1:

**Comment by ericmutta** [comment]
Hi @Jskobos thanks for letting me know! I did notice the refresh and love how it packs a ton of information in a small space (bit daunting at first, but once you know what's what, its super handy for reviewing your linodes without clicking all over the place...also love the ability to launch the lish console straight from the three-dots menu :+1:).
