### ISSUE TITLE
Auto Add A / AAAA Record at Add a new Domain

### ISSUE THREAD

**Issue by bkfon** [linode/manager#4941]
In the old version there was an automatic addition of a / aaaa records when adding a domain. In the new version of this function is not.

**Comment by martinmckenna** [comment]
Hey @bkfon. This is actually something on our roadmap that we plan on taking action on. I will let you know when we have an update on this.

**Comment by martinmckenna** [comment]
@bkfon Slated for the v0.58.0 release, which should be out before the end of the week
