### ISSUE TITLE
Paypal doesn't work

### ISSUE THREAD

**Issue by daparky** [linode/manager#5025]
Trying to top up my account via Paypal but it just hangs when it opens the Paypal window.

The Paypal window just has a spinning padlock animation going on and doesn't proceed.

**Comment by martinmckenna** [comment]
Hey @daparky. Sorry to hear about the issues with Paypal. Could you give us some more reproduction steps? Specifically, what is the amount you're attempting to pay with?

Further, are you seeing any issues in the browser console? You can usually open up the console by hitting the F12 key in Chrome.

Unfortunately, I can't reproduce on my end, so it might be an issue with the dollar amount limits set by our API, so if there is an error we're not reporting, we should definitely get that fixed up.

**Comment by daparky** [comment]
Hi @martinmckenna, thanks for your response.

I found the issue, it's because I was using Chrome Canary. Tried in normal Chrome and it worked.
