### ISSUE TITLE
Migration Upgrade Status Queue

### ISSUE THREAD

**Issue by RitterKnightCreative** [linode/manager#5048]
The Cloud Manager is looking great!

One thing I noticed on the old interface that the new one is lacking is how many migrations are queued in front of you and the estimated time to migrate.

I'm not sure if this information was removed because it was inaccurate or simply an oversight? Looks like the copy was simplified as well which is great but those additional details would be nice because it's one gauge of how busy the network seems to be. 

![Screen Shot 2019-06-10 at 3 45 52 PM](https://user-images.githubusercontent.com/3707869/59225765-2fd01780-8b97-11e9-9901-4f89685c8a27.png)
![Screen Shot 2019-06-10 at 3 45 16 PM](https://user-images.githubusercontent.com/3707869/59225766-2fd01780-8b97-11e9-9ab8-68c0ec5f8f5d.png)

**Comment by martinmckenna** [comment]
Hey @RitterKnightCreative. Thanks for the feedback.

I agree with you that this is some useful information we're missing in Cloud Manager. That being said, it's actually more of a limitation with our [public APIv4](https://developers.linode.com/api/v4/), as it doesn't return that information in any available endpoint. If anything changes, I'll be sure to let you know but as of now we have no plans to include that in the upgrade messaging.

Looking at those screenshots, it looks like we also need to implement the ability to optionally resize your disk when upgrading your Linode - that's something we should implement ASAP and I'll be sure to get that into the pipeline.

**Comment by martinmckenna** [comment]
hey @RitterKnightCreative - just want to provide an update and say that in the next release, we'll be showing estimated time to migrate in this upgrade drawer.

Look out for that sometime this week.
