### ISSUE TITLE
Reset password button should have a confirm modal

### ISSUE THREAD

**Issue by briansteffens** [linode/manager#513]

**Comment by eatonphil** [comment]
Should it? Do we do that in the CF manager?

**Comment by briansteffens** [comment]
Not sure, seemed like a potentially destructive action.

**Comment by eatonphil** [comment]
@abemassry my bad. Seems there is some precedent for now

![screen shot 2016-11-11 at 11 11 55 am](https://cloud.githubusercontent.com/assets/3925912/20221543/b3765ef6-a7ff-11e6-8848-a0cb201aa23e.png)
