### ISSUE TITLE
"Group by tag" behaves strangely in Linodes view

### ISSUE THREAD

**Issue by andysh-uk** [linode/manager#5162]
The "group by tag" option is behaving a bit strangely on the Linodes page.

* Login to Dashboard
* Click Linodes page - "group by tag" is enabled
* Un-select it, click another tab (e.g. Domains)
* Click back to Linodes page - "group by tag" is now enabled again
* Hit Refresh in the browser - "group by tag" is not enabled

* Select it to enable it, click another tab
* Click back to Linodes - "group by tag" is still enabled
* Hit Refresh - stays enabled

It seems to be ignoring the current value of the option when you're switching between tabs, but on initial load, it is set correctly.

**Comment by johnwcallahan** [comment]
This has been resolved -- a fix will be included in the next release of Cloud Manager, scheduled for tomorrow (7/2/19). Thanks for the feedback!
