### ISSUE TITLE
Linode notification thresholds not loading

### ISSUE THREAD

**Issue by andysh-uk** [linode/manager#5163]
On the Linode Settings tab, the notification thresholds are not loading.

This is a new Linode, so I thought I needed to set them myself. Set them, hit Save, they remain.

When the page is refreshed, they load in blank.

**Comment by johnwcallahan** [comment]
Thanks for reporting this, @andysh-uk. We'll get this resolved ASAP.

**Comment by johnwcallahan** [comment]
Hi @andysh-uk, this was fixed in v0.63.0, which was released earlier today.

Thanks again for the issue!
