### ISSUE TITLE
Choose a Distribution Page Should be Tweaked

### ISSUE THREAD

**Issue by felicianotech** [linode/manager#5168]
Page: https://cloud.linode.com/linodes/create
Screenshot: 
![FireShot Capture 005 - Create a Linode - Linode Manager - cloud linode com](https://user-images.githubusercontent.com/6017470/60400984-50addc00-9b49-11e9-8835-a1ad3a17ae3d.png)

I think that the "Choose a Distribution" page/panel in Manager should be tweaked. As you can see from the screenshot above, Ubuntu 19.04 is shown and Ubuntu 18.04 is not. Any server person, especially Ubuntu user, worth their salt knows that LTS releases (18.04) are the recommended releases of Ubuntu to install on servers. The non-LTS release (19.04, 18.10, etc) are not. They're useful for testing maybe, but not the solid, recommended version to use. I believe that it's doing users injustice to show Ubuntu 19.04 over 18.04 here.

The reason for this? I get it, it's showing the distros in reverse chronological order so Ubuntu 18.04 is hidden behind the "show older images" button. This implementation should be changed.

Certain releases, such as Ubuntu LTS releases, should be given a higher priority (or pinned or something) so that they always show up in the list without having to expand for older releases.

In the case of Ubuntu, I'd suggest that the most current LTS be show always. The older LTS releases aren't necessary and can remain behind the expand button.

**Comment by johnwcallahan** [comment]
Thanks for opening this issue, @felicianotech. We're currently exploring a new UX pattern for distro selection, which will solve the problem that you describe. I'll keep this issue open so we can keep you updated on our progress.

**Comment by martinmckenna** [comment]
hey @felicianotech. The Distrobution selection has been updated thanks to @Jskobos. Check out [the new look and feel](https://cloud.linode.com/linodes/create) and let us know what you think 😎
