### ISSUE TITLE
Brief thoughts on power dropdown

### ISSUE THREAD

**Issue by eatonphil** [linode/manager#534]
Goals:

* Be mostly consistent between all views (3 currently: Linode, card, list)
* Not be too clunky/blocky
* Still indicate the connection between status and dropdowns containing actions

I don't seem to have a mockup of the list view so I'll come back to that later if need be.

![screen shot 2016-10-07 at 11 53 43 am](https://cloud.githubusercontent.com/assets/3925912/19196813/ff0b39ae-8c84-11e6-8522-1ff3d35abbda.png)
![screen shot 2016-10-07 at 11 53 51 am](https://cloud.githubusercontent.com/assets/3925912/19196816/ff10bb5e-8c84-11e6-920f-f8a093b8e89f.png)
![screen shot 2016-10-07 at 11 53 58 am](https://cloud.githubusercontent.com/assets/3925912/19196811/ff080c48-8c84-11e6-8b43-f33abde35676.png)
![screen shot 2016-10-07 at 11 54 11 am](https://cloud.githubusercontent.com/assets/3925912/19196815/ff0cb5f4-8c84-11e6-9592-bac44eda5538.png)
![screen shot 2016-10-07 at 11 54 17 am](https://cloud.githubusercontent.com/assets/3925912/19196812/ff0a25e6-8c84-11e6-8921-f90bdb223950.png)
![screen shot 2016-10-07 at 11 54 23 am](https://cloud.githubusercontent.com/assets/3925912/19196814/ff0c620c-8c84-11e6-8656-64dcab30e3e6.png)

**Comment by briansteffens** [comment]
At first glance I like the last 2. The extra line between the status and the button is just noise IMO. The last one is cleanest looking but the second might be clearer that it can be interacted with.

**Comment by eatonphil** [comment]
I'm leaning toward maybe we drop the outline on the card and list views but keep it for the Linode details page.
