### ISSUE TITLE
Get rid of cyclic structure created by genConfig and used by refineState

### ISSUE THREAD

**Issue by eatonphil** [linode/manager#540]

**Comment by mparke** [comment]
@eatonphil does this problem still exist?

**Comment by na3d** [comment]
@eatonphil  does this still exist?

**Comment by eatonphil** [comment]
Yup.

**Comment by eatonphil** [comment]
Not worth keeping alive as an issue. The only thing it prevents you from doing is printing out a config. But I've never really needed to do that anyway.
