### ISSUE TITLE
Center dropdown arrow

### ISSUE THREAD

**Issue by briansteffens** [linode/manager#546]

**Comment by briansteffens** [comment]
This may not be necessary anymore (not sure if any dropdowns are left other than the status dropdowns) but:

![screen shot 2016-10-18 at 4 01 05 pm](https://cloud.githubusercontent.com/assets/4149249/19494253/3a1ff708-954c-11e6-8667-69d5890f9efe.png)

**Comment by eatonphil** [comment]
After a while looking into this, it seems a little too deep into bootstrap... we may be better off switching to our own dropdown styles to fix this.

**Comment by abemassry** [comment]
Superseded by #856
