### ISSUE TITLE
Vertical align the 'alert enable' checkboxes

### ISSUE THREAD

**Issue by briansteffens** [linode/manager#552]
![screen shot 2016-10-18 at 3 59 37 pm](https://cloud.githubusercontent.com/assets/4149249/19494270/528ce45e-954c-11e6-836a-3b520dd829ed.png)

**Comment by eatonphil** [comment]
Oh man that's not right.

**Comment by eatonphil** [comment]
The padding on the right by the arrows is off too.

**Comment by na3d** [comment]
We might want to verify in Opera, Safari, Chrome, Firefox, and IE 10 - Edge how everything looks.

**Comment by eatonphil** [comment]
Still an issue on FF, confirmed.
