### ISSUE TITLE
Next iteration mockup progress bar

### ISSUE THREAD

**Issue by eatonphil** [linode/manager#569]

**Comment by eatonphil** [comment]
![screen shot 2016-10-25 at 1 29 42 pm](https://cloud.githubusercontent.com/assets/3925912/19696969/711807da-9ab7-11e6-9b51-83fec50a52ec.png)
![screen shot 2016-10-25 at 1 29 48 pm](https://cloud.githubusercontent.com/assets/3925912/19696970/711b36d0-9ab7-11e6-8b89-c5bd5cddfcef.png)
![screen shot 2016-10-25 at 1 30 00 pm](https://cloud.githubusercontent.com/assets/3925912/19696971/711efd92-9ab7-11e6-8394-0feb3dded202.png)

**Comment by abemassry** [comment]
just for clarification, the in progress status will only be represented on the linode detail view page?

**Comment by eatonphil** [comment]
That's the idea here anyway
