### ISSUE TITLE
Mockup feedback extractor

### ISSUE THREAD

**Issue by eatonphil** [linode/manager#571]

**Comment by eatonphil** [comment]
![screen shot 2016-10-25 at 11 11 48 am](https://cloud.githubusercontent.com/assets/3925912/19691893/e86ba85a-9aa3-11e6-9187-92c81ecb153c.png)
![screen shot 2016-10-25 at 11 11 55 am](https://cloud.githubusercontent.com/assets/3925912/19691894/e86ff162-9aa3-11e6-8e74-91cb1f269643.png)

**Comment by jfrederickson** [comment]
Quick thought - probably want to make sure it doesn't show up/shows up in a different location if someone visits the Manager on a device with a very narrow viewport (e.g. mobile browsers). I've seen feedback bars like this on other sites that obstruct the page content on mobile devices.

Aside from that, I like it! Very unobtrusive, but I think people will see it if they're looking for it.

**Comment by eatonphil** [comment]
@jfrederickson mobile is a big issue/discussion point. But right now, we are explicitly not prioritizing support for mobile (and non-FF/non-chrome browsers for that matter).

**Comment by abemassry** [comment]
Perfect, when we go to implement it, we can try it on the bottom of the page as well.  I'm leaving this over here as a note, no need to mock it up
