### ISSUE TITLE
Support '@' for CNAME target

### ISSUE THREAD

**Issue by trinopoty** [linode/manager#5721]
Can we please have support for '@' in the CNAME target field?

**Comment by martinmckenna** [comment]
Hey @trinopoty. Thanks for reaching out. The inability to enter an `@` as a CNAME target is actually a limitation of our APIv4.

Could you give us some more detail of the expected functionality and what exactly you're looking for?

**Comment by trinopoty** [comment]
Entering '@' would be useful because right now, one needs to type in the full domain name to refer to it. This is certainly a bit error prone.
Also, it's not required on the API. I believe just doing it on the manager would be enough.
Something like, if the target is '@', replace it with the domain name and send to the API.

**Comment by martinmckenna** [comment]
Gotcha. So essentially, you're looking for the `@` character to strip out the subdomain of whatever is in the  Hostname field.

So for instance if I enter `www.helloworld.com` as a hostname and `@` as a target, you'd expect the request to send the following to the server:

```js
{
  "type": "CNAME",
   "name": "www.helloworld.com",
   "target": "helloworld.com"
}
```

**Comment by trinopoty** [comment]
Yes that is correct. This is the behaviour provided by other DNS providers such as Godaddy, Cloudflare and others.

**Comment by martinmckenna** [comment]
Got it. We'll take this feedback into our priority planning and see if we can't get a PR up for this soon. Thanks for the feedback!

**Comment by Jskobos** [comment]
@trinopoty sorry this took us so long! Support for this will be going out in our release later today. Please let us know if the functionality is what you expected and/or if you can see room for further enhancements. Closing this out for now.

**Comment by trinopoty** [comment]
It seems to be working as expected. Thank you for taking the time to work on this.
