### ISSUE TITLE
How to use upload file object storage using expressjs ?

### ISSUE THREAD

**Issue by RakaWA** [linode/manager#5834]
How to use upload file object storage using expressjs with acces token and key ?

**Comment by johnwcallahan** [comment]
Hi @RakaWA. Linode Object Storage can be used with any s3-compatible tool, so you could use something like the JavaScript [AWS SDK](https://www.npmjs.com/package/aws-sdk) in your Node app to interact with Object Storage.

It'll depend on your use case, but I'd recommend using pre-signed URLs for file uploads. The idea is that your Express.js server will use an Access Key and Secret Key to generate an authenticated URL to allow a client to upload a specific file directly to Object Storage, without the file having to pass through your server. There are several blog posts out there with example code that may be helpful.
