### ISSUE TITLE
2FA: add support for U2F and FIDO2

### ISSUE THREAD

**Issue by Hyask** [linode/manager#5841]
It would be great to support security keys like YubiKeys for 2nd factor authentication.

**Comment by trinopoty** [comment]
+1 for this. It's cumbersome to type the OTP every time.

**Comment by trinopoty** [comment]
I suspect this isn't controlled from this project.
It's an entirely different project that's not a public repo.
Hopefully, someone from the staff will open a relevant issue on the project that's actually concerned with this change.

**Comment by johnwcallahan** [comment]
Thanks for reaching out. @trinopoty you're right in that this discussion is larger than this specific project. We've discussed this internally, but it's not on our immediate roadmap. I'm happy to re-open this if that changes in the future.
