### ISSUE TITLE
Updates the card and list view

### ISSUE THREAD

**Issue by eatonphil** [linode/manager#585]
![screen shot 2016-10-25 at 1 29 21 pm](https://cloud.githubusercontent.com/assets/3925912/19696948/6179c3c2-9ab7-11e6-9eb9-8d6514f1e351.png)

![screen shot 2016-10-25 at 1 29 31 pm](https://cloud.githubusercontent.com/assets/3925912/19696949/617b13da-9ab7-11e6-92e5-eed7f86b16a6.png)

**Comment by na3d** [comment]
Is there an alternative to the checkbox?  Maybe a colored inside left border?

**Comment by abemassry** [comment]
I like both of these, I feel like there is a lot of whitespace in the list view but that could be left as is or is room for future expansion, the card view is really good

**Comment by eatonphil** [comment]
> Is there an alternative to the checkbox? Maybe a colored inside left border?

@na3d That sounds more like an indication that the thing has already been checked - not an invitation to check it.

> I like both of these, I feel like there is a lot of whitespace in the list view

@abemassry yeah... one issue is that the mocked up screen this represents is pretty huge. I don't think the container is even allowed to get this big.

**Comment by na3d** [comment]
The card version looks horrible to me, because the checkbox doesn't have equal padding in any direction at all.

**Comment by eatonphil** [comment]
That is getting into the realm of too picky for me... Because everyone has had different opinions about what looks good here.

This is a mockup with equal padding.

![screen shot 2016-10-25 at 2 46 07 pm](https://cloud.githubusercontent.com/assets/3925912/19699594/ead90b78-9ac1-11e6-83df-634d3f17f2fb.png)

**Comment by na3d** [comment]
The equal padding helps a lot, thank you.  There has to be a better solution, but this will do for now.
