### ISSUE TITLE
Add no distribution card in create source selection

### ISSUE THREAD

**Issue by eatonphil** [linode/manager#593]

**Comment by eatonphil** [comment]
Better yet (from design perspective) would be to include an empty distro card that describes it as deploying no distro. This may or may not be obvious enough.

**Comment by eatonphil** [comment]
![screen shot 2016-11-07 at 11 06 35 am](https://cloud.githubusercontent.com/assets/3925912/20064895/3cf8ab26-a4da-11e6-97c8-26fe2d53b5f7.png)

**Comment by na3d** [comment]
Feelings on a circle with a diagonal line through it?  Seems weird for the rest to have images, but I trust your judgement.

**Comment by eatonphil** [comment]
I don't think that is more descriptive than this, and it not being an image does not really bother me.

**Comment by phuegel** [comment]
Disable password and backups

**Comment by phuegel** [comment]
As needed create additional tasks if additional items.
