### ISSUE TITLE
"Page break" between line items and subtotal in PDF invoice 

### ISSUE THREAD

**Issue by TommyZG** [linode/manager#6089]
When I try to get the PDF of an invoice, although the invoice has only two items, there are two pages. The first page has two line items and lots of empty space, and the second page contains only the subtotal and again a lot of empty space. Can this be fixed, so total is displayed below the two invoice items and the invoice is on a single page? 

This has been reported to Linode Support 4 months ago. The interim solution was to use the Classic Manager, but it seems it is decomissioned now since the URL is redirecting to the Cloud Manager. 

Editing PDF each month manually for accounting department is not really a solution.

Steps to reproduce: https://cloud.linode.com/account/billing -> Recent Invoices -> any invoice -> Download PDF.
I guess the browser version and OS don't matter since PDF is generated on the backend.

Thank you in advance.

**Comment by TommyZG** [comment]
Anyone?

**Comment by johnwcallahan** [comment]
Thanks @TommyZG; I apologize for the delay. 

I'm able to reproduce this issue. We generate the Invoice PDFs on the front-end, and we're adding an extra page before the "total" section here: 

https://github.com/linode/manager/blob/2d883a1461a2b82354ecc4caa2fde0e107fd2172/packages/manager/src/features/Billing/PdfGenerator/PdfGenerator.ts#L194

Removing that extra page seems to do the trick, but we need to make sure that it doesn't break the formatting anywhere else. 

This fix is slated for our current iteration so you can expect this to be resolved soon. I'll keep this open and provide updates along the way.

Thanks again for reporting!

**Comment by TommyZG** [comment]
Hello, @johnwcallahan. Thanks for your effort and your quick resolution. There is a check if the page break is necessary, a few lines before, at 

https://github.com/linode/manager/blob/2d883a1461a2b82354ecc4caa2fde0e107fd2172/packages/manager/src/features/Billing/PdfGenerator/PdfGenerator.ts#L189-L191 

so I believe removing L194 won't break anything on invoices with 20+ items.
