### ISSUE TITLE
domain manager and DNSSEC

### ISSUE THREAD

**Issue by robo2bobo** [linode/manager#6096]
I can't find any information regarding DNSSEC in the domain manager. Is DNSSEC not supported by the linode DNS servers, or is it a limitation of the new cloud manager?

Thank you.

**Comment by johnwcallahan** [comment]
Hi @robo2bobo, you're right that this is not currently supported. We are looking into it, but I'm not able to provide any solid information on how this fits in to our roadmap. That being said, I've taken note of your interest in our internal tracker. There's some discussion on this topic on our Community Site: https://www.linode.com/community/questions/158/is-dnssec-going-to-be-supported.
