### ISSUE TITLE
When importing the DNS Zones, SOA RNAME dots are incorrectly translated to @'s

### ISSUE THREAD

**Issue by coling** [linode/manager#6104]
The RNAME field is an email address. The first (non-escaped) dot should be converted to an @ but it seems all dots are converted to @'s.

**Comment by coling** [comment]
Correction: The first _two_ dots are converted to @'s

e.g. 
`foo.bar.com -> foo@bar@com`
but
`foo.bar.oink.com -> foo@bar@oink.com`

**Comment by johnwcallahan** [comment]
Thanks, @coling. We're investigating this issue on the back-end. I'll keep this open and provide an update when more details are available.

**Comment by johnwcallahan** [comment]
A back-end fix for this issue has been released. Only the first dot should be converted to an "@" now. Thanks again for reporting!
