### ISSUE TITLE
After importing a DNS zone, we are redirected to a 404 page

### ISSUE THREAD

**Issue by coling** [linode/manager#6105]
When you import a DNS zone, you are redirected to a URL of the form:
`https://cloud.linode.com/domains/123456`

This results in a large Not Found page.

Clicking on the "Domains" link from the menu lists all domains prior to import.

Doing a full page reload shows the imported domain also.

**Comment by johnwcallahan** [comment]
Hi @coling, thanks for reporting this. I think this is because we are not updating the Redux store with the response from the POST request when importing a domain. 

We've got this slated for our current iteration of work, so a fix will be coming shortly.

**Comment by johnwcallahan** [comment]
Hey @coling, we just released a fix for this yesterday (v1.3.0). Feel free to reach out if you have more issues. Thanks again for reporting!
