### ISSUE TITLE
Wrong display of time

### ISSUE THREAD

**Issue by robo2bobo** [linode/manager#6106]
Hello,

I have several events that display the "time ago" in a very wrong way. For example, 404213 hours ago.

![hours1](https://user-images.githubusercontent.com/37706921/74564488-d87d1500-4f77-11ea-9d86-758578d330da.png)
![hours2](https://user-images.githubusercontent.com/37706921/74564496-dc109c00-4f77-11ea-9289-156461585263.png)

Maybe a rounding error, or an invalid conversion from a float?

**Comment by johnwcallahan** [comment]
Hi @robo2bobo, thanks for reporting. I think this has to do with `host_reboot` event durations being reported incorrectly by the API. I've opened a [PR](https://github.com/linode/manager/pull/6132) to hide the duration for `host_reboot` events for now, and will follow up with our API team.
