### ISSUE TITLE
Fix alignment of tag headers of Linodes list

### ISSUE THREAD

**Issue by jungaretti** [linode/manager#6191]
I have a couple of Linodes grouped by their tags. The left padding of these headers' container `td` is inconsistent. The first header has `left-padding` of `15px`, while the second's `left-padding` is `0px`.

https://cloud.linode.com/linodes?view=list

<img width="503" alt="Screen Shot 2020-03-13 at 12 29 06 AM" src="https://user-images.githubusercontent.com/19893438/76592526-a81a8f00-64c1-11ea-8ede-fc8e8d98a5c2.png">

Firefox 74.0

**Comment by johnwcallahan** [comment]
Good catch @jungaretti. I just opened a [PR](https://github.com/linode/manager/pull/6199) to address this.
