### ISSUE TITLE
Improve header bar number of notifications design

### ISSUE THREAD

**Issue by eatonphil** [linode/manager#62]
How should the number of notifications be displayed in the navigation? Also includes collab with @caker to figure it out.

**Comment by eatonphil** [comment]
![screen shot 2016-06-07 at 4 45 27 pm](https://cloud.githubusercontent.com/assets/3925912/15874039/632cbf90-2ccf-11e6-9198-f4305bcc77e7.png)
![screen shot 2016-06-07 at 4 46 04 pm](https://cloud.githubusercontent.com/assets/3925912/15874038/632b6d98-2ccf-11e6-8f36-a5a7b6585222.png)

**Comment by eatonphil** [comment]
First has no border, second has a white border.

**Comment by SirCmpwn** [comment]
no border++

**Comment by eatonphil** [comment]
me too
