### ISSUE TITLE
Timezone support of 0:30 and 0:45 minutes

### ISSUE THREAD

**Issue by jeffmcneill** [linode/manager#622]
For the timezone settings you have Asia/Rangoon and Asia/Yangon (same city) at GMT +7. But all of Myanmar is actually GMT +6:30. 

Since this is pretty important, I would hope it could have a priority. It is especially an issue for India, Iran, Australia, and others.

It would also be better to have one listing -- either Asia/Rangoon/Yangon, or Asia/Yangon. Yangon is the official name, Rangoon is a historical name. Everyone who calls it one name, knows the other name.

Note that there are 0:45 offset timezones as well, may want to include that on the feature request. 

Source: https://en.wikipedia.org/wiki/List_of_UTC_time_offsets

**Comment by eatonphil** [comment]
Interesting. Thanks for pointing this out. All the timezones (and there are a number of duplicates for some reason) are pulled from the Olson database by both Java and Python, I believe. We may have to look into making better use of the database or switching to a different one.

**Comment by jeffmcneill** [comment]
So, fixed or will-not-fix?

**Comment by rjstires** [comment]
Hi @jeffmcneill! As you may have noticed we've refreshed the frontend of the Cloud Manager. As part of that effort we're revamping the way time is displayed to user and part of that strategy will address your concerns. It's worth noting we haven't yet implemented that strategy so times displayed may not be adjusted for the current user or their selected timezone.
