### ISSUE TITLE
Resize disk instructions are not clear

### ISSUE THREAD

**Issue by nicolasdanelon** [linode/manager#6252]
If I want to shrink a linode I have to resize my disks manualy. The Auto Resize Disk should have a better wording, at the time it is not clear.

![Screenshot from 2020-03-27 12-21-41](https://user-images.githubusercontent.com/2846046/77771588-a2768a80-7025-11ea-92a1-54594b8136d4.png)

I don't think is necessary but I've saw this on Firefox 74.0, Linode manager version v1.3.0

**Comment by nicolasdanelon** [comment]
btw, I'm a frontend developer and I've using linode since 2012. I love the work you've done. The new react ui it's amazing

**Comment by Jskobos** [comment]
Thanks for the feedback, we're glad you like the new interface! You're right that we should make this clearer. As is, if you resize to a lower plan we de-select the checkbox and show a help icon, but you have to hover over it to actually see what's going on. We'll add some text to the main message for clarity.

![Screen Shot 2020-03-31 at 9 32 24 AM](https://user-images.githubusercontent.com/1624067/78032775-84fe3500-7333-11ea-956c-2a594d84057e.png)

**Comment by nicolasdanelon** [comment]
yeah, I check the code and then I saw the tooltip haha. but........... I feel that the text need a little change. thanks Jskobos

**Comment by Jskobos** [comment]
@nicolasdanelon we released a fix for this a few months back but never updated you, sorry about that. Resizing now lives inside a modal, and we've expanded the helper text next to the auto resize function.
