### ISSUE TITLE
Show amount of storage used by Object Storage on Object Storage page

### ISSUE THREAD

**Issue by Oloryn** [linode/manager#6256]
It would be handy to have the amount of storage currently used by the account's object storage showing on the object storage page.

**Comment by johnwcallahan** [comment]
Hey @Oloryn, I agree this would be handy. We've been discussing ways we could expose this info in our API, and thus display it in Cloud Manager. I don't have specifics to share on a timeline, but I've noted your request and will update this issue as details become available. 

In the meantime, you can use a tool like the Linode CLI to view the size of each bucket:

```
$ linode-cli obj du <bucket_name>
```

For more info on using Object Storage with the Linode CLI, see https://www.linode.com/docs/platform/object-storage/how-to-use-object-storage/#linode-cli.

**Comment by andysh-uk** [comment]
+1 for this

**Comment by kanongil** [comment]
I am considering using the object storage product, but I find it concerning that there doesn't appear to be a way for me to see the total amount stored. Especially considering this is a billable metric.

**Comment by johnwcallahan** [comment]
Thanks @andysh-uk and @kanongil; I've noted your interest in this feature in our internal tracker.

I do want to underscore that it's possible to see your total Object Storage usage with other tools like the Linode CLI (example above) or [s3cmd](https://s3tools.org/s3cmd):

```
$ s3cmd du
```

You can find more info on Object Storage tooling at https://www.linode.com/docs/platform/object-storage/how-to-use-object-storage/

**Comment by andysh-uk** [comment]
Thanks @johnwcallahan, I do hope you get this in the UI soon though; it’s a pain having to drop into the CLI when most other operations can be done in Manager.

If linode-cli can surface this information, does this mean it’s available in the Linode API?

**Comment by kanongil** [comment]
I just tested your `linode-cli` workaround, however it is not a viable solution. I timed a run, and it took 3m 44s to complete, and used heaps of cpu and bandwidth in the process.

FYI, I'm still only using 1/8'th of what I plan to use, so it will likely take take ~30 mins to complete by then!

Again, this is a billable metric, which should be readily available in your system.

**Comment by Oloryn** [comment]
@kanongil What have you got stored in S3 storage  that it's taking that long?  Using either the s3cmd or the linode-cli workaround, etiher from home or from one of my linodes, it takes me no more than 3 seconds of run time,  and I've got about 72GB of storage in use (in about 1100 files).  Only thing I can think of is perhaps you have a huge number of small files?

**Comment by kanongil** [comment]
Huge number of files, yes.

FYI, I found that ceph seems to be able to expose the storage size through the swift API: https://docs.ceph.com/docs/mimic/radosgw/swift/serviceops/#list-containers

**Comment by johnwcallahan** [comment]
It's true that if you have a huge number of files the calculation that tools like s3cmd does is going to take a while. 

Fortunately it looks like we're going to be able to add this to the API/Cloud very shortly; I'll keep you posted.

**Comment by andysh-uk** [comment]
Amazing, thank you @johnwcallahan and @adammohammed  😊

**Comment by andysh-uk** [comment]
This make me very happy, look forward to it hitting live.  Thanks @johnwcallahan @adammohammed 😄

**Comment by johnwcallahan** [comment]
These changes were just released. There is now a "Size" column on the Buckets table:

![Screen Shot 2020-06-30 at 1 18 30 PM](https://user-images.githubusercontent.com/16911484/86157625-ad820080-bad5-11ea-858d-1f4b3c4f17d3.png)

You can see the full release notes of v1.13.0 [here](https://github.com/linode/manager/releases/tag/linode-manager%40v1.13.0).

**Comment by andysh-uk** [comment]
Brilliant, looking good 😄 👍 

Thanks again guys
