### ISSUE TITLE
Changing Group causes bad State

### ISSUE THREAD

**Issue by Dorthu** [linode/manager#631]
Steps to reproduce:

1. Create a new Linode (do not specify group)
1. Go to Settings tab
1. Enter Group and click Save
1. Go to Linodes page

Result:

Linode is shown twice - a solid green bar is shown where "Running" should be.

![screen shot 2016-11-04 at 9 42 28 am](https://cloud.githubusercontent.com/assets/7172953/20007691/dd464246-a273-11e6-8a81-6c350ed2f0e1.png)

**Comment by eatonphil** [comment]
We've been seeing some issues with group changing recently but this is a new symptom. Thanks for the bug report!
