### ISSUE TITLE
Middle-click / ctrl+click on tabs doesn't open them in new browser tab

### ISSUE THREAD

**Issue by briansteffens** [linode/manager#633]

**Comment by eatonphil** [comment]
This is probably going to be an issue in [react-tabs](https://github.com/reactjs/react-tabs).

**Comment by briansteffens** [comment]
Opened issue with react-tabs here:

https://github.com/reactjs/react-tabs/issues/145

Figured out what we can change to fix it, but might as well see why they do things that way to make sure we're not breaking anything else.

**Comment by briansteffens** [comment]
Closing this for now as we've looked into this as far as we can at the moment. I'd rather not hack something together or maintain a fork of a repo over something like this until we've actually discussed and know what/why we're doing it.
