### ISSUE TITLE
Sass organization

### ISSUE THREAD

**Issue by eatonphil** [linode/manager#634]
The organization of our css is degrading (and was never nice to begin with). We have a few needs:

* Less fragile selectors
* A consistent naming scheme
* A consistent file structure
* Ideally a way to lint one or both of these

There are a number of existing standards out there. [BEM](http://getbem.com/introduction/), [SMACSS](https://smacss.com/), [SUIT](https://suitcss.github.io/), etc.

I propose we move to the BEM/SUIT scheme and use a structure more fitting to our existing layout. There is an existing [linter](https://github.com/postcss/postcss-bem-linter) we can use to enforce this.

In the style of BEM/SUIT, style description will begin at the component and share the same file path as the source component albeit in the scss directory. When a specific layout needs to overwrite the rules for the component, it will do so in its own file in the appropriate layouts directory.

One side-effect of this change will require subdirectory routes' index pages to be renamed so the CSS class-names don't clash. (I.e. src/linodes/linode/IndexPage -> src/linodes/linode/LinodePage)

Example:

```js
// src/linodes/linode/LinodePage.js
import FullWidthCard form '~/components/FullWidthCard';
export class LinodePage extends Component {
    ...
    render() {
        return (
            <div className="LinodePage">
                <FullWidthCard>
                    <header className="FullWidthCard__header">My Linode</header>
                </FullWidthCard>
            </div>
        );
    }
}
```

```
// scss/components/FullWidthCard.scss
.FullWidthCard {
    &__header {
        background: white;
    }
}
```

```css
// scss/linodes/linode/LinodePage.scss
.LinodePage {
    .FullWidthCard {
        &__header {
            background: gray;
        }
    }
}
```

Bonus points: [dead css code removal linter](https://github.com/giakki/uncss)

**Comment by na3d** [comment]
I am not a fan of double underscores and dashes for a naming practice, except for very specific purposes that require the attention of someone touching a file. BEM and SUIT both over utilize this technique, which, I fear, will make our CSS look like a mess.

I like the concept other than that fact.  If we did it with single, instead of double, I would prefer BEM.

**Comment by eatonphil** [comment]
Although one format could look better or worse for any person, I personally don't really want to think about that. I'd rather just go with the "official" way SUIT says here.

**Comment by eatonphil** [comment]
We've started applying this, so I'm closing.
