### ISSUE TITLE
Would like ability to see zone file

### ISSUE THREAD

**Issue by Ben-Coleman** [linode/manager#6341]
In the domain section of the cloud manager, one thing I miss (that the old Linode Manager had) is the ability to see the zone file for the domain.  It allowed you to quickly check if a particular change had been added to the zone file, and, as a plain text format, it could be text mangled to pull out information easier than it can be pulled from the DNS Manager page (I was asked today to come up with a list of our subdomains.  The web site isn't really conducive to grabbing that.  The zone file would have made it pretty easy).

**Comment by johnwcallahan** [comment]
Hi @Ben-Coleman, we've considered adding this feature to Cloud Manager, but right now it is not on our roadmap. There is some more information on this Community Site post: https://www.linode.com/community/questions/19365/how-do-i-export-a-zone-from-linode-in-a-bind-format

If you're looking for an easier way to interact with your Domain Records, I'd recommend using the [Linode CLI](https://www.linode.com/docs/platform/api/linode-cli/). For example, to list a Domain's records: 

```
$ linode-cli domains records-list
```

This is powerful when combined with a tool like [jq](https://stedolan.github.io/jq/). As an example, this will list the name and target of all A records on a Domain:

```
$ linode-cli domains records-list <domainID> --json | jq '.[] | select(.type="A") | "\(.target) | \(.name)"'
"1.1.1.1 | subdomain1"
"2.2.2.2 | subdomain2"
```
