### ISSUE TITLE
Add global error catch

### ISSUE THREAD

**Issue by eatonphil** [linode/manager#645]

**Comment by bralski1** [comment]
Phil - can you please provide more info? Thx.

**Comment by eatonphil** [comment]
Sure, we may want to track errors and report them to the API so we can help debug remotely.

**Comment by mparke** [comment]
If api doesn't have support yet, consider looking at sentry/ravenjs

**Comment by na3d** [comment]
Make sure to sanitize data if using third party, no big deal.
