### ISSUE TITLE
Add graphs to detail page

### ISSUE THREAD

**Issue by eatonphil** [linode/manager#65]
Phil suggests d3.

**Comment by eatonphil** [comment]
Had a ton of issues using D3. I settled with [Chartjs](http://www.chartjs.org/). Chartjs uses canvas while D3 uses SVG (by default?).

Here is a screenshot.
![screen shot 2016-06-20 at 6 45 25 pm](https://cloud.githubusercontent.com/assets/3925912/16212677/6511eba8-3717-11e6-84b3-49df5d7db4a9.png)

**Comment by SirCmpwn** [comment]
I've used Chart.js before. I think we should invest more time in trying to figure out D3.

**Comment by SirCmpwn** [comment]
I can take a whack at it if you'd like.

**Comment by eatonphil** [comment]
I couldn't figure out how to scale the svg. If you can get it to fill 100% width while keeping the height at 300px, d3 would be great.

**Comment by SirCmpwn** [comment]
Commit what you have so far and I'll take a look on the morning.

**Comment by eatonphil** [comment]
This is probably useless for any d3 effort, but [here](https://github.com/eatonphil/manager/tree/chartjs) you go. I don't have the d3 code but I was able to get it (barely) working using [rd3](https://github.com/yang-wei/rd3).
