### ISSUE TITLE
Warning when "Boot This Config" is clicked

### ISSUE THREAD

**Issue by andysh-uk** [linode/manager#6551]
I discovered by accident that the "Boot this config" menu option under Disks/Configs > Configuration > (configuration profile ...) forces a reboot of the Linode into that configuration - even if it's already booted.

I feel this should have a warning prompt instead of automatically forcing a reboot (in my case it was a purely accidental click - I was going to hit Edit and my hand slipped!)

When you choose to Reboot or Power off a Linode, you get a clear warning and confirmation prompt - this option should have the same as it is forcing a reboot.

**Comment by johnwcallahan** [comment]
Good catch, we should definitely add a confirmation modal there. We'll get this in an upcoming release.

**Comment by johnwcallahan** [comment]
Quick update on this:

This was done as part of an app-wide UI update being released in a few months.

![Screen Shot 2020-07-20 at 3 19 24 PM](https://user-images.githubusercontent.com/16911484/87977385-a6c72780-ca9c-11ea-846e-0b2bb045c9c0.png)

I'll keep this opened until the code is actually been released to production, but the specific feature you requested has been merged with https://github.com/linode/manager/pull/6602.

**Comment by andysh-uk** [comment]
Brilliant, looks just the job!

Cheers for the update,
Andy

**Comment by Jskobos** [comment]
This has now been released. I'm going to mark this as closed; thanks for your feedback, and please let us know if you see anything in our updated UI that needs improvement.
