### ISSUE TITLE
Total Object storage on Object Storage Page?

### ISSUE THREAD

**Issue by Oloryn** [linode/manager#6588]
I note that the Size column on each bucket on the Object Storage Page is now live.  Thanks!  One more little thing would be handy.  How about a total of the size for all buckets?

**Comment by johnwcallahan** [comment]
Good feedback, @Oloryn. I just made a note of this in our internal tracker. There are some further improvements coming to the Object Storage interface in a few months; we might be able to roll this in as well.

**Comment by Jskobos** [comment]
This was released a while back but we forgot to update this issue. Sorry about that @Oloryn, and thanks again for the feedback.
