### ISSUE TITLE
Linode details summary page changes wrt Chris's feedback

### ISSUE THREAD

**Issue by eatonphil** [linode/manager#66]
* [x] Rename "launch" button
* [x] Make all launchy buttons same color & less prevalent
* [x] Add SSH button next to SSH command
* [x] Change "Lish" to "Text Console" or so
* [x] Change "Glish" to "Graphical Console" or so
* [x] Make the Linode's current state bigger
* [x] Move state management near the state (i.e. power)
* [ ] Too much text on the detail page (who cares)

**Comment by eatonphil** [comment]
![screen shot 2016-06-07 at 4 52 02 pm](https://cloud.githubusercontent.com/assets/3925912/15874230/303d4f68-2cd0-11e6-98e5-9081f9850be4.png)

**Comment by SirCmpwn** [comment]
s/Graphic/Graphical/

**Comment by eatonphil** [comment]
I was initially imagining a lot more gore.
