### ISSUE TITLE
Cannot take first snapshot

### ISSUE THREAD

**Issue by eatonphil** [linode/manager#660]
Snapshot option should probably have a take snapshot button if no snapshot currently exists. Bit of an oversight. :)

![screen shot 2016-11-09 at 7 26 33 pm](https://cloud.githubusercontent.com/assets/3925912/20160043/76eb0714-a6b2-11e6-9fa2-51f4d0ea87f6.png)

**Comment by briansteffens** [comment]
It should probably always have that button right? Not just for the first one?

**Comment by eatonphil** [comment]
I'm working with an older version of a mockup here, but here's my shot for now.

![screen shot 2017-01-05 at 9 02 15 am](https://cloud.githubusercontent.com/assets/3925912/21683074/bc68a3c4-d325-11e6-858e-54c21d2bb0c8.png)
