### ISSUE TITLE
Reset root password after error password info text stays up while rating rectangles are reset

### ISSUE THREAD

**Issue by eatonphil** [linode/manager#666]

**Comment by eatonphil** [comment]
![screen shot 2016-11-11 at 10 17 55 am](https://cloud.githubusercontent.com/assets/3925912/20219568/16a39776-a7f8-11e6-8f59-45c656a05c5a.png)

**Comment by abemassry** [comment]
could not reproduce
![image](https://cloud.githubusercontent.com/assets/1616275/21647502/9276fd08-d268-11e6-905a-8884486ad095.png)
