### ISSUE TITLE
Allow setting TTL (last parameter of SOA record) separate from default TTL?

### ISSUE THREAD

**Issue by Ben-Coleman** [linode/manager#6660]
One thing I'd like to see in DNS editing for the SOA record is the ability to change the SOA TTL field ( the last field in the SOA record) separately from the Default TTL.

I note that this field originally had the meaning of the minimum TTL for the zone, and it has often been interpreted as the default TTL, but the current meaning is that of the TTL to be used for negative caching (caching of a NXDOMAIN response for a particular domain in the zone).  E.g. see [The Wikipedia SOA record entry](https://en.wikipedia.org/wiki/SOA_record).

The current LInode implementation puts the Default TTL in that field.  This becomes annoying when you add a new DNS record (which should have zero time 'propagation' (a misnomer) once the change hits the authoritative DNS servers), and someone tries to access it before it makes its way to the ns?.linode.com servers (easy to do given the once-every-quarter-hour-update nature of Linode's DNS).  If you've got a long default TTL (a day or more), you'll now have to wait for that day or more before being able to use it, as the local caching DNS server will have that NXDOMAIN cached for the full default TTL time.  This tends to discourage using a longer default TTL for a zone, resulting in more requests going to Linode's DNS servers.

The idea behind the current meaning of the SOA TTL field is that you can put a shorter TTL value there, and cached NXDOMAIN replies can be expired quicker, while still being able to have a longer default TTL.  This means you have to be able to set it apart from the value for the default TTL.  Can this be added to the SOA edit page?

**Comment by andysh-uk** [comment]
Hi Ben, totally get what you’re saying.

I just wanted to point out one thing:

> easy to do given the once-every-quarter-hour-update nature of Linode's DNS

Since July, Linode now pushes DNS changes near-instantly (within 60 secs) - [see this blog post](https://www.linode.com/blog/linode/linode-turns-17/)

**Comment by WilkinsKa1** [comment]
Hi @Ben-Coleman , thanks for reaching out! The behavior you have noted is actually intentional and in-line with how DNS is expected to work. One possible solution for the case you've brought up may be to use a third-party DNS host that would support having secondary DNS servers and/or DNS delegation. The DNS improvements that @andysh-uk mentioned should also help in making updates faster.
