### ISSUE TITLE
Linode details networking page changes wrt Chris's feedback

### ISSUE THREAD

**Issue by eatonphil** [linode/manager#67]
* [x] Show all of the things (i.e. IP addresses)
* [x] Edit network button needs to be rethought

Edit mode:

* [x] Remove multi-delete interface
* [x] Make more clear the distinction between the UI parts
* [x] Single delete only plus confirmation modal
* [x] "Add an IP address" as a new section
* [x] Rename failover IP addresses
* [x] Swap IP needs to deal with moving IP addresses

**Comment by eatonphil** [comment]
![screen shot 2016-06-07 at 4 47 26 pm](https://cloud.githubusercontent.com/assets/3925912/15874076/8cd8918e-2ccf-11e6-995c-58deb2aafd58.png)
![screen shot 2016-06-07 at 4 47 55 pm](https://cloud.githubusercontent.com/assets/3925912/15874091/a86932d2-2ccf-11e6-9bc6-96909156d54c.png)
![screen shot 2016-06-07 at 4 48 31 pm](https://cloud.githubusercontent.com/assets/3925912/15874105/b3023e5a-2ccf-11e6-9dc8-d39c0275ae2e.png)
![screen shot 2016-06-07 at 4 48 53 pm](https://cloud.githubusercontent.com/assets/3925912/15874118/bfb58120-2ccf-11e6-999e-474ae67c596d.png)

**Comment by SirCmpwn** [comment]
"Please explain your use-case. This will be reviewed by a human."

**Comment by SirCmpwn** [comment]
How does it look with the dividers extended across the full width?

**Comment by eatonphil** [comment]
![screen shot 2016-06-08 at 9 52 37 am](https://cloud.githubusercontent.com/assets/3925912/15896567/d8032c2a-2d5e-11e6-8b9c-eb5a4cf86878.png)
![screen shot 2016-06-08 at 9 52 52 am](https://cloud.githubusercontent.com/assets/3925912/15896568/d80779ce-2d5e-11e6-8655-3ba74b26d865.png)
![screen shot 2016-06-08 at 9 53 10 am](https://cloud.githubusercontent.com/assets/3925912/15896569/d80b9a5e-2d5e-11e6-8c75-624b3baadd65.png)

**Comment by eatonphil** [comment]
Following styles from #48 
![screen shot 2016-06-08 at 2 30 50 pm](https://cloud.githubusercontent.com/assets/3925912/15906170/b5334a1e-2d85-11e6-910a-4127559ce7a0.png)
