### ISSUE TITLE
getLinode() return AxiosPromise<Linode> vs Promise<Linode>

### ISSUE THREAD

**Issue by delaneyj** [linode/manager#6775]
most of the API returns Promise<T> however some return AxiosPromise<T>.  Is there a specific reason for this as you have to do an extra layer of extraction from the `.data` field from axios that appears to be an implementation detail.

**Comment by johnwcallahan** [comment]
@delaneyj thanks for catching this. I opened a PR, though since it's a breaking change, we'll need to wait until our next major version release (date TBD).

**Comment by Jskobos** [comment]
@delaneyj This has now been released. Interested in your input: we're considering a future enhancement where we add a new wrapper that exposes some of the request metadata (response code and possibly headers). Would that useful to you?
