### ISSUE TITLE
IP Transfer is only for IPv4

### ISSUE THREAD

**Issue by ghost** [linode/manager#6777]
All linode servers some with both IPv4 and IPv6 addresses. The IP Transfer tool can only swap the IPv4 address between linode servers and not the IPv6 address.

This is a serious issue, it makes the IP Transfer tool rather useless.

Because the admin would need to make heavy modifications to DNS records and other things like local address assignments, deployment and firewall changes, so on and so forth.

If there is a network/design limitation and you can't swap IPv6 addresses, at least add a big red warning on top of the IP Transfer option to warn users that it does half the job its supposed to do. Or rename it to "IPv4 Transfer" :)

**Comment by andysh-uk** [comment]
This is my biggest frustration with the Linode platform, and it’s shared by others on the community site - such as:

https://www.linode.com/community/questions/19938/how-do-i-swap-ipv6-addresses-between-linodes

I suspect it is some technical limitation as Digital Ocean also only offers “hit swappable” v4 addresses - but I have no idea what.

Any Linode that uses IPv6 for public services (which let’s face it, you should these days) cannot be swapped out as easy as the IP Transfer suggests - IPv6 addresses still need to be handled manually, either by Linode or through DNS.

I would love to understand why this seemingly small thing cannot be done!

**Comment by WilkinsKa1** [comment]
Hi @robo2bobo , thanks for sharing this feedback! It's currently not possible to transfer a SLAAC IPv6 address due to the way MAC addresses are assigned to each Linode. With a range of IPv6 addresses, it's possible to manually hotswap, though ranges must be requested from Support. I agree we can add some clarity to the limitations of this feature in Cloud. I'll keep this open and provide an update when the work to update our messaging has been completed.

**Comment by robo2bobo** [comment]
Its important to mention 2 things:

- the IP Transfer tool is not for IPv6 migration
- an alternative method is to use backup snapshots and restore to another linode server

I can picture a situation with a tired admin, rushing to use the IP transfer tool and then later on, wondering why **half** the traffic is still going to the old server...

communication is key :+1: 

thank you!

**Comment by bcmertz** [comment]
IPv6 transfer is being released in the upcoming release
