### ISSUE TITLE
Broken link on the server label

### ISSUE THREAD

**Issue by davide93** [linode/manager#6779]
The link on the server name leads to a broken link/page.

![linode](https://user-images.githubusercontent.com/3228835/90510002-843b3380-e15a-11ea-8cb0-9238682ba773.png)

**Comment by johnwcallahan** [comment]
Hi @davide93, thanks for reporting this bug. This was fixed in https://github.com/linode/manager/pull/6810 and will go out in our next release, scheduled for next week.
