### ISSUE TITLE
Cancel backups modal doesn't render properly

### ISSUE THREAD

**Issue by na3d** [linode/manager#687]
It only has a title, not text or buttons.

**Comment by eatonphil** [comment]
Renders correctly for me. Do you have console errors?
![screen shot 2016-11-15 at 10 24 19 am](https://cloud.githubusercontent.com/assets/3925912/20311398/a7fbce5a-ab1d-11e6-89d1-93d604062b75.png)

**Comment by eatonphil** [comment]
Actually, I believe @abemassry is taking care of this in #513
