### ISSUE TITLE
Make typography great again

### ISSUE THREAD

**Issue by eatonphil** [linode/manager#72]

**Comment by eatonphil** [comment]
If we're going to go with an open source font, I recommend we use either [Heebo](https://fonts.google.com/specimen/Heebo) or [Yantramanav](https://fonts.google.com/specimen/Yantramanav) importing the Thin and Light weights.

**Comment by eatonphil** [comment]
Here are two screenshots of Heebo:

![screen shot 2016-06-14 at 3 26 11 pm](https://cloud.githubusercontent.com/assets/3925912/16056637/6781a8d8-3244-11e6-972e-51d7806e5d48.png)
![screen shot 2016-06-14 at 3 26 24 pm](https://cloud.githubusercontent.com/assets/3925912/16056638/6781c854-3244-11e6-8e3c-ea1dcc5b8c4d.png)

Here is Yantramanav:
![screen shot 2016-06-14 at 3 27 29 pm](https://cloud.githubusercontent.com/assets/3925912/16056668/8c464e08-3244-11e6-960d-b1536f104f67.png)

Actually Yantramanav won't do because the header links looks terrible with it.

**Comment by SirCmpwn** [comment]
Heebo++
