### ISSUE TITLE
Add Flow type checking and reasonable configuration

### ISSUE THREAD

**Issue by eatonphil** [linode/manager#748]

**Comment by mparke** [comment]
@eatonphil what does this mean? Is it still relevant?

**Comment by na3d** [comment]
@eatonphil  what is this?

**Comment by eatonphil** [comment]
I'd still recommend doing this but it's too big of an argument to only make in an issue. The benefits of static typing are well known for large/growing projects. TypeScript or Flow would be sufficient and appropriate.
