### ISSUE TITLE
Number of events is always 20

### ISSUE THREAD

**Issue by andysh-uk** [linode/manager#7519]
I really like the new Manager UI, but find this (minor) point quite irritating.

When you click the notification icon, the “events” section always shows the number 20. I assume this is the number of events displayed.

I feel there are 2 things here:

* I have many more events than 20 - should it not say “20+” to indicate there are more? I don’t feel this should show the accurate count as you can’t get to all of them anyway; it only ever shows 20. A visual indicator that there are more would be useful.
* Would it not be more useful to show the number of un-seen events? I feel this should correlate with the number shown on the bell. I.e. if the bell shows 6, and I have one “notification”, then “events” should show 5, not 20.

As it is, anyone that’s been relatively active setting up Linodes, domains, etc. will quickly reach that magic 20, and won’t see any other number here.

**Comment by andysh-uk** [comment]
I’ve just realised - this is only on a mobile phone view. On a tablet or desktop, the “notifications” and “events” groups in the drawer care always expanded and do not show the count.

On a mobile, they are collapsed with a “badge” showing the count - this is what I’m referring to.

**Comment by andysh-uk** [comment]
Hi @bnussman 

Yes my feedback on this still stands.

**Comment by h3ssan** [comment]
Hi @andysh-uk 

Is this still an active issue?
Please upload a screenshot for the issue

**Comment by bnussman-akamai** [comment]
We've made a lot of changes to our events code over the last year which I think addressed this so some extent.  I'm going to close this issue, but feel free to re-open or create a new issue if there are further improvements or changes you think we could make 🙏
