### ISSUE TITLE
Firewall default changes in v1.36.0

### ISSUE THREAD

**Issue by andysh-uk** [linode/manager#7524]
Following the change in v1.36.0, that firewalls no longer create default SSH and DNS rules, the text on the "Create Firewall" blade is now incorrect:

From [the release notes](https://github.com/linode/manager/releases/tag/linode-manager%401.36.0):

> Remove default Firewall rules (new Firewalls are created empty, with policies set to Accept)

In the blade in Manager:

> Firewalls are created with default rules to allow inbound SSH (port 22) and DNS (port 53) traffic. You can edit these rules or add additional rules once the Firewall has been created.

Also - unrelated - the tag created for the v1.36.0 is "linode-manager@1.36.0" whereas the version link within manager is looking for "linode-manager@v1.36.0" and results in a 404 on Github. Previous releases did have the "v" in the tag name.

**Comment by johnwcallahan** [comment]
Thanks @andysh-uk, good catch! We'll get the Firewall text fixed in our next release.
