### ISSUE TITLE
compilation error when including @linode/api-v4 as a dependency

### ISSUE THREAD

**Issue by elmerbulthuis** [linode/manager#7686]
when compiling with typescript we get the following error

```
node_modules/@linode/api-v4/lib/support/types.d.ts:1:24 - error TS2307: Cannot find module 'src/account/types' or its corresponding type declarations.

1 import { Entity } from 'src/account/types';
                         ~~~~~~~~~~~~~~~~~~~
```

workaround:

in a file called global.d.ts:
```ts
declare module "src/account/types" {
    export interface Entity {
    }
}
```

but this is not ideal!

**Comment by bnussman** [comment]
Can you provide some more information on how to reproduce this?

**Comment by elmerbulthuis** [comment]
sure!

first setup a typescript project..

install linode sdk
```sh
 npm install @linode/api-v4@0.53.2
```
then create a file with this concent:
```typescript
import * as linodeApi from "@linode/api-v4";

let linode: linodeApi.Linode;
```

compile and there is the error!

**Comment by bnussman** [comment]
I'm unable to replicate any error! Maybe this could be a `tsconfig.json` related?

**Comment by sinoz** [comment]
@bnussman Here is an example project that illustrates the problem: https://github.com/Gameye/reproduce-linode-issue

**Comment by bnussman** [comment]
I'm not completely sure of the root cause, but I was able to get your Typescript compiler to run by adding `"skipLibCheck": true`  into your tsconfig.json. 

```json
{
  "compilerOptions": {
    "target": "ES2020",
    "module": "commonjs",
    "sourceMap": true,
    "outDir": "./node",
    "rootDir": "./src",
    "importHelpers": true,
    "strict": true,
    "skipLibCheck": true
  },
  "include": [
    "src/**/*"
  ]
}
```

Let me know if this this is enough for you to get up and running! If not, let me know so I can look more into it! Thanks!

**Comment by sinoz** [comment]
> I'm not completely sure of the root cause, but I was able to get your Typescript compiler to run by adding `"skipLibCheck": true` into your tsconfig.json.
> 
> ```json
> {
>   "compilerOptions": {
>     "target": "ES2020",
>     "module": "commonjs",
>     "sourceMap": true,
>     "outDir": "./node",
>     "rootDir": "./src",
>     "importHelpers": true,
>     "strict": true,
>     "skipLibCheck": true
>   },
>   "include": [
>     "src/**/*"
>   ]
> }
> ```
> 
> Let me know if this this is enough for you to get up and running! If not, let me know so I can look more into it! Thanks!

@elmerbulthuis's temporary workaround works as well but it is not actually fixing the problem. The point of using TypeScript is to make sure that everything is checked!

If you look at all the other imports throughout the source code, you can see that no other import points from the source root. So one solution would be to change:

```
import { Entity } from 'src/account/types';
```

to:

```
import { Entity } from '../account/types';
```

And I can make a PR for that. However, I don't know why it even starts with `src` in the first place. Is this an actual bug or was this done on purpose?

**Comment by bnussman** [comment]
I think we use paths that start with `src/` by design. I'll keep looking into this...
