### ISSUE TITLE
Missing validation on firewall rule label

### ISSUE THREAD

**Issue by andysh-uk** [linode/manager#7750]
When adding a firewall rule that has spaces, there is no error displayed in the UI, but the API has returned a validation error.

The UI just looks like it does nothing - no error is presented to the user.

To reproduce:

- Create a new firewall rule
- Enter a name with a space (mine was: "MariaDB Downloads")
- Click Add Changes, and then Save

Expected behaviour:

Warning message advising that the firewall label contains spaces on clicking Add Changes.

Actual behaviour:

The UI does nothing; the new row remains blue like it is unsaved. In the browser tools, a validation warning has been returned from the request:

```
PUT  https://cloud.linode.com/api/v4beta/networking/firewalls/xxx/rules
```

```json
{"errors": [{"reason": "Must include only ASCII letters, numbers, underscores, periods, and dashes", "field": "rules.outbound[4].label"}]}
```

**Comment by HanaXu** [comment]
@andysh-uk The error seems to be displayed in the UI after clicking save. Can you confirm if this is still an issue?

![image](https://user-images.githubusercontent.com/14323019/128921725-8e1e3915-ed23-4a47-9f5c-ebb883546511.png)

**Comment by andysh-uk** [comment]
Hi @HanaXu 

Yes, I can confirm that message is there.

However I have 2 issues with the implementation of this:

- on an iPad (not tried on a desktop browser yet) on clicking Save Changes, the screen jumps slightly as if it is trying to scroll up, but the validation error still isn’t visible. It took me a few seconds to realise it had appeared at the top of the screen, out of view
- If I’ve added a few rules, how do I know which one caused the validation error? I feel that message should be displayed when you click to add the rule, in the same way as you get “Must be a valid IPv4 or IPv6 range” when entering an invalid IP address. It should highlight the label field and tell me then it should be alpha
