### ISSUE TITLE
Show Longview on Linode detail

### ISSUE THREAD

**Issue by tsmgeek** [linode/manager#7894]
Would it be possible if Longview is enabled for a node to show extra tab with all that info, or link to the longview detail page for that node.

**Comment by bnussman-akamai** [comment]
Hey @tsmgeek 👋 

Sorry it's been years before we're responded to this 😭.  Unfortunately, we don't have any plans on our roadmap to add Longview specifically to the Linode details page, **_but_** there are new observability products in active development that I think may satisfy this ask once they are generally available.

I'm going to close this for now, but feel free to reach back out if you have any further comments or questions
