### ISSUE TITLE
Replace custom Dropdown component with Bootstrap dropdowns and regular <select>s where relevant

### ISSUE THREAD

**Issue by eatonphil** [linode/manager#81]

**Comment by eatonphil** [comment]
I'm going to suggest we move to Bootstrap dropdowns and regular selects everywhere instead of the custom dropdown component.

**Comment by eatonphil** [comment]
So I'm going to punt on this and pull this out of "in progress" for now. I'll add another task to actually customizing the dropdowns and selects after the switch to bootstrap.

**Comment by SirCmpwn** [comment]
:+1:
