### ISSUE TITLE
Clean up linode details header

### ISSUE THREAD

**Issue by eatonphil** [linode/manager#83]
http://tympanus.net/codrops/2014/09/02/tab-styles-inspiration/

**Comment by SirCmpwn** [comment]
I'm pretty happy with the tab design you came up with. Could use some animations though.

**Comment by eatonphil** [comment]
It doesn't have to be as radically different as in the link. But I don't think it's quite polished yet, so I want to keep trying some variations.

The transitions in the current implementation are nice.

**Comment by SirCmpwn** [comment]
Current transitions are just the global `* { transition: ...; }` rules. I was playing for a little while with sliding the tab background over to the new tab and also with making the background slide in and out from the bottom, but abandoned the efforts cause I didn't think it was necessary.

**Comment by eatonphil** [comment]
No plans right now.
