### ISSUE TITLE
Chrome tab crashes when trying to replace object storage file

### ISSUE THREAD

**Issue by benbro** [linode/manager#8373]
When dragging an existing file to a object storage bucket in the manager a button appears asking whether to replace the file.
When I click on the Replace button the Chrome tab crashes.

Tested with Chrome 101.0.4951.64

**Comment by bnussman** [comment]
Fixed by https://github.com/linode/manager/pull/8556 🔧 and deployed in [v1.77.0](https://github.com/linode/manager/releases/tag/linode-manager%40v1.77.0) 🚀

Thank you for reporting this @benbro!
