### ISSUE TITLE
Try right-aligning right side of header

### ISSUE THREAD

**Issue by eatonphil** [linode/manager#839]

**Comment by na3d** [comment]
![screen shot 2017-01-12 at 4 10 34 pm](https://cloud.githubusercontent.com/assets/6047142/21908469/e0100044-d8e1-11e6-89a8-2ab27c0855ab.png)
![screen shot 2017-01-12 at 4 11 06 pm](https://cloud.githubusercontent.com/assets/6047142/21908470/e0176e74-d8e1-11e6-9129-320e614d3e1a.png)

**Comment by briansteffens** [comment]
That looks really weird with such a large gap on the right side. Maybe it would look better on a page with less gap between browser edge and right side of the content?

**Comment by na3d** [comment]
More similar to the current marketing page header:
![screen shot 2017-01-13 at 9 36 45 am](https://cloud.githubusercontent.com/assets/6047142/21933567/e7a19182-d973-11e6-8d46-f95cf18a91a1.png)

**Comment by na3d** [comment]
Were you thinking something like this @briansteffens 
![screen shot 2017-01-13 at 9 41 15 am](https://cloud.githubusercontent.com/assets/6047142/21933715/7d70c138-d974-11e6-91da-00bd0c712375.png)

**Comment by na3d** [comment]
https://github.com/na3d/manager/tree/header-right
![screen shot 2017-01-18 at 9 47 17 am](https://cloud.githubusercontent.com/assets/6047142/22068576/73a0b4a4-dd63-11e6-84c4-fc20cd2724e9.png)

**Comment by na3d** [comment]
https://github.com/na3d/manager/tree/header-right
![screen shot 2017-01-18 at 9 59 25 am](https://cloud.githubusercontent.com/assets/6047142/22068996/d6488248-dd64-11e6-8c14-47e451719a92.png)

**Comment by na3d** [comment]
Another idea, so there is some balance on the screen.
![screen shot 2017-01-18 at 10 17 59 am](https://cloud.githubusercontent.com/assets/6047142/22069721/72e35068-dd67-11e6-8d6a-562c57500791.png)
