### ISSUE TITLE
Implement components for common information

### ISSUE THREAD

**Issue by na3d** [linode/manager#85]
We need something for loading:
* [x] Plan names
* [x] Datacenters
* [x] Backups
* [x] Distribution
* [x] Warning button ( ! )

We definitely don't want to call a plan Linode 1024 in one place and Linode 1G in another.

**Comment by SirCmpwn** [comment]
@caker we need a call on the distinction between "Linode 1024" and "Linode 1G" (or 2G I guess :wink:)

**Comment by eatonphil** [comment]
My vote is for 1G. It makes it much easier for all plans - big and small.
