### ISSUE TITLE
Add Linode Form: Remove hide/show for single input

### ISSUE THREAD

**Issue by mparke** [linode/manager#850]
Hide/show for single input was discussed as weird, can be inlined to be more clear.

![screen shot 2016-12-22 at 1 30 33 pm](https://cloud.githubusercontent.com/assets/709951/21436153/1b5f9256-c84b-11e6-93ed-9575f7c6b34d.png)

**Comment by eatonphil** [comment]
> can be inlined to be more clear.

Or just dropped would be fine in this case too.
