### ISSUE TITLE
Consider linode icon for gravatar default

### ISSUE THREAD

**Issue by mparke** [linode/manager#858]
Design suggestion to use a linode icon or something other than the gravatar default for the user menu:

![screen shot 2016-12-22 at 2 10 13 pm](https://cloud.githubusercontent.com/assets/709951/21437175/63415b7c-c850-11e6-8928-28c4c963941b.png)

**Comment by eatonphil** [comment]
I think having an empty user icon would be a little more indicative of the desired use.

![image](https://cloud.githubusercontent.com/assets/3925912/21613928/6fa1211e-d1a5-11e6-9037-76c69c7d8344.png)

**Comment by na3d** [comment]
Maybe just a single block?
