### ISSUE TITLE
Unable to use with nodejs (commonjs) or typescript

### ISSUE THREAD

**Issue by Jishun** [linode/manager#8675]
Trying to reference the javascript sdk 
started with `npm i @linode/api-v4`
and try the basic example
```js
import { baseRequest } from '@linode/api-v4'

baseRequest.interceptors.request.use(config => {
  const myToken = 'token';

  return {
    ...config,
    headers: {
      ...config.headers,
      Authorization: `Bearer ${myToken}`
    }
  };
});
```
received below error 
```
Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/djs/dev/temp/node_modules/@linode/api-v4/lib/index.js from /Users/djs/dev/temp/linode.ts not supported.
index.js is treated as an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which declares all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use dynamic import() which is available in all CommonJS modules, or change "type": "module" to "type": "commonjs" in /Users/djs/dev/temp/node_modules/@linode/api-v4/package.json to treat all .js files as CommonJS (using .mjs for all ES modules instead).

    at require.extensions.<computed> [as .js] (/usr/local/lib/node_modules/ts-node/dist/index.js:851:20)

```

the error is kinda clear, it believes itself a ES module so rejected request from commonjs, then I set the project to `module` by adding `"type": "module"` in `package.json`
however it turns out this package references another commonjs module that produces another error: 
```
file:///Users/djs/dev/temp/node_modules/@linode/validation/lib/esm/index.js:219
import { parse as parseIP, parseCIDR } from "ipaddr.js";
                           ^^^^^^^^^
SyntaxError: Named export 'parseCIDR' not found. The requested module 'ipaddr.js' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'ipaddr.js';
const { parse: parseIP, parseCIDR } = pkg;
```
The same behaviour with `js` or `ts`. when using `ts` , `tsc` does compile the code to proper js file. but later executing with `node` gives the above error.  the same error when executing the ts file with `ts-node`

Can't find out what I'm missing. 
is there a sample nodejs or TypeScript project that I can take and have a quick try ?

**Comment by bnussman** [comment]
Hey @Jishun! Thank you for reporting this issue. We were able to replicate it and are working on a fix. In the mean time, if you need to use this package, we recommend you use version `0.75.0` until we get this fixed. 

```
npm i @linode/api-v4@0.75.0
```

**Comment by bnussman-akamai** [comment]
@Jishun Alternatively, you could set the following in your `tsconfig.json`

```
"module": "umd"
```

**Comment by bnussman-akamai** [comment]
We have fixed this issue by publishing `@linode/validation` v0.17.1, which is a dependency of @linode/api-v4.
