### ISSUE TITLE
@linode/validation/lib/esm/index.js changed to call 'ipaddr.js' CommonJS module

### ISSUE THREAD

**Issue by lucdouwen** [linode/manager#8713]
Hi, 
I am using your wrapper to create a DNS domain and import records from a zone file
https://github.com/Evolane/linode-dns-tools
I have a correction there in ./node_modules/@linode/validation/lib/esm/index.js for the error below. 
Can you integrate this? 

Regards,
Luc

$ node linode_create_domain.js -f importfiles/akamai.test.dns.txt -t 9138exxxxxxxxxxxxxxxxxxxx
file:///Users/xxxxxxx/projects/linode-dns-tools/node_modules/@linode/validation/lib/esm/index.js:219
import { parse as parseIP, parseCIDR } from "ipaddr.js";
                           ^^^^^^^^^
SyntaxError: Named export 'parseCIDR' not found. The requested module 'ipaddr.js' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:
import pkg from 'ipaddr.js';
const { parse: parseIP, parseCIDR } = pkg;  
```
)

**Comment by bnussman-akamai** [comment]
We have fixed this issue by publishing `@linode/validation` v0.17.1, which is a dependency of @linode/api-v4.

**Comment by bnussman-akamai** [comment]
Fixed in `api-v4` versions >=0.85.0
