### ISSUE TITLE
Styleguide: Buttons (Simple)

### ISSUE THREAD

**Issue by mparke** [linode/manager#888]
Document buttons used within the app in a styleguide section

Includes:

- default
- primary
- cancel
- submit

Also:

- `<Section name="buttons" title="Buttons"></Section>`
- define a `Buttons.scss`
- define a `Buttons.js` in `/styleguide/components/sections`

Styleguide Index: #884
reference #877

**Comment by eatonphil** [comment]
The scss is going to be less complex (per button) if you create 3 (or 4 if you include cancel) React component buttons and associated scss files. Afterward, you should be able to get rid of every line of scss currently used to style any buttons anywhere in ~/../scss.

Requirements:
* all buttons enter their changed state on hover and while clicked, but should return to their normal state immediately unmouseout (even if the button has not lost focus!)
  * this could mean dropping :focus or :active rules or both, not sure
* default buttons are light gray with black text; hover turns the background gray
* primary buttons are blue with white text; hover turns the background white, text blue, and border remains blue
* submit buttons are not a special case in terms of styles, they should just be default
* cancel buttons are blue link-like with no background or border; hover should only add text-underline

**Comment by briansteffens** [comment]
Would it make sense to call the buttons:

- default buttons = Button
- primary buttons = PrimaryButton
- cancel button = LinkButton (or something?)

Looks funny to say DefaultButton all over the place and we have a lot of links that aren't technically cancellations of anything but otherwise share the behavior of CancelButton

**Comment by briansteffens** [comment]
How about the grayed-out `.delete-button` like on linodes/{label}/settings/advanced to delete a config?
