### ISSUE TITLE
Mockup create page disabled button helper

### ISSUE THREAD

**Issue by abemassry** [linode/manager#907]

**Comment by eatonphil** [comment]
Few thoughts bundled into one here:

* Add back in the current section completed indicator
* Set max-width on the create page context
* Embiggen distro/datacenter/plan size to be boxier
  * Could even put them inside of the cards that are distributed across the row and set width: 100%, max-width: some-squarish-value
* Drop no distro box to give it less emphasis and to make the layout of cards look more natural

![screen shot 2017-01-05 at 2 46 43 pm](https://cloud.githubusercontent.com/assets/3925912/21695143/884e4ffe-d356-11e6-82ac-795b1d7a0448.png)
![screen shot 2017-01-05 at 2 46 52 pm](https://cloud.githubusercontent.com/assets/3925912/21695144/8854bb8c-d356-11e6-8365-efbff270dc1e.png)
![screen shot 2017-01-05 at 2 47 07 pm](https://cloud.githubusercontent.com/assets/3925912/21695145/88557d24-d356-11e6-8cce-9d636576738f.png)

**Comment by mparke** [comment]
There looks to be a lot of UI changes going on in this mockup, the issue is about `disabled button helper`?

@abemassry or @eatonphil could you provide a description on the issue/ what problem we're solving?

**Comment by eatonphil** [comment]
Key point concerning this issue is that the marker turns red when you hit the disabled button. Everything else is an iteration.

**Comment by mparke** [comment]
@eatonphil cool, could you provide a description of which state (of the three, grey, blue, red) happens when the user is interacting with the form? 

Also, have you taken into account how this may or may not apply on other forms?

**Comment by eatonphil** [comment]
Grey until they successfully complete the section. Blue when they do. And red if they click the disabled submit button.

I do not see this being applied to any other form we currently have -- I think it would be inappropriate / unnecessary in this way on other forms. In many senses the create page is unique. It *might* be applicable to other sections of the site like NodeBalancers or Longview. But so far the create in other sections have been simpler in every way. I.e. they don't require multi-step create.
