### ISSUE TITLE
Drop green highlight current section indication

### ISSUE THREAD

**Issue by eatonphil** [linode/manager#918]
The green background is obnoxious and unsightly. Furthermore, it attracts attention needlessly. Suggested alternative is to simply highlight (and bold) the current section:

![screen shot 2017-01-05 at 11 24 23 am](https://cloud.githubusercontent.com/assets/3925912/21688166/c8a6f078-d339-11e6-8fc9-3b194999be58.png)

**Comment by na3d** [comment]
I like the more subtle look here.

**Comment by mparke** [comment]
No longer relevant, sidebar dropped in https://github.com/linode/manager/pull/1162
