### ISSUE TITLE
Add a Linode

### ISSUE THREAD

**Issue by phuegel** [linode/manager#927]
Suggestions for Add a Linode / Create page - 
https://manager.alpha.linode.com/linodes/create

1. Increase font weight for only selected menu and submenus
I think its the class="ReactTabs__Tab ReactTabs__Tab--selected". Increase it so that it stands out more than the rest of the tabbed menu items.

2. Make default all Linux distro icons monochromatic still selected.
So when a user selects the distro, both the background and distro icon get filled in with color. (see attached sample screenshot)

3. Increase contrast on the color for each selected option on the page.
(see attached sample screenshot)
![image](https://cloud.githubusercontent.com/assets/19841047/21699316/290323c2-d369-11e6-99de-cccb7aa35586.png)

**Comment by na3d** [comment]
Overcome by events, closing.
