### ISSUE TITLE
404s not handled correctly on url with bad linode label

### ISSUE THREAD

**Issue by eatonphil** [linode/manager#942]
Try going to the linode page using a non-existing linode id/label

http://localhost:3000/linodes/1

The page should 404 or redirect to the /linodes page.

**Comment by na3d** [comment]
Redirect to /linodes +1

**Comment by eatonphil** [comment]
src/linodes/linode/layouts/IndexPage.js is an example of this right now, but there may be other places like this that should have better error handling if the label is not found.
