### ISSUE TITLE
BackupsCTA Rendering Incorrectly

### ISSUE THREAD

**Issue by martinmckenna** [linode/manager#9559]
https://github.com/linode/manager/blob/e1f34e93eb2c220d7aca2d178a72ca41e61bc6ab/packages/manager/src/features/Backups/BackupsCTA.tsx#L37

I think this line is evaluating to `false` somehow because all my Linodes have backups enabled and my `/preferences` data has no existence of the backups cta notification dismissal, which gets me a CTA that opens a drawer with no Linodes to backup:

<img width="1310" alt="Screenshot 2023-08-17 at 10 33 25 AM" src="https://github.com/linode/manager/assets/7387001/652664af-5c2a-41a3-88ef-443c9f1beba8">

**Comment by bnussman-akamai** [comment]
Hey Martin 👋🏼 Hope you are doing well! 

This component recently underwent a refactor (https://github.com/linode/manager/pull/9517) which has fixed this behavior 🎉

You can expect the fix to land in Cloud Manager v1.100.0 which is expected to release around Aug 21st 🗓️🧰

**Comment by bnussman-akamai** [comment]
Fixed by https://github.com/linode/manager/pull/9517 and released in [v1.100.0](https://github.com/linode/manager/releases/tag/linode-manager%40v1.100.0])
