### ISSUE TITLE
Use shrink-wrapped (but consistent) columns for all table-like data

### ISSUE THREAD

**Issue by eatonphil** [linode/manager#964]
Everywhere we display rows of information or rows of input / labels, the bootstrap columns containing them are too large. These columns should be shrink-wrapped to take up the minimum width of the largest row value for that column. The label column (left-most column) should then be right-aligned within the column like we try to do now.

Personally, I'm fine with using tables in every place that we have this need. The container the tables are inside of handle breaking on screen sizes. For instances, the Reset root password bit is in a col-sm-6 column (or similar) so it will flow under the Rescue mode bit when the screen size is too small. This is good. But the content inside of the Reset root password bit really has no need to reflow on screen size change, so table (display) would be sufficient and simple here.

There may be edge cases where we have small rows of data that need to be shrink-wrapped and also need to reflow within rows, but so far we have never seen one even in mockups.

**Comment by mparke** [comment]
For tabular information, tables are appropriate sure, but for forms or other content i'm going to disagree with this. We should not be using tables for any page layout. This issue needs to be discussed before being picked up.

**Comment by eatonphil** [comment]
No worries, this task was only supposed to be for discussion anyway. I was just trying to make my implementation idea clear.

**Comment by mparke** [comment]
@eatonphil is this issue still relevant?
