### ISSUE TITLE
Compilation error under Angular 16: Cannot find module 'src/regions' or its corresponding type declarations.

### ISSUE THREAD

**Issue by kekonn** [linode/manager#9655]
Full error:

```
Error: node_modules/@linode/api-v4/lib/account/types.d.ts:2:24 - error TS2307: Cannot find module 'src/regions' or its corresponding type declarations.

2 import { Region } from 'src/regions';
                         ~~~~~~~~~~~~~
 ```

This is a regression of issue #7686 and was introduced in [this commit](https://github.com/linode/manager/commit/b5b4ad137c37a20b4afc1f030444493ec4f3c789).

**Comment by bnussman-akamai** [comment]
Thank you for opening this issue! We released the fix in `@linode/api-v4@0.101.0`. Please reach out to us if you have anymore issues!
