### ISSUE TITLE
Backups > Take first snapshot throwing errors

### ISSUE THREAD

**Issue by mparke** [linode/manager#994]
Take first snapshot appears to throw an error

![screen shot 2017-01-16 at 3 41 03 pm](https://cloud.githubusercontent.com/assets/709951/21998373/5955bdcc-dc02-11e6-92eb-e56024546b20.png)

https://github.com/linode/manager/blob/master/src/linodes/linode/backups/layouts/BackupPage.js#L96

**Comment by na3d** [comment]
Closed by #1032
